// Generated by forge proof from cli-worktree-commands.md
import { describe, test, expect, beforeEach, afterEach, spyOn } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  listWorktrees,
  getWorktreesByWorkGroup,
  transitionWorktreeStatus,
  getValidTransitions,
  insertSpecEntry,
  insertSpecRun,
  getSpecEntryByPath,
  getSpecRunsByEntry,
} from './db.js';
import type { Database } from 'bun:sqlite';
import type { WorktreeStatus } from './db.js';
import crypto from 'crypto';

let db: Database;
let consoleLogs: string[];
let consoleErrors: string[];

beforeEach(() => {
  db = getTestDb();
  consoleLogs = [];
  consoleErrors = [];
});

function makeId(): string {
  return `wt-cmd-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeId();
  insertWorktree(db, {
    id,
    spec_path: 'specs/test.md',
    branch: 'forge/test',
    worktree_path: '/tmp/project-test',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── forge worktree list ─────────────────────────────────────────

describe('forge worktree list', () => {
  test('shows all worktrees with id, status, spec, branch, path, age', () => {
    const id = insertTestWorktree({
      spec_path: 'specs/auth.md',
      branch: 'forge/auth',
      worktree_path: '/tmp/project-auth',
      status: 'running',
    });

    const wt = getWorktree(db, id);
    expect(wt).not.toBeNull();
    // All required columns for list display
    expect(wt!.id).toBeTruthy();              // id
    expect(wt!.status).toBe('running');        // status
    expect(wt!.spec_path).toBe('specs/auth.md'); // spec
    expect(wt!.branch).toBe('forge/auth');     // branch
    expect(wt!.worktree_path).toBe('/tmp/project-auth'); // path
    expect(wt!.updated_at).toBeTruthy();       // age (computed from updated_at)
  });

  test('list --status <status> filters by worktree status', () => {
    insertTestWorktree({ status: 'running', branch: 'forge/r1', worktree_path: '/tmp/r1' });
    insertTestWorktree({ status: 'complete', branch: 'forge/c1', worktree_path: '/tmp/c1' });
    insertTestWorktree({ status: 'running', branch: 'forge/r2', worktree_path: '/tmp/r2' });

    const running = listWorktrees(db, 'running');
    expect(running).toHaveLength(2);
    expect(running.every(w => w.status === 'running')).toBe(true);

    const complete = listWorktrees(db, 'complete');
    expect(complete).toHaveLength(1);
    expect(complete[0].status).toBe('complete');
  });

  test('list --work-group <id> filters by work group', () => {
    insertTestWorktree({ work_group_id: 'wg-A', branch: 'forge/a1', worktree_path: '/tmp/a1' });
    insertTestWorktree({ work_group_id: 'wg-A', branch: 'forge/a2', worktree_path: '/tmp/a2' });
    insertTestWorktree({ work_group_id: 'wg-B', branch: 'forge/b1', worktree_path: '/tmp/b1' });

    const groupA = getWorktreesByWorkGroup(db, 'wg-A');
    expect(groupA).toHaveLength(2);
    expect(groupA.every(w => w.work_group_id === 'wg-A')).toBe(true);

    const groupB = getWorktreesByWorkGroup(db, 'wg-B');
    expect(groupB).toHaveLength(1);
  });

  test('list sorted by updated_at descending (most recently updated first)', () => {
    const id1 = insertTestWorktree({ branch: 'forge/old', worktree_path: '/tmp/old' });
    const id2 = insertTestWorktree({ branch: 'forge/new', worktree_path: '/tmp/new' });

    // Force distinct updated_at values
    const older = new Date(Date.now() - 60000).toISOString();
    db.run('UPDATE worktrees SET updated_at = ? WHERE id = ?', [older, id2]);
    transitionWorktreeStatus(db, id1, 'running');

    const all = listWorktrees(db);
    // Apply CLI sort: updated_at DESC
    all.sort((a, b) => b.updated_at.localeCompare(a.updated_at));

    expect(all[0].id).toBe(id1);
    expect(all[1].id).toBe(id2);
  });

  test('list returns empty when no worktrees exist', () => {
    const all = listWorktrees(db);
    expect(all).toEqual([]);
  });
});

// ── forge worktree status <id> ──────────────────────────────────

describe('forge worktree status <id>', () => {
  test('shows detailed info including full spec content reference', () => {
    const id = insertTestWorktree({
      spec_path: 'specs/auth-login.md',
      branch: 'forge/auth-login',
      worktree_path: '/tmp/project-auth-login',
      work_group_id: 'wg-detail',
      linear_issue_id: 'ENG-42',
      session_id: 'sess-xyz',
    });

    const wt = getWorktree(db, id);
    expect(wt).not.toBeNull();
    expect(wt!.spec_path).toBe('specs/auth-login.md');
    expect(wt!.branch).toBe('forge/auth-login');
    expect(wt!.worktree_path).toBe('/tmp/project-auth-login');
    expect(wt!.work_group_id).toBe('wg-detail');
    expect(wt!.linear_issue_id).toBe('ENG-42');
    expect(wt!.session_id).toBe('sess-xyz');
    expect(wt!.created_at).toBeTruthy();
    expect(wt!.updated_at).toBeTruthy();
  });

  test('shows run history via spec_entries and spec_runs', () => {
    const specPath = 'specs/history-test.md';
    const entryId = crypto.randomUUID();

    insertSpecEntry(db, { id: entryId, spec: specPath });
    insertSpecRun(db, {
      id: crypto.randomUUID(),
      spec_entry_id: entryId,
      run_id: 'batch-1',
      timestamp: '2026-01-01T00:00:00Z',
      status: 'passed',
      cost_usd: 2.5,
      duration_seconds: 120,
      num_turns: 15,
    });
    insertSpecRun(db, {
      id: crypto.randomUUID(),
      spec_entry_id: entryId,
      run_id: 'batch-2',
      timestamp: '2026-01-02T00:00:00Z',
      status: 'failed',
      cost_usd: 1.0,
      duration_seconds: 45,
      num_turns: 8,
    });

    insertTestWorktree({ spec_path: specPath });

    // Verify the lookup chain works
    const entry = getSpecEntryByPath(db, specPath);
    expect(entry).not.toBeNull();
    expect(entry!.id).toBe(entryId);

    const runs = getSpecRunsByEntry(db, entryId);
    expect(runs).toHaveLength(2);
    // Ordered by timestamp DESC: most recent first
    expect(runs[0].status).toBe('failed');
    expect(runs[0].cost_usd).toBe(1.0);
    expect(runs[1].cost_usd).toBe(2.5);
    expect(runs[1].duration_seconds).toBe(120);
  });

  test('shows error when worktree not found', () => {
    const wt = getWorktree(db, 'nonexistent-id');
    expect(wt).toBeNull();
  });
});

// ── forge worktree mark-ready <id> ──────────────────────────────

describe('forge worktree mark-ready <id>', () => {
  test('validates transition: complete -> ready succeeds', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');

    const { previousStatus } = transitionWorktreeStatus(db, id, 'ready');
    expect(previousStatus).toBe('complete');
    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('validates transition: proofed -> ready succeeds', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'audited');
    transitionWorktreeStatus(db, id, 'proofing');
    transitionWorktreeStatus(db, id, 'proofed');

    const { previousStatus } = transitionWorktreeStatus(db, id, 'ready');
    expect(previousStatus).toBe('proofed');
  });

  test('validates transition: merge_failed -> ready succeeds (retry)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');
    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merge_failed');

    const { previousStatus } = transitionWorktreeStatus(db, id, 'ready');
    expect(previousStatus).toBe('merge_failed');
    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('rejects invalid transition: created -> ready', () => {
    const id = insertTestWorktree({ status: 'created' });
    expect(() => transitionWorktreeStatus(db, id, 'ready')).toThrow('Invalid worktree transition');
  });

  test('rejects invalid transition: running -> ready', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    expect(() => transitionWorktreeStatus(db, id, 'ready')).toThrow('Invalid worktree transition');
  });

  test('rejects transition on nonexistent worktree', () => {
    expect(() => transitionWorktreeStatus(db, 'nonexistent', 'ready')).toThrow('Worktree not found');
  });

  test('mark-ready is the primary user-driven lifecycle transition', () => {
    // ready is the entry point to merging
    const transitions = getValidTransitions('ready');
    expect(transitions).toContain('merging');
  });
});

// ── Output format consistency ───────────────────────────────────

describe('output format consistency', () => {
  test('status icon uses ASCII characters, not emojis', () => {
    // The CLI uses: + for success, > for running, x for fail, ~ for paused, - for created
    const asciiIcons = ['+', '>', 'x', '~', '-'];
    for (const icon of asciiIcons) {
      expect(icon.length).toBe(1);
      expect(icon.codePointAt(0)!).toBeLessThan(128); // ASCII range
    }
  });

  test('age formatting produces human-readable strings', () => {
    // formatAge produces: "Xs ago", "Xm ago", "Xh ago", "Xd ago"
    const now = Date.now();

    const formats = [
      { offset: 30 * 1000, pattern: /\d+s ago/ },       // seconds
      { offset: 5 * 60 * 1000, pattern: /\d+m ago/ },   // minutes
      { offset: 3 * 60 * 60 * 1000, pattern: /\d+h ago/ }, // hours
      { offset: 2 * 24 * 60 * 60 * 1000, pattern: /\d+d ago/ }, // days
    ];

    for (const { offset, pattern } of formats) {
      const timestamp = new Date(now - offset).toISOString();
      const ms = Date.now() - new Date(timestamp).getTime();
      const seconds = Math.floor(ms / 1000);

      let formatted: string;
      if (seconds < 60) formatted = `${seconds}s ago`;
      else if (seconds < 3600) formatted = `${Math.floor(seconds / 60)}m ago`;
      else if (seconds < 86400) formatted = `${Math.floor(seconds / 3600)}h ago`;
      else formatted = `${Math.floor(seconds / 86400)}d ago`;

      expect(formatted).toMatch(pattern);
    }
  });
});
