// Generated by forge proof from config.md
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import {
  getConfig,
  clearConfigCache,
  CONFIG_DEFAULTS,
  formatConfig,
} from './config.js';
import type { ForgeLocalConfig } from './config.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-config-test-'));
  clearConfigCache();
  // Clear env vars that may affect tests
  delete process.env.FORGE_API_TOKEN;
  delete process.env.FORGE_API_PORT;
  delete process.env.FORGE_DB_PROVIDER;
  delete process.env.FORGE_SETUP_TIMEOUT;
});

afterEach(async () => {
  clearConfigCache();
  delete process.env.FORGE_API_TOKEN;
  delete process.env.FORGE_API_PORT;
  delete process.env.FORGE_DB_PROVIDER;
  delete process.env.FORGE_SETUP_TIMEOUT;
  await fs.rm(tmpDir, { recursive: true, force: true });
});

// ── CONFIG_DEFAULTS ───────────────────────────────────────────

describe('CONFIG_DEFAULTS', () => {
  test('has expected default values', () => {
    expect(CONFIG_DEFAULTS.setup).toEqual([]);
    expect(CONFIG_DEFAULTS.teardown).toEqual([]);
    expect(CONFIG_DEFAULTS.setupTimeout).toBe(300000);
    expect(CONFIG_DEFAULTS.dbProvider).toBe('sqlite');
    expect(CONFIG_DEFAULTS.apiPort).toBe(4926);
    expect(CONFIG_DEFAULTS.apiToken).toBeNull();
  });
});

// ── getConfig: auto-create ────────────────────────────────────

describe('getConfig auto-creation', () => {
  test('creates .forge/config.json with defaults when file does not exist', () => {
    getConfig(tmpDir);
    const configPath = path.join(tmpDir, '.forge', 'config.json');
    const exists = require('fs').existsSync(configPath);
    expect(exists).toBe(true);
  });

  test('config.json created contains valid JSON with defaults', () => {
    getConfig(tmpDir);
    const configPath = path.join(tmpDir, '.forge', 'config.json');
    const content = require('fs').readFileSync(configPath, 'utf-8');
    const parsed = JSON.parse(content) as ForgeLocalConfig;
    expect(parsed.setup).toEqual([]);
    expect(parsed.teardown).toEqual([]);
    expect(parsed.setupTimeout).toBe(300000);
    expect(parsed.dbProvider).toBe('sqlite');
    expect(parsed.apiPort).toBe(4926);
    expect(parsed.apiToken).toBeNull();
  });

  test('returns defaults when file does not exist', () => {
    const config = getConfig(tmpDir);
    expect(config.setup).toEqual([]);
    expect(config.teardown).toEqual([]);
    expect(config.setupTimeout).toBe(300000);
    expect(config.dbProvider).toBe('sqlite');
    expect(config.apiPort).toBe(4926);
    expect(config.apiToken).toBeNull();
  });

  test('creates .forge directory if it does not exist', () => {
    const freshDir = path.join(tmpDir, 'fresh');
    require('fs').mkdirSync(freshDir);
    getConfig(freshDir);
    const forgeDir = path.join(freshDir, '.forge');
    expect(require('fs').existsSync(forgeDir)).toBe(true);
  });
});

// ── getConfig: reading from file ─────────────────────────────

describe('getConfig file reading', () => {
  async function writeConfig(obj: Partial<ForgeLocalConfig> & Record<string, unknown>): Promise<void> {
    await fs.mkdir(path.join(tmpDir, '.forge'), { recursive: true });
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'config.json'),
      JSON.stringify(obj, null, 2),
    );
  }

  test('reads setup and teardown arrays from file', async () => {
    await writeConfig({
      setup: ['echo "before"', 'npm install'],
      teardown: ['echo "after"'],
    });
    const config = getConfig(tmpDir);
    expect(config.setup).toEqual(['echo "before"', 'npm install']);
    expect(config.teardown).toEqual(['echo "after"']);
  });

  test('reads dbProvider from file', async () => {
    await writeConfig({ dbProvider: 'turso' });
    const config = getConfig(tmpDir);
    expect(config.dbProvider).toBe('turso');
  });

  test('reads apiPort from file', async () => {
    await writeConfig({ apiPort: 8080 });
    const config = getConfig(tmpDir);
    expect(config.apiPort).toBe(8080);
  });

  test('reads apiToken from file', async () => {
    await writeConfig({ apiToken: 'my-secret-token' });
    const config = getConfig(tmpDir);
    expect(config.apiToken).toBe('my-secret-token');
  });

  test('reads setupTimeout from file', async () => {
    await writeConfig({ setupTimeout: 60000 });
    const config = getConfig(tmpDir);
    expect(config.setupTimeout).toBe(60000);
  });

  test('preserves unknown keys (forward-compatible via passthrough)', async () => {
    await writeConfig({ futureField: 'some value', setup: ['cmd'] } as Record<string, unknown>);
    // Should not throw, and known fields should be correctly read
    const config = getConfig(tmpDir);
    expect(config.setup).toEqual(['cmd']);
  });
});

// ── getConfig: invalid values fall back to defaults ──────────

describe('getConfig invalid value fallback', () => {
  async function writeConfig(obj: Record<string, unknown>): Promise<void> {
    await fs.mkdir(path.join(tmpDir, '.forge'), { recursive: true });
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'config.json'),
      JSON.stringify(obj, null, 2),
    );
  }

  test('falls back to default for invalid dbProvider', async () => {
    await writeConfig({ dbProvider: 'mysql' });
    const config = getConfig(tmpDir);
    expect(config.dbProvider).toBe('sqlite'); // default
  });

  test('falls back to default for invalid apiPort (negative)', async () => {
    await writeConfig({ apiPort: -1 });
    const config = getConfig(tmpDir);
    expect(config.apiPort).toBe(4926); // default
  });

  test('falls back to default for invalid setupTimeout (negative)', async () => {
    await writeConfig({ setupTimeout: -5000 });
    const config = getConfig(tmpDir);
    expect(config.setupTimeout).toBe(300000); // default
  });

  test('falls back to default for invalid setup (not array)', async () => {
    await writeConfig({ setup: 'not-an-array' });
    const config = getConfig(tmpDir);
    expect(config.setup).toEqual([]); // default
  });

  test('warns to stderr for invalid values', async () => {
    await writeConfig({ dbProvider: 'mysql' });
    const warnMessages: string[] = [];
    const origWarn = console.warn;
    console.warn = (...args: unknown[]) => warnMessages.push(args.join(' '));
    try {
      getConfig(tmpDir);
    } finally {
      console.warn = origWarn;
    }
    expect(warnMessages.some(m => m.includes('dbProvider'))).toBe(true);
  });
});

// ── getConfig: caching ────────────────────────────────────────

describe('getConfig caching', () => {
  test('returns same object reference on repeated calls', () => {
    const config1 = getConfig(tmpDir);
    const config2 = getConfig(tmpDir);
    expect(config1).toBe(config2);
  });

  test('clearConfigCache causes re-read on next call', async () => {
    getConfig(tmpDir); // populates cache, creates config.json
    // Modify the config file
    const configPath = path.join(tmpDir, '.forge', 'config.json');
    await fs.writeFile(configPath, JSON.stringify({ apiPort: 9999 }, null, 2));
    // Without clearing cache, old value is returned
    const cached = getConfig(tmpDir);
    expect(cached.apiPort).toBe(4926); // still cached default
    // After clearing, new value is picked up
    clearConfigCache();
    const fresh = getConfig(tmpDir);
    expect(fresh.apiPort).toBe(9999);
  });
});

// ── getConfig: environment variable overrides ────────────────

describe('getConfig environment variable overrides', () => {
  test('FORGE_API_TOKEN overrides apiToken from file', async () => {
    await fs.mkdir(path.join(tmpDir, '.forge'), { recursive: true });
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'config.json'),
      JSON.stringify({ apiToken: 'file-token' }, null, 2),
    );
    process.env.FORGE_API_TOKEN = 'env-token';
    const config = getConfig(tmpDir);
    expect(config.apiToken).toBe('env-token');
  });

  test('empty FORGE_API_TOKEN sets apiToken to null', () => {
    process.env.FORGE_API_TOKEN = '';
    const config = getConfig(tmpDir);
    expect(config.apiToken).toBeNull();
  });

  test('FORGE_API_PORT overrides apiPort from file', async () => {
    await fs.mkdir(path.join(tmpDir, '.forge'), { recursive: true });
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'config.json'),
      JSON.stringify({ apiPort: 5000 }, null, 2),
    );
    process.env.FORGE_API_PORT = '7777';
    const config = getConfig(tmpDir);
    expect(config.apiPort).toBe(7777);
  });

  test('invalid FORGE_API_PORT (non-number) is ignored', () => {
    process.env.FORGE_API_PORT = 'not-a-port';
    const config = getConfig(tmpDir);
    expect(config.apiPort).toBe(4926); // falls back to default
  });

  test('FORGE_DB_PROVIDER overrides dbProvider', () => {
    process.env.FORGE_DB_PROVIDER = 'turso';
    const config = getConfig(tmpDir);
    expect(config.dbProvider).toBe('turso');
  });

  test('invalid FORGE_DB_PROVIDER is ignored', () => {
    process.env.FORGE_DB_PROVIDER = 'mysql';
    const config = getConfig(tmpDir);
    expect(config.dbProvider).toBe('sqlite'); // falls back to default
  });

  test('FORGE_SETUP_TIMEOUT overrides setupTimeout', () => {
    process.env.FORGE_SETUP_TIMEOUT = '45000';
    const config = getConfig(tmpDir);
    expect(config.setupTimeout).toBe(45000);
  });

  test('env vars take precedence over file values', async () => {
    await fs.mkdir(path.join(tmpDir, '.forge'), { recursive: true });
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'config.json'),
      JSON.stringify({ apiToken: 'file-token', apiPort: 5000, dbProvider: 'turso' }, null, 2),
    );
    process.env.FORGE_API_TOKEN = 'env-wins';
    process.env.FORGE_API_PORT = '9000';
    const config = getConfig(tmpDir);
    expect(config.apiToken).toBe('env-wins');
    expect(config.apiPort).toBe(9000);
    expect(config.dbProvider).toBe('turso'); // no env override, file wins
  });
});

// ── formatConfig ─────────────────────────────────────────────

describe('formatConfig', () => {
  test('returns a non-empty string', () => {
    const output = formatConfig(tmpDir);
    expect(typeof output).toBe('string');
    expect(output.length).toBeGreaterThan(0);
  });

  test('includes all field names in output', () => {
    const output = formatConfig(tmpDir);
    expect(output).toContain('setup');
    expect(output).toContain('teardown');
    expect(output).toContain('setupTimeout');
    expect(output).toContain('dbProvider');
    expect(output).toContain('apiPort');
    expect(output).toContain('apiToken');
  });

  test('shows (default) annotation for default values', () => {
    const output = formatConfig(tmpDir);
    expect(output).toContain('default');
  });

  test('shows env var annotation when env override is active', () => {
    process.env.FORGE_API_TOKEN = 'test-token';
    clearConfigCache();
    const output = formatConfig(tmpDir);
    expect(output).toContain('FORGE_API_TOKEN');
  });
});
