// Generated by forge proof from consolidate-command.md, consolidate-concurrency-guard.md, consolidate-conflict-resolution.md
import { describe, test, expect, beforeEach, beforeAll, afterAll } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  listWorktrees,
  getWorktreesByWorkGroup,
  transitionWorktreeStatus,
  acquireConsolidationLock,
  releaseConsolidationLock,
  releaseAllConsolidationLocks,
} from './db.js';
import type { Database } from 'bun:sqlite';
import type { WorktreeStatus } from './db.js';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';

let db: Database;

beforeAll(() => { setupHermeticGit(); });
afterAll(() => { teardownHermeticGit(); });

beforeEach(() => {
  db = getTestDb();
});

function insertReadyWorktree(wgId: string, specPath: string, branch: string): string {
  const id = `wt-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
  insertWorktree(db, {
    id,
    work_group_id: wgId,
    spec_path: specPath,
    branch,
    worktree_path: `/tmp/wt-${branch}`,
    status: 'created',
  });
  // Transition to ready
  transitionWorktreeStatus(db, id, 'running');
  transitionWorktreeStatus(db, id, 'complete');
  transitionWorktreeStatus(db, id, 'ready');
  return id;
}

// ── Consolidation Concurrency Guard ──────────────────────────

describe('acquireConsolidationLock', () => {
  test('acquires lock when no existing lock', () => {
    const result = acquireConsolidationLock(db, 'wg-test-1');
    expect(result.acquired).toBe(true);
  });

  test('rejects when active lock exists for same work group', () => {
    // First acquisition succeeds
    acquireConsolidationLock(db, 'wg-test-2');

    // Second acquisition with same work group fails (our own PID is alive)
    const result = acquireConsolidationLock(db, 'wg-test-2');
    expect(result.acquired).toBe(false);
    if (!result.acquired) {
      expect(result.activePid).toBe(process.pid);
    }
  });

  test('allows lock for different work group', () => {
    acquireConsolidationLock(db, 'wg-A');
    const result = acquireConsolidationLock(db, 'wg-B');
    expect(result.acquired).toBe(true);
  });

  test('clears stale lock (dead PID) and acquires', () => {
    // Insert a lock with a definitely-dead PID
    db.run(
      "INSERT INTO consolidations (work_group_id, pid, started_at) VALUES (?, ?, datetime('now'))",
      ['wg-stale', 99999999],
    );

    const result = acquireConsolidationLock(db, 'wg-stale');
    expect(result.acquired).toBe(true);
  });
});

describe('releaseConsolidationLock', () => {
  test('releases lock for current process', () => {
    acquireConsolidationLock(db, 'wg-release');

    releaseConsolidationLock(db, 'wg-release');

    // Should be able to acquire again
    const result = acquireConsolidationLock(db, 'wg-release');
    expect(result.acquired).toBe(true);
  });

  test('does not release lock held by different PID', () => {
    // Insert a lock with a different PID (our process PID + 1 would be different)
    db.run(
      "INSERT INTO consolidations (work_group_id, pid, started_at) VALUES (?, ?, datetime('now'))",
      ['wg-other-pid', process.pid + 1],
    );

    // Try to release -- should not delete because PID doesn't match
    releaseConsolidationLock(db, 'wg-other-pid');

    // Row should still exist
    const row = db.query('SELECT * FROM consolidations WHERE work_group_id = ?').get('wg-other-pid');
    expect(row).not.toBeNull();
  });

  test('no-op when no lock exists', () => {
    // Should not throw
    releaseConsolidationLock(db, 'wg-nonexistent');
  });
});

describe('releaseAllConsolidationLocks', () => {
  test('releases all locks held by current process', () => {
    acquireConsolidationLock(db, 'wg-all-1');
    acquireConsolidationLock(db, 'wg-all-2');

    releaseAllConsolidationLocks(db);

    // Both should be re-acquirable
    expect(acquireConsolidationLock(db, 'wg-all-1').acquired).toBe(true);
    expect(acquireConsolidationLock(db, 'wg-all-2').acquired).toBe(true);
  });
});

// ── Consolidation Worktree Discovery ─────────────────────────

describe('consolidation worktree discovery', () => {
  test('discovers ready worktrees by work_group_id', () => {
    const wgId = 'wg-discover';
    insertReadyWorktree(wgId, 'auth.md', 'forge/auth');
    insertReadyWorktree(wgId, 'api.md', 'forge/api');

    // Also insert a non-ready worktree
    const failedId = `wt-failed-${Date.now()}`;
    insertWorktree(db, {
      id: failedId,
      work_group_id: wgId,
      spec_path: 'broken.md',
      branch: 'forge/broken',
      worktree_path: '/tmp/wt-broken',
      status: 'created',
    });

    const all = getWorktreesByWorkGroup(db, wgId);
    expect(all).toHaveLength(3);

    const ready = all.filter(w => w.status === 'ready');
    expect(ready).toHaveLength(2);
  });

  test('worktree status transitions: ready -> merging -> merged', () => {
    const wgId = 'wg-transition';
    const wtId = insertReadyWorktree(wgId, 'feature.md', 'forge/feature');

    transitionWorktreeStatus(db, wtId, 'merging');
    expect(getWorktree(db, wtId)!.status).toBe('merging');

    transitionWorktreeStatus(db, wtId, 'merged');
    expect(getWorktree(db, wtId)!.status).toBe('merged');
  });

  test('worktree status transitions: merging -> paused (conflict)', () => {
    const wgId = 'wg-conflict';
    const wtId = insertReadyWorktree(wgId, 'conflict.md', 'forge/conflict');

    transitionWorktreeStatus(db, wtId, 'merging');
    transitionWorktreeStatus(db, wtId, 'paused', 'Unresolved conflicts: src/auth.ts');

    const wt = getWorktree(db, wtId)!;
    expect(wt.status).toBe('paused');
    expect(wt.error).toBe('Unresolved conflicts: src/auth.ts');
  });

  test('worktree status transitions: merging -> merge_failed (type errors)', () => {
    const wgId = 'wg-type-error';
    const wtId = insertReadyWorktree(wgId, 'type-err.md', 'forge/type-err');

    transitionWorktreeStatus(db, wtId, 'merging');
    transitionWorktreeStatus(db, wtId, 'merge_failed', 'Type errors after 2 fix attempts');

    expect(getWorktree(db, wtId)!.status).toBe('merge_failed');
  });
});

// ── Consolidation Result Tracking ────────────────────────────

describe('consolidation result tracking', () => {
  test('tracks merged, paused, and failed worktrees', () => {
    const wgId = 'wg-results';
    const mergedId = insertReadyWorktree(wgId, 'merged.md', 'forge/merged');
    const pausedId = insertReadyWorktree(wgId, 'paused.md', 'forge/paused');
    const failedId = insertReadyWorktree(wgId, 'failed.md', 'forge/failed');

    // Simulate consolidation outcomes
    transitionWorktreeStatus(db, mergedId, 'merging');
    transitionWorktreeStatus(db, mergedId, 'merged');

    transitionWorktreeStatus(db, pausedId, 'merging');
    transitionWorktreeStatus(db, pausedId, 'paused', 'Conflict in auth.ts');

    transitionWorktreeStatus(db, failedId, 'merging');
    transitionWorktreeStatus(db, failedId, 'merge_failed', 'Type errors');

    const all = getWorktreesByWorkGroup(db, wgId);
    const merged = all.filter(w => w.status === 'merged');
    const paused = all.filter(w => w.status === 'paused');
    const failed = all.filter(w => w.status === 'merge_failed');

    expect(merged).toHaveLength(1);
    expect(paused).toHaveLength(1);
    expect(failed).toHaveLength(1);
  });
});
