// Generated by forge proof from consolidate-concurrency-guard.md
import { describe, test, expect, beforeEach, beforeAll, afterAll } from 'bun:test';
import {
  getTestDb,
  acquireConsolidationLock,
  releaseConsolidationLock,
  releaseAllConsolidationLocks,
} from './db.js';
import type { Database } from 'bun:sqlite';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';

let db: Database;

beforeAll(() => { setupHermeticGit(); });
afterAll(() => { teardownHermeticGit(); });

beforeEach(() => {
  db = getTestDb();
});

// ── Concurrency guard: acquire ──────────────────────────────

describe('consolidation concurrency guard: acquire', () => {
  test('acquires lock when no prior lock exists', () => {
    const result = acquireConsolidationLock(db, 'wg-fresh');
    expect(result.acquired).toBe(true);
  });

  test('records current PID in consolidations table', () => {
    acquireConsolidationLock(db, 'wg-pid-check');

    const row = db.query('SELECT * FROM consolidations WHERE work_group_id = ?').get('wg-pid-check') as { pid: number } | null;
    expect(row).not.toBeNull();
    expect(row!.pid).toBe(process.pid);
  });

  test('records started_at timestamp', () => {
    acquireConsolidationLock(db, 'wg-time-check');

    const row = db.query('SELECT * FROM consolidations WHERE work_group_id = ?').get('wg-time-check') as { started_at: string } | null;
    expect(row).not.toBeNull();
    expect(row!.started_at).toBeTruthy();
    // Timestamp should be recent (within 5s)
    const ts = new Date(row!.started_at).getTime();
    expect(Math.abs(Date.now() - ts)).toBeLessThan(5000);
  });

  test('rejects second acquire on same work group when PID is alive', () => {
    acquireConsolidationLock(db, 'wg-double');

    const second = acquireConsolidationLock(db, 'wg-double');
    expect(second.acquired).toBe(false);
    if (!second.acquired) {
      expect(second.activePid).toBe(process.pid);
    }
  });

  test('allows acquire on different work group', () => {
    acquireConsolidationLock(db, 'wg-alpha');
    const result = acquireConsolidationLock(db, 'wg-beta');
    expect(result.acquired).toBe(true);
  });

  test('clears stale lock (dead PID) and acquires', () => {
    // Insert a row with a dead PID (999999 is almost certainly not running)
    const now = new Date().toISOString();
    db.run(
      'INSERT INTO consolidations (work_group_id, pid, started_at) VALUES (?, ?, ?)',
      ['wg-stale-pid', 999999, now],
    );

    const result = acquireConsolidationLock(db, 'wg-stale-pid');
    expect(result.acquired).toBe(true);

    // Verify stale record was replaced
    const row = db.query('SELECT pid FROM consolidations WHERE work_group_id = ?').get('wg-stale-pid') as { pid: number };
    expect(row.pid).toBe(process.pid);
  });

  test('rejects when PID is alive even if old started_at', () => {
    // Insert a lock with our own PID but an old timestamp
    db.run(
      'INSERT INTO consolidations (work_group_id, pid, started_at) VALUES (?, ?, ?)',
      ['wg-old-but-alive', process.pid, '2020-01-01T00:00:00.000Z'],
    );

    const result = acquireConsolidationLock(db, 'wg-old-but-alive');
    expect(result.acquired).toBe(false);
  });
});

// ── Concurrency guard: release ──────────────────────────────

describe('consolidation concurrency guard: release', () => {
  test('releases lock held by current process', () => {
    acquireConsolidationLock(db, 'wg-release-ok');
    releaseConsolidationLock(db, 'wg-release-ok');

    // Should be re-acquirable
    const result = acquireConsolidationLock(db, 'wg-release-ok');
    expect(result.acquired).toBe(true);
  });

  test('does not release lock held by different PID', () => {
    // Manually insert a lock with a different PID
    db.run(
      'INSERT INTO consolidations (work_group_id, pid, started_at) VALUES (?, ?, ?)',
      ['wg-other-owner', process.pid + 12345, new Date().toISOString()],
    );

    releaseConsolidationLock(db, 'wg-other-owner');

    // Row should still exist because PID doesn't match
    const row = db.query('SELECT * FROM consolidations WHERE work_group_id = ?').get('wg-other-owner');
    expect(row).not.toBeNull();
  });

  test('no-op when no lock exists for work group', () => {
    // Should not throw
    expect(() => releaseConsolidationLock(db, 'wg-never-locked')).not.toThrow();
  });

  test('PID record cleared on completion', () => {
    acquireConsolidationLock(db, 'wg-complete');
    releaseConsolidationLock(db, 'wg-complete');

    const row = db.query('SELECT * FROM consolidations WHERE work_group_id = ?').get('wg-complete');
    expect(row).toBeNull();
  });
});

// ── Concurrency guard: releaseAll ───────────────────────────

describe('consolidation concurrency guard: releaseAll (Ctrl-C cleanup)', () => {
  test('releases all locks held by current process', () => {
    acquireConsolidationLock(db, 'wg-batch-1');
    acquireConsolidationLock(db, 'wg-batch-2');

    releaseAllConsolidationLocks(db);

    expect(acquireConsolidationLock(db, 'wg-batch-1').acquired).toBe(true);
    expect(acquireConsolidationLock(db, 'wg-batch-2').acquired).toBe(true);
  });

  test('does not release locks held by other processes', () => {
    // Lock by our process
    acquireConsolidationLock(db, 'wg-ours');

    // Lock by another process
    db.run(
      'INSERT INTO consolidations (work_group_id, pid, started_at) VALUES (?, ?, ?)',
      ['wg-theirs', process.pid + 99999, new Date().toISOString()],
    );

    releaseAllConsolidationLocks(db);

    // Ours is released
    const oursRow = db.query('SELECT * FROM consolidations WHERE work_group_id = ?').get('wg-ours');
    expect(oursRow).toBeNull();

    // Theirs remains
    const theirsRow = db.query('SELECT * FROM consolidations WHERE work_group_id = ?').get('wg-theirs');
    expect(theirsRow).not.toBeNull();
  });
});

// ── Per-work-group guard (not global) ───────────────────────

describe('consolidation concurrency guard: per-work-group isolation', () => {
  test('consolidating group A does not block group B', () => {
    const resultA = acquireConsolidationLock(db, 'wg-A');
    expect(resultA.acquired).toBe(true);

    const resultB = acquireConsolidationLock(db, 'wg-B');
    expect(resultB.acquired).toBe(true);
  });

  test('releasing group A does not affect group B lock', () => {
    acquireConsolidationLock(db, 'wg-X');
    acquireConsolidationLock(db, 'wg-Y');

    releaseConsolidationLock(db, 'wg-X');

    // Y is still locked (by our PID)
    const resultY = acquireConsolidationLock(db, 'wg-Y');
    expect(resultY.acquired).toBe(false);
  });
});

// ── Error message includes PID and work group ───────────────

describe('consolidation concurrency guard: error messages', () => {
  test('rejected acquire returns activePid for the error message', () => {
    acquireConsolidationLock(db, 'wg-err-msg');
    const result = acquireConsolidationLock(db, 'wg-err-msg');

    expect(result.acquired).toBe(false);
    if (!result.acquired) {
      expect(typeof result.activePid).toBe('number');
      expect(result.activePid).toBe(process.pid);

      // Simulate error message construction from consolidate.ts
      const msg = `Consolidation already in progress for work group wg-err-msg (PID ${result.activePid}).`;
      expect(msg).toContain('wg-err-msg');
      expect(msg).toContain(String(process.pid));
    }
  });
});
