// Generated by forge proof from consolidate-command.md
import { describe, test, expect, beforeAll, afterAll, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  transitionWorktreeStatus,
  listWorktrees,
  getWorktreesByWorkGroup,
} from './db.js';
import type { WorktreeRow } from './db.js';
import type { Database } from 'bun:sqlite';
import { topoSort } from './deps.js';
import type { SpecDep } from './deps.js';
import { detectVerification } from './verify.js';

const execAsync = promisify(exec);

// ── Hermetic Git ─────────────────────────────────────────────

beforeAll(() => { setupHermeticGit(); });
afterAll(() => { teardownHermeticGit(); });

// ── Helpers ──────────────────────────────────────────────────

let db: Database;

function makeId(): string {
  return `wt-${Date.now()}-${Math.random().toString(16).substring(2, 8)}`;
}

function makeWorkGroupId(): string {
  return `wg-${Date.now()}-${Math.random().toString(16).substring(2, 8)}`;
}

function insertReadyWorktree(wgId: string, overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeId();
  insertWorktree(db, {
    id,
    work_group_id: wgId,
    spec_path: overrides.spec_path ?? `specs/${id}.md`,
    branch: overrides.branch ?? `forge/${id}`,
    worktree_path: overrides.worktree_path ?? `/tmp/forge-${id}`,
    status: 'created',
    ...overrides,
  });
  transitionWorktreeStatus(db, id, 'running');
  transitionWorktreeStatus(db, id, 'complete');
  transitionWorktreeStatus(db, id, 'ready');
  return id;
}

// ── Work group discovery ────────────────────────────────────

describe('consolidate: work group auto-detection', () => {
  beforeEach(() => { db = getTestDb(); });

  test('discovers ready worktrees via work_group_id', () => {
    const wgId = makeWorkGroupId();
    const id1 = insertReadyWorktree(wgId, { spec_path: 'specs/auth.md', branch: 'forge/auth' });
    const id2 = insertReadyWorktree(wgId, { spec_path: 'specs/api.md', branch: 'forge/api' });

    const results = getWorktreesByWorkGroup(db, wgId);
    expect(results.length).toBe(2);
    expect(results.map(r => r.id)).toEqual(expect.arrayContaining([id1, id2]));
    expect(results.every(r => r.status === 'ready')).toBe(true);
  });

  test('filters by status to find only ready worktrees in a group', () => {
    const wgId = makeWorkGroupId();
    insertReadyWorktree(wgId, { spec_path: 'specs/done.md', branch: 'forge/done' });

    const createdId = makeId();
    insertWorktree(db, {
      id: createdId,
      work_group_id: wgId,
      spec_path: 'specs/wip.md',
      branch: 'forge/wip',
      worktree_path: `/tmp/forge-${createdId}`,
      status: 'created',
    });

    const all = getWorktreesByWorkGroup(db, wgId);
    const ready = all.filter(w => w.status === 'ready');
    expect(all.length).toBe(2);
    expect(ready.length).toBe(1);
  });

  test('auto-detect selects most recent work group with ready worktrees', () => {
    // Simulate autoDetectWorkGroup logic from consolidate.ts
    // Use explicit timestamps to avoid same-millisecond races
    const olderWg = makeWorkGroupId();
    const olderId = makeId();
    insertWorktree(db, {
      id: olderId,
      work_group_id: olderWg,
      spec_path: 'specs/old.md',
      branch: 'forge/old',
      worktree_path: `/tmp/forge-${olderId}`,
      status: 'created',
    });
    transitionWorktreeStatus(db, olderId, 'running');
    transitionWorktreeStatus(db, olderId, 'complete');
    transitionWorktreeStatus(db, olderId, 'ready');
    // Manually backdate the created_at
    db.run('UPDATE worktrees SET created_at = ? WHERE id = ?', ['2026-01-01T00:00:00.000Z', olderId]);

    const newerWg = makeWorkGroupId();
    const newerId = makeId();
    insertWorktree(db, {
      id: newerId,
      work_group_id: newerWg,
      spec_path: 'specs/new.md',
      branch: 'forge/new',
      worktree_path: `/tmp/forge-${newerId}`,
      status: 'created',
    });
    transitionWorktreeStatus(db, newerId, 'running');
    transitionWorktreeStatus(db, newerId, 'complete');
    transitionWorktreeStatus(db, newerId, 'ready');
    // Newer group keeps the current timestamp (more recent)

    const readyWorktrees = listWorktrees(db, 'ready');
    const groups = new Map<string, WorktreeRow[]>();
    for (const wt of readyWorktrees) {
      if (!wt.work_group_id) continue;
      const existing = groups.get(wt.work_group_id) || [];
      existing.push(wt);
      groups.set(wt.work_group_id, existing);
    }

    let bestGroup: string | null = null;
    let bestTime = '';
    for (const [groupId, worktrees] of groups) {
      const newest = worktrees[0].created_at;
      if (newest > bestTime) {
        bestTime = newest;
        bestGroup = groupId;
      }
    }

    // The newer group should be selected (its created_at is later)
    expect(bestGroup).toBe(newerWg);
  });

  test('returns null when no ready worktrees exist', () => {
    const readyWorktrees = listWorktrees(db, 'ready');
    expect(readyWorktrees.length).toBe(0);
  });

  test('ignores worktrees without work_group_id', () => {
    const id = makeId();
    insertWorktree(db, {
      id,
      spec_path: 'specs/solo.md',
      branch: 'forge/solo',
      worktree_path: `/tmp/forge-${id}`,
      status: 'created',
    });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');

    const readyWorktrees = listWorktrees(db, 'ready');
    const withGroup = readyWorktrees.filter(w => w.work_group_id !== null);
    expect(withGroup.length).toBe(0);
  });
});

// ── Consolidation branch creation ───────────────────────────

describe('consolidate: branch naming and creation', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-branch-test-'));
    await execAsync('git init', { cwd: tmpDir });
    await execAsync('git config user.email "test@test.com"', { cwd: tmpDir });
    await execAsync('git config user.name "Test"', { cwd: tmpDir });
    await fs.writeFile(path.join(tmpDir, 'README.md'), '# Test');
    await execAsync('git add . && git commit -m "init"', { cwd: tmpDir });
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test('consolidation branch follows forge/consolidate/{work-group-id} pattern', () => {
    const wgId = 'wg-test-abc';
    const branch = `forge/consolidate/${wgId}`;
    expect(branch).toBe('forge/consolidate/wg-test-abc');
  });

  test('creates branch from main head', async () => {
    const wgId = 'wg-branch-test';
    const branch = `forge/consolidate/${wgId}`;

    const { stdout: mainSha } = await execAsync('git rev-parse main', { cwd: tmpDir });
    await execAsync(`git branch "${branch}" main`, { cwd: tmpDir });
    const { stdout: branchSha } = await execAsync(`git rev-parse "${branch}"`, { cwd: tmpDir });

    expect(branchSha.trim()).toBe(mainSha.trim());
  });

  test('deletes existing consolidation branch before recreating', async () => {
    const branch = 'forge/consolidate/wg-recreate';

    await execAsync(`git branch "${branch}" main`, { cwd: tmpDir });
    // Make a commit on main so the branch and main diverge
    await fs.writeFile(path.join(tmpDir, 'new.txt'), 'new');
    await execAsync('git add . && git commit -m "advance"', { cwd: tmpDir });

    // Delete and recreate
    await execAsync(`git branch -D "${branch}"`, { cwd: tmpDir });
    await execAsync(`git branch "${branch}" main`, { cwd: tmpDir });

    const { stdout: branchSha } = await execAsync(`git rev-parse "${branch}"`, { cwd: tmpDir });
    const { stdout: mainSha } = await execAsync('git rev-parse main', { cwd: tmpDir });
    expect(branchSha.trim()).toBe(mainSha.trim());
  });
});

// ── Merge order via topoSort ────────────────────────────────

describe('consolidate: dependency-ordered merging', () => {
  test('specs with no deps all land in level 0', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/a.md', depends: [] },
      { name: 'b.md', path: '/b.md', depends: [] },
      { name: 'c.md', path: '/c.md', depends: [] },
    ];
    const levels = topoSort(specs);
    expect(levels.length).toBe(1);
    expect(levels[0].specs.length).toBe(3);
  });

  test('linear dependency chain creates sequential levels', () => {
    const specs: SpecDep[] = [
      { name: 'base.md', path: '/base.md', depends: [] },
      { name: 'mid.md', path: '/mid.md', depends: ['base.md'] },
      { name: 'top.md', path: '/top.md', depends: ['mid.md'] },
    ];
    const levels = topoSort(specs);
    expect(levels.length).toBe(3);
    expect(levels[0].specs[0].name).toBe('base.md');
    expect(levels[1].specs[0].name).toBe('mid.md');
    expect(levels[2].specs[0].name).toBe('top.md');
  });

  test('diamond dependency creates correct levels', () => {
    const specs: SpecDep[] = [
      { name: 'root.md', path: '/root.md', depends: [] },
      { name: 'left.md', path: '/left.md', depends: ['root.md'] },
      { name: 'right.md', path: '/right.md', depends: ['root.md'] },
      { name: 'leaf.md', path: '/leaf.md', depends: ['left.md', 'right.md'] },
    ];
    const levels = topoSort(specs);
    expect(levels.length).toBe(3);
    expect(levels[0].specs[0].name).toBe('root.md');
    expect(levels[1].specs.map(s => s.name)).toEqual(expect.arrayContaining(['left.md', 'right.md']));
    expect(levels[2].specs[0].name).toBe('leaf.md');
  });

  test('circular dependency throws error', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/a.md', depends: ['b.md'] },
      { name: 'b.md', path: '/b.md', depends: ['a.md'] },
    ];
    expect(() => topoSort(specs)).toThrow(/Circular dependency/);
  });
});

// ── Worktree merge status transitions ───────────────────────

describe('consolidate: worktree status transitions', () => {
  beforeEach(() => { db = getTestDb(); });

  test('ready -> merging -> merged (clean merge)', () => {
    const wgId = makeWorkGroupId();
    const id = insertReadyWorktree(wgId);

    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merged');
    expect(getWorktree(db, id)!.status).toBe('merged');
  });

  test('ready -> merging -> merge_failed (type error rollback)', () => {
    const wgId = makeWorkGroupId();
    const id = insertReadyWorktree(wgId);

    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merge_failed', 'Type errors could not be fixed after 2 attempts');

    const wt = getWorktree(db, id)!;
    expect(wt.status).toBe('merge_failed');
    expect(wt.error).toContain('Type errors');
  });

  test('ready -> merging -> paused (unresolved conflict)', () => {
    const wgId = makeWorkGroupId();
    const id = insertReadyWorktree(wgId);

    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'paused', 'Unresolved merge conflicts: src/auth.ts, src/api.ts');

    const wt = getWorktree(db, id)!;
    expect(wt.status).toBe('paused');
    expect(wt.error).toContain('src/auth.ts');
  });

  test('merge_failed -> ready allows retry consolidation', () => {
    const wgId = makeWorkGroupId();
    const id = insertReadyWorktree(wgId);

    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merge_failed');
    transitionWorktreeStatus(db, id, 'ready');
    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('merged -> cleaned is terminal', () => {
    const wgId = makeWorkGroupId();
    const id = insertReadyWorktree(wgId);

    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merged');
    transitionWorktreeStatus(db, id, 'cleaned');
    expect(getWorktree(db, id)!.status).toBe('cleaned');
  });

  test('ready -> merged bypassing merging throws', () => {
    const wgId = makeWorkGroupId();
    const id = insertReadyWorktree(wgId);
    expect(() => transitionWorktreeStatus(db, id, 'merged')).toThrow('Invalid worktree transition');
  });
});

// ── Transitive skip propagation ─────────────────────────────

describe('consolidate: skip propagation for failed dependencies', () => {
  test('failed spec causes direct dependents to be skipped', () => {
    const failedSpecs = new Set<string>();
    const skipped: string[] = [];
    const specs: SpecDep[] = [
      { name: 'base.md', path: '/base.md', depends: [] },
      { name: 'child.md', path: '/child.md', depends: ['base.md'] },
    ];

    // base fails
    failedSpecs.add('base.md');

    // child depends on base -- should be skipped
    const blocker = specs[1].depends.find(d => failedSpecs.has(d));
    expect(blocker).toBe('base.md');
    skipped.push('child.md');
    failedSpecs.add('child.md');

    expect(skipped).toEqual(['child.md']);
  });

  test('transitive skip propagation across multiple levels', () => {
    const failedSpecs = new Set<string>();
    const skipped: string[] = [];

    // base -> mid -> leaf chain
    failedSpecs.add('base.md');

    // mid depends on base
    failedSpecs.add('mid.md');
    skipped.push('mid.md');

    // leaf depends on mid (transitively blocked by base)
    failedSpecs.add('leaf.md');
    skipped.push('leaf.md');

    expect(skipped).toEqual(['mid.md', 'leaf.md']);
  });

  test('independent specs are not affected by failures', () => {
    const failedSpecs = new Set<string>(['base.md']);

    const independent: SpecDep = { name: 'independent.md', path: '/ind.md', depends: [] };
    const dependent: SpecDep = { name: 'child.md', path: '/child.md', depends: ['base.md'] };

    const indBlocker = independent.depends.find(d => failedSpecs.has(d));
    const depBlocker = dependent.depends.find(d => failedSpecs.has(d));

    expect(indBlocker).toBeUndefined();
    expect(depBlocker).toBe('base.md');
  });

  test('skipped worktrees remain in ready status (not paused)', () => {
    db = getTestDb();
    const wgId = makeWorkGroupId();
    const id = insertReadyWorktree(wgId);

    // Skipped worktrees never get transitioned -- they stay ready
    expect(getWorktree(db, id)!.status).toBe('ready');
  });
});

// ── Git merge integration ───────────────────────────────────

describe('consolidate: git merge --no-ff pattern', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-merge-test-'));
    await execAsync('git init', { cwd: tmpDir });
    await execAsync('git config user.email "test@test.com"', { cwd: tmpDir });
    await execAsync('git config user.name "Test"', { cwd: tmpDir });
    await fs.writeFile(path.join(tmpDir, 'base.txt'), 'base');
    await execAsync('git add . && git commit -m "init"', { cwd: tmpDir });
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test('--no-ff creates a merge commit with two parents', async () => {
    await execAsync('git checkout -b feature', { cwd: tmpDir });
    await fs.writeFile(path.join(tmpDir, 'feat.txt'), 'feature');
    await execAsync('git add . && git commit -m "add feature"', { cwd: tmpDir });

    await execAsync('git checkout -b consolidation main', { cwd: tmpDir });
    await execAsync('git merge --no-ff feature -m "forge: consolidate feature"', { cwd: tmpDir });

    const { stdout } = await execAsync('git rev-list --parents -n 1 HEAD', { cwd: tmpDir });
    const hashes = stdout.trim().split(/\s+/);
    expect(hashes.length).toBe(3); // commit + 2 parents
  });

  test('sequential merges preserve all content', async () => {
    // Branch 1
    await execAsync('git checkout -b feat-1', { cwd: tmpDir });
    await fs.writeFile(path.join(tmpDir, 'f1.txt'), 'feat 1');
    await execAsync('git add . && git commit -m "feat 1"', { cwd: tmpDir });

    // Branch 2
    await execAsync('git checkout main', { cwd: tmpDir });
    await execAsync('git checkout -b feat-2', { cwd: tmpDir });
    await fs.writeFile(path.join(tmpDir, 'f2.txt'), 'feat 2');
    await execAsync('git add . && git commit -m "feat 2"', { cwd: tmpDir });

    // Consolidate
    await execAsync('git checkout -b consolidation main', { cwd: tmpDir });
    await execAsync('git merge --no-ff feat-1 -m "merge 1"', { cwd: tmpDir });
    await execAsync('git merge --no-ff feat-2 -m "merge 2"', { cwd: tmpDir });

    const f1 = await fs.readFile(path.join(tmpDir, 'f1.txt'), 'utf-8');
    const f2 = await fs.readFile(path.join(tmpDir, 'f2.txt'), 'utf-8');
    expect(f1).toBe('feat 1');
    expect(f2).toBe('feat 2');
  });
});

// ── Incremental type-check ──────────────────────────────────

describe('consolidate: incremental type-check detection', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-typecheck-test-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test('detects tsc --noEmit for TypeScript project with typescript dependency', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), JSON.stringify({
      scripts: { build: 'tsc' },
      devDependencies: { typescript: '^5.0.0' },
    }));
    await fs.writeFile(path.join(tmpDir, 'tsconfig.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const commands = await detectVerification(tmpDir);
    const hasTsc = commands.some(c => c.includes('tsc --noEmit'));
    expect(hasTsc).toBe(true);
  });

  test('no tsc command when typescript is not a dependency', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), JSON.stringify({
      scripts: { build: 'esbuild' },
    }));
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const commands = await detectVerification(tmpDir);
    const hasTsc = commands.some(c => c.includes('tsc --noEmit'));
    expect(hasTsc).toBe(false);
  });
});

// ── PR description building ─────────────────────────────────

describe('consolidate: PR description construction', () => {
  test('builds spec list from merged worktree IDs', () => {
    const allWorktrees: Partial<WorktreeRow>[] = [
      { id: 'wt-1', spec_path: 'specs/auth.md', branch: 'forge/auth' },
      { id: 'wt-2', spec_path: 'specs/api.md', branch: 'forge/api' },
    ];
    const merged = ['wt-1', 'wt-2'];

    const specList = merged.map(id => {
      const wt = allWorktrees.find(w => w.id === id);
      return wt ? `- ${path.basename(wt.spec_path!, '.md')} (\`${wt.branch}\`)` : `- ${id}`;
    }).join('\n');

    expect(specList).toContain('auth');
    expect(specList).toContain('api');
    expect(specList).toContain('forge/auth');
  });

  test('includes paused and failed sections when present', () => {
    const paused = ['wt-paused'];
    const failed = ['wt-failed'];
    const skipped = ['wt-skipped'];

    const pausedList = paused.length > 0 ? `\n\n## Paused\n${paused.join('\n')}` : '';
    const failedList = failed.length > 0 ? `\n\n## Failed\n${failed.join('\n')}` : '';
    const skippedList = skipped.length > 0 ? `\n\n## Skipped\n${skipped.join('\n')}` : '';

    expect(pausedList).toContain('Paused');
    expect(failedList).toContain('Failed');
    expect(skippedList).toContain('Skipped');
  });

  test('omits sections when arrays are empty', () => {
    const paused: string[] = [];
    const pausedList = paused.length > 0 ? `\n\n## Paused` : '';
    expect(pausedList).toBe('');
  });
});
