// Generated by forge proof from db-runs.md
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { Database } from 'bun:sqlite';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import {
  getTestDb,
  insertRun,
  queryAggregateStats,
  querySpecStats,
  queryModelStats,
  queryStatusRuns,
  backfillRuns,
  getDbWithBackfill,
  getDb,
  closeDb,
  getSchemaVersion,
} from './db.js';
import type { RunRow } from './db.js';

// ── Helpers ──────────────────────────────────────────────────

function makeRun(overrides: Partial<RunRow> = {}): RunRow {
  return {
    id: `run-${Math.random().toString(36).slice(2, 10)}`,
    specPath: 'specs/test.md',
    model: 'claude-opus-4-5',
    status: 'success',
    costUsd: 0.05,
    durationSeconds: 30,
    numTurns: 10,
    toolCalls: 5,
    batchId: 'batch-001',
    type: 'run',
    prompt: 'implement feature X',
    cwd: '/tmp/test',
    sessionId: `sess-${Math.random().toString(36).slice(2, 8)}`,
    error: null,
    createdAt: new Date().toISOString(),
    ...overrides,
  };
}

// ── runs table migration ──────────────────────────────────────

describe('runs table migration', () => {
  test('runs table exists after migration', () => {
    const db = getTestDb();
    const tables = db.query(
      "SELECT name FROM sqlite_master WHERE type='table' AND name='runs'",
    ).all() as Array<{ name: string }>;
    expect(tables.length).toBe(1);
    expect(tables[0].name).toBe('runs');
    db.close();
  });

  test('runs table has correct columns', () => {
    const db = getTestDb();
    const info = db.query('PRAGMA table_info(runs)').all() as Array<{ name: string }>;
    const columns = info.map(c => c.name);
    expect(columns).toContain('id');
    expect(columns).toContain('specPath');
    expect(columns).toContain('model');
    expect(columns).toContain('status');
    expect(columns).toContain('costUsd');
    expect(columns).toContain('durationSeconds');
    expect(columns).toContain('numTurns');
    expect(columns).toContain('toolCalls');
    expect(columns).toContain('batchId');
    expect(columns).toContain('type');
    expect(columns).toContain('prompt');
    expect(columns).toContain('cwd');
    expect(columns).toContain('sessionId');
    expect(columns).toContain('error');
    expect(columns).toContain('createdAt');
    db.close();
  });

  test('schema version is at least 2 (runs migration)', () => {
    const db = getTestDb();
    expect(getSchemaVersion(db)).toBeGreaterThanOrEqual(2);
    db.close();
  });

  test('runs indexes exist', () => {
    const db = getTestDb();
    const indexes = db.query(
      "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='runs'",
    ).all() as Array<{ name: string }>;
    const names = indexes.map(i => i.name);
    expect(names).toContain('idx_runs_batchId');
    expect(names).toContain('idx_runs_createdAt');
    expect(names).toContain('idx_runs_specPath');
    expect(names).toContain('idx_runs_model');
    expect(names).toContain('idx_runs_status');
    db.close();
  });
});

// ── insertRun ─────────────────────────────────────────────────

describe('insertRun', () => {
  let db: Database;

  beforeEach(() => {
    db = getTestDb();
  });

  test('inserts a run row with all fields', () => {
    const run = makeRun({
      id: 'run-insert-001',
      specPath: 'specs/auth.md',
      model: 'claude-opus-4-5',
      status: 'success',
      costUsd: 1.23,
      durationSeconds: 45.6,
      numTurns: 12,
      toolCalls: 8,
      batchId: 'batch-abc',
      type: 'run',
      prompt: 'build auth feature',
      cwd: '/projects/app',
      sessionId: 'sess-abc123',
      error: null,
      createdAt: '2026-01-01T10:00:00.000Z',
    });
    insertRun(db, run);

    const result = db.query('SELECT * FROM runs WHERE id = ?').get('run-insert-001') as RunRow;
    expect(result).not.toBeNull();
    expect(result.specPath).toBe('specs/auth.md');
    expect(result.costUsd).toBe(1.23);
    expect(result.durationSeconds).toBe(45.6);
    expect(result.batchId).toBe('batch-abc');
    expect(result.sessionId).toBe('sess-abc123');
    expect(result.createdAt).toBe('2026-01-01T10:00:00.000Z');
  });

  test('INSERT OR IGNORE is idempotent', () => {
    const run = makeRun({ id: 'run-idem-001', status: 'success' });
    insertRun(db, run);
    insertRun(db, { ...run, status: 'error_execution' }); // same id, different status

    const result = db.query('SELECT status FROM runs WHERE id = ?').get('run-idem-001') as { status: string };
    expect(result.status).toBe('success'); // original value preserved
  });

  test('allows null specPath (ad-hoc run without spec)', () => {
    const run = makeRun({ id: 'run-no-spec', specPath: null });
    insertRun(db, run);
    const result = db.query('SELECT specPath FROM runs WHERE id = ?').get('run-no-spec') as { specPath: string | null };
    expect(result.specPath).toBeNull();
  });

  test('stores error message when provided', () => {
    const run = makeRun({ id: 'run-with-error', status: 'error_execution', error: 'Verification failed after 3 attempts' });
    insertRun(db, run);
    const result = db.query('SELECT error FROM runs WHERE id = ?').get('run-with-error') as { error: string | null };
    expect(result.error).toBe('Verification failed after 3 attempts');
  });
});

// ── queryAggregateStats ──────────────────────────────────────

describe('queryAggregateStats', () => {
  let db: Database;

  beforeEach(() => {
    db = getTestDb();
  });

  test('returns zeros for empty table', () => {
    const stats = queryAggregateStats(db);
    expect(stats.total).toBe(0);
    // SUM() returns null for empty tables in SQLite — treat null as 0
    expect(stats.passed ?? 0).toBe(0);
    expect(stats.failed ?? 0).toBe(0);
    expect(stats.totalCost).toBe(0); // COALESCE applied in query
    expect(stats.totalDuration).toBe(0); // COALESCE applied in query
  });

  test('counts total, passed, and failed correctly', () => {
    insertRun(db, makeRun({ id: 'r1', status: 'success', costUsd: 0.10, durationSeconds: 10 }));
    insertRun(db, makeRun({ id: 'r2', status: 'success', costUsd: 0.20, durationSeconds: 20 }));
    insertRun(db, makeRun({ id: 'r3', status: 'error_execution', costUsd: 0.05, durationSeconds: 5 }));

    const stats = queryAggregateStats(db);
    expect(stats.total).toBe(3);
    expect(stats.passed).toBe(2);
    expect(stats.failed).toBe(1);
    expect(stats.totalCost).toBeCloseTo(0.35);
    expect(stats.totalDuration).toBe(35);
  });

  test('--since filters by createdAt using lexicographic comparison', () => {
    insertRun(db, makeRun({ id: 'r-old', createdAt: '2025-01-01T00:00:00Z', status: 'success', costUsd: 0.10 }));
    insertRun(db, makeRun({ id: 'r-new', createdAt: '2026-03-01T00:00:00Z', status: 'success', costUsd: 0.20 }));

    const stats = queryAggregateStats(db, '2026-01-01T00:00:00Z');
    expect(stats.total).toBe(1);
    expect(stats.totalCost).toBeCloseTo(0.20);
  });

  test('handles null costUsd gracefully (COALESCE to 0)', () => {
    insertRun(db, makeRun({ id: 'r-no-cost', costUsd: null }));
    const stats = queryAggregateStats(db);
    expect(stats.totalCost).toBe(0);
  });

  test('sums numTurns correctly', () => {
    insertRun(db, makeRun({ id: 'r-t1', numTurns: 5 }));
    insertRun(db, makeRun({ id: 'r-t2', numTurns: 10 }));
    insertRun(db, makeRun({ id: 'r-t3', numTurns: null }));

    const stats = queryAggregateStats(db);
    expect(stats.totalTurns).toBe(15);
    expect(stats.runsWithTurns).toBe(2);
  });
});

// ── querySpecStats ────────────────────────────────────────────

describe('querySpecStats', () => {
  let db: Database;

  beforeEach(() => {
    db = getTestDb();
  });

  test('groups by specPath', () => {
    insertRun(db, makeRun({ id: 'r1', specPath: 'specs/auth.md', status: 'success', costUsd: 0.10 }));
    insertRun(db, makeRun({ id: 'r2', specPath: 'specs/auth.md', status: 'success', costUsd: 0.20 }));
    insertRun(db, makeRun({ id: 'r3', specPath: 'specs/db.md', status: 'error_execution', costUsd: 0.05 }));

    const rows = querySpecStats(db);
    expect(rows.length).toBe(2);

    const authRow = rows.find(r => r.specPath === 'specs/auth.md');
    expect(authRow).toBeDefined();
    expect(authRow!.runs).toBe(2);
    expect(authRow!.passed).toBe(2);
    expect(authRow!.avgCost).toBeCloseTo(0.15);

    const dbRow = rows.find(r => r.specPath === 'specs/db.md');
    expect(dbRow!.runs).toBe(1);
    expect(dbRow!.passed).toBe(0);
  });

  test('excludes runs with null specPath', () => {
    insertRun(db, makeRun({ id: 'r1', specPath: null }));
    insertRun(db, makeRun({ id: 'r2', specPath: 'specs/test.md' }));

    const rows = querySpecStats(db);
    expect(rows.length).toBe(1);
    expect(rows[0].specPath).toBe('specs/test.md');
  });

  test('orders by runs DESC (most-run specs first)', () => {
    insertRun(db, makeRun({ id: 'r1', specPath: 'specs/a.md' }));
    insertRun(db, makeRun({ id: 'r2', specPath: 'specs/b.md' }));
    insertRun(db, makeRun({ id: 'r3', specPath: 'specs/b.md' }));
    insertRun(db, makeRun({ id: 'r4', specPath: 'specs/b.md' }));

    const rows = querySpecStats(db);
    expect(rows[0].specPath).toBe('specs/b.md'); // 3 runs
    expect(rows[1].specPath).toBe('specs/a.md'); // 1 run
  });

  test('--since filters by createdAt', () => {
    insertRun(db, makeRun({ id: 'r-old', specPath: 'specs/old.md', createdAt: '2025-01-01T00:00:00Z' }));
    insertRun(db, makeRun({ id: 'r-new', specPath: 'specs/new.md', createdAt: '2026-03-01T00:00:00Z' }));

    const rows = querySpecStats(db, '2026-01-01T00:00:00Z');
    expect(rows.length).toBe(1);
    expect(rows[0].specPath).toBe('specs/new.md');
  });
});

// ── queryModelStats ───────────────────────────────────────────

describe('queryModelStats', () => {
  let db: Database;

  beforeEach(() => {
    db = getTestDb();
  });

  test('groups by model', () => {
    insertRun(db, makeRun({ id: 'r1', model: 'opus', status: 'success', costUsd: 0.50 }));
    insertRun(db, makeRun({ id: 'r2', model: 'opus', status: 'error_execution', costUsd: 0.10 }));
    insertRun(db, makeRun({ id: 'r3', model: 'sonnet', status: 'success', costUsd: 0.05 }));

    const rows = queryModelStats(db);
    const opusRow = rows.find(r => r.model === 'opus');
    expect(opusRow).toBeDefined();
    expect(opusRow!.runs).toBe(2);
    expect(opusRow!.passed).toBe(1);
    expect(opusRow!.avgCost).toBeCloseTo(0.30);
  });

  test('returns empty array for empty table', () => {
    const rows = queryModelStats(db);
    expect(rows).toEqual([]);
  });

  test('--since filters by createdAt', () => {
    insertRun(db, makeRun({ id: 'r-old', model: 'opus', createdAt: '2025-01-01T00:00:00Z' }));
    insertRun(db, makeRun({ id: 'r-new', model: 'sonnet', createdAt: '2026-03-01T00:00:00Z' }));

    const rows = queryModelStats(db, '2026-01-01T00:00:00Z');
    expect(rows.length).toBe(1);
    expect(rows[0].model).toBe('sonnet');
  });
});

// ── queryStatusRuns ───────────────────────────────────────────

describe('queryStatusRuns', () => {
  let db: Database;

  beforeEach(() => {
    db = getTestDb();
  });

  test('returns runs ordered by createdAt DESC', () => {
    insertRun(db, makeRun({ id: 'r-first', createdAt: '2026-01-01T10:00:00Z' }));
    insertRun(db, makeRun({ id: 'r-third', createdAt: '2026-01-03T10:00:00Z' }));
    insertRun(db, makeRun({ id: 'r-second', createdAt: '2026-01-02T10:00:00Z' }));

    const rows = queryStatusRuns(db);
    expect(rows[0].id).toBe('r-third');
    expect(rows[1].id).toBe('r-second');
    expect(rows[2].id).toBe('r-first');
  });

  test('returns batchId for grouping by batch', () => {
    insertRun(db, makeRun({ id: 'r-batched', batchId: 'batch-xyz' }));
    const rows = queryStatusRuns(db);
    expect(rows[0].batchId).toBe('batch-xyz');
  });

  test('returns all runs (no limit by default)', () => {
    for (let i = 0; i < 20; i++) {
      insertRun(db, makeRun({ id: `r-${i}` }));
    }
    const rows = queryStatusRuns(db);
    expect(rows.length).toBe(20);
  });

  test('includes all required fields for status display', () => {
    insertRun(db, makeRun({ id: 'r-status', specPath: 'specs/test.md', model: 'opus', status: 'success', costUsd: 1.23 }));
    const rows = queryStatusRuns(db);
    const row = rows[0];
    expect(row.id).toBe('r-status');
    expect(row.specPath).toBe('specs/test.md');
    expect(row.model).toBe('opus');
    expect(row.status).toBe('success');
    expect(row.costUsd).toBe(1.23);
    expect(row.startedAt).toBeDefined(); // mapped from createdAt
  });
});

// ── backfillRuns ──────────────────────────────────────────────

describe('backfillRuns', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-runs-backfill-'));
    await fs.mkdir(path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z'), { recursive: true });
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test('imports summary.json files into runs table', async () => {
    const db = getTestDb();
    const summary = {
      specPath: 'specs/auth.md',
      model: 'claude-opus-4-5',
      status: 'success',
      costUsd: 0.10,
      durationSeconds: 30,
      numTurns: 5,
      toolCalls: 3,
      runId: 'batch-001',
      type: 'run',
      prompt: 'test prompt',
      cwd: tmpDir,
      sessionId: 'sess-abc',
      startedAt: '2026-01-01T10:00:00.000Z',
    };
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z', 'summary.json'),
      JSON.stringify(summary),
    );

    const count = await backfillRuns(db, tmpDir);
    expect(count).toBe(1);

    const rows = queryStatusRuns(db);
    expect(rows.length).toBe(1);
    expect(rows[0].specPath).toBe('specs/auth.md');
    expect(rows[0].id).toBe('2026-01-01T10-00-00-000Z'); // dir name as id
    db.close();
  });

  test('uses timestamp directory name as run ID', async () => {
    const db = getTestDb();
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z', 'summary.json'),
      JSON.stringify({ model: 'opus', status: 'success', durationSeconds: 1, prompt: 'p', cwd: '/c', startedAt: '2026-01-01T10:00:00Z' }),
    );

    await backfillRuns(db, tmpDir);
    const rows = queryStatusRuns(db);
    expect(rows[0].id).toBe('2026-01-01T10-00-00-000Z');
    db.close();
  });

  test('is idempotent (INSERT OR IGNORE)', async () => {
    const db = getTestDb();
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z', 'summary.json'),
      JSON.stringify({ model: 'opus', status: 'success', durationSeconds: 1, prompt: 'p', cwd: '/c', startedAt: '2026-01-01T10:00:00Z' }),
    );

    await backfillRuns(db, tmpDir);
    await backfillRuns(db, tmpDir); // second call should not duplicate
    const rows = queryStatusRuns(db);
    expect(rows.length).toBe(1);
    db.close();
  });

  test('returns 0 when results directory does not exist', async () => {
    const db = getTestDb();
    const count = await backfillRuns(db, path.join(tmpDir, 'nonexistent'));
    expect(count).toBe(0);
    db.close();
  });

  test('skips corrupt summary.json files', async () => {
    const db = getTestDb();
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z', 'summary.json'),
      '{ invalid json',
    );

    const count = await backfillRuns(db, tmpDir);
    expect(count).toBe(0);
    db.close();
  });

  test('maps runId field to batchId column', async () => {
    const db = getTestDb();
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z', 'summary.json'),
      JSON.stringify({ model: 'opus', status: 'success', durationSeconds: 1, prompt: 'p', cwd: '/c', startedAt: '2026-01-01T10:00:00Z', runId: 'batch-test-123' }),
    );

    await backfillRuns(db, tmpDir);
    const rows = queryStatusRuns(db);
    expect(rows[0].batchId).toBe('batch-test-123');
    db.close();
  });
});

// ── getDbWithBackfill ─────────────────────────────────────────

describe('getDbWithBackfill', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-backfill-lazy-'));
    await fs.mkdir(path.join(tmpDir, '.forge'), { recursive: true });
  });

  afterEach(async () => {
    closeDb(tmpDir);
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test('returns a database instance', async () => {
    const db = await getDbWithBackfill(tmpDir);
    expect(db).not.toBeNull();
  });

  test('triggers backfill when runs table is empty and results exist', async () => {
    // Create a result directory with a summary
    await fs.mkdir(path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z'), { recursive: true });
    await fs.writeFile(
      path.join(tmpDir, '.forge', 'results', '2026-01-01T10-00-00-000Z', 'summary.json'),
      JSON.stringify({ model: 'opus', status: 'success', durationSeconds: 1, prompt: 'p', cwd: tmpDir, startedAt: '2026-01-01T10:00:00Z' }),
    );

    const db = await getDbWithBackfill(tmpDir);
    expect(db).not.toBeNull();
    const rows = queryStatusRuns(db!);
    expect(rows.length).toBe(1);
  });
});
