// Generated by forge proof from dependency-level-gates.md
import { describe, test, expect, beforeEach } from 'bun:test';
import { topoSort, detectCycle, loadSpecDeps, hasDependencies } from './deps.js';
import type { SpecDep, DepLevel } from './deps.js';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  listWorktrees,
  transitionWorktreeStatus,
  getWorktreesByWorkGroup,
} from './db.js';
import type { Database } from 'bun:sqlite';
import type { WorktreeStatus } from './db.js';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function makeId(): string {
  return `wt-dep-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeId();
  insertWorktree(db, {
    id,
    spec_path: 'specs/test.md',
    branch: 'forge/test',
    worktree_path: '/tmp/project-test',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── topoSort levels drive worktree creation order ───────────────

describe('topoSort produces dependency levels', () => {
  test('specs with no dependencies all land in level 0', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: [] },
      { name: 'b.md', path: '/tmp/b.md', depends: [] },
      { name: 'c.md', path: '/tmp/c.md', depends: [] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(1);
    expect(levels[0].specs).toHaveLength(3);
    expect(levels[0].specs.map(s => s.name).sort()).toEqual(['a.md', 'b.md', 'c.md']);
  });

  test('dependent specs land in subsequent levels', () => {
    const specs: SpecDep[] = [
      { name: 'base.md', path: '/tmp/base.md', depends: [] },
      { name: 'mid.md', path: '/tmp/mid.md', depends: ['base.md'] },
      { name: 'top.md', path: '/tmp/top.md', depends: ['mid.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(3);
    expect(levels[0].specs[0].name).toBe('base.md');
    expect(levels[1].specs[0].name).toBe('mid.md');
    expect(levels[2].specs[0].name).toBe('top.md');
  });

  test('parallel specs within same level when they share the same dependency', () => {
    const specs: SpecDep[] = [
      { name: 'base.md', path: '/tmp/base.md', depends: [] },
      { name: 'feat-a.md', path: '/tmp/feat-a.md', depends: ['base.md'] },
      { name: 'feat-b.md', path: '/tmp/feat-b.md', depends: ['base.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(2);
    expect(levels[0].specs).toHaveLength(1);
    expect(levels[0].specs[0].name).toBe('base.md');
    expect(levels[1].specs).toHaveLength(2);
    expect(levels[1].specs.map(s => s.name).sort()).toEqual(['feat-a.md', 'feat-b.md']);
  });

  test('diamond dependency produces correct levels', () => {
    const specs: SpecDep[] = [
      { name: 'root.md', path: '/tmp/root.md', depends: [] },
      { name: 'left.md', path: '/tmp/left.md', depends: ['root.md'] },
      { name: 'right.md', path: '/tmp/right.md', depends: ['root.md'] },
      { name: 'top.md', path: '/tmp/top.md', depends: ['left.md', 'right.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(3);
    expect(levels[0].specs[0].name).toBe('root.md');
    expect(levels[1].specs).toHaveLength(2);
    expect(levels[2].specs[0].name).toBe('top.md');
  });

  test('single spec produces one level', () => {
    const specs: SpecDep[] = [
      { name: 'only.md', path: '/tmp/only.md', depends: [] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(1);
    expect(levels[0].specs[0].name).toBe('only.md');
  });

  test('circular dependency throws', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: ['b.md'] },
      { name: 'b.md', path: '/tmp/b.md', depends: ['a.md'] },
    ];

    expect(() => topoSort(specs)).toThrow('Circular dependency');
  });
});

// ── Level 0 specs fan out into parallel worktrees ───────────────

describe('level 0 fan-out into worktrees', () => {
  test('each level-0 spec gets its own worktree in isolate mode', () => {
    const specs: SpecDep[] = [
      { name: 'api.md', path: '/tmp/api.md', depends: [] },
      { name: 'auth.md', path: '/tmp/auth.md', depends: [] },
      { name: 'db.md', path: '/tmp/db.md', depends: [] },
    ];

    const levels = topoSort(specs);
    const level0 = levels[0];

    // In isolate mode, each spec in level 0 gets a worktree
    const worktreeIds: string[] = [];
    for (const spec of level0.specs) {
      const id = insertTestWorktree({
        spec_path: `specs/${spec.name}`,
        branch: `forge/isolate-${spec.name.replace('.md', '')}`,
        worktree_path: `/tmp/project-${spec.name.replace('.md', '')}`,
        work_group_id: 'wg-level0',
      });
      worktreeIds.push(id);
    }

    const groupWorktrees = getWorktreesByWorkGroup(db, 'wg-level0');
    expect(groupWorktrees).toHaveLength(3);
  });
});

// ── Failure in a level skips dependent levels ───────────────────

describe('failure propagation between levels', () => {
  test('failed spec causes dependent levels to be cancelled', () => {
    const specs: SpecDep[] = [
      { name: 'base.md', path: '/tmp/base.md', depends: [] },
      { name: 'dep.md', path: '/tmp/dep.md', depends: ['base.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(2);

    // Simulate level 0 failure
    const baseId = insertTestWorktree({
      spec_path: 'specs/base.md',
      branch: 'forge/base',
      worktree_path: '/tmp/project-base',
      work_group_id: 'wg-fail-test',
    });
    transitionWorktreeStatus(db, baseId, 'failed', 'Build failed');

    // Check that base failed
    expect(getWorktree(db, baseId)!.status).toBe('failed');

    // In the real code, dependent specs would be marked cancelled
    // Verify the failure propagation logic:
    const levelFailures = [{ spec: 'base.md', status: 'fail' }];
    expect(levelFailures.length).toBeGreaterThan(0);
    // This means level 1 specs should be cancelled
  });

  test('all specs in failed level are checked before cancelling dependents', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: [] },
      { name: 'b.md', path: '/tmp/b.md', depends: [] },
      { name: 'c.md', path: '/tmp/c.md', depends: ['a.md', 'b.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(2);
    expect(levels[0].specs).toHaveLength(2);

    // If only a.md fails but b.md passes, level 1 is still skipped
    const level0Results = [
      { spec: 'a.md', status: 'fail' },
      { spec: 'b.md', status: 'success' },
    ];

    const failures = level0Results.filter(r => r.status !== 'success');
    expect(failures.length).toBeGreaterThan(0);
    // Therefore c.md (level 1) should be cancelled
  });
});

// ── Consolidation between levels ────────────────────────────────

describe('intermediate consolidation between levels', () => {
  test('successful branches from level 0 are collected for consolidation', () => {
    // Simulate worktrees completing successfully
    const id1 = insertTestWorktree({
      spec_path: 'specs/api.md',
      branch: 'forge/isolate-api',
      worktree_path: '/tmp/api',
      work_group_id: 'wg-consol',
    });
    const id2 = insertTestWorktree({
      spec_path: 'specs/auth.md',
      branch: 'forge/isolate-auth',
      worktree_path: '/tmp/auth',
      work_group_id: 'wg-consol',
    });

    transitionWorktreeStatus(db, id1, 'running');
    transitionWorktreeStatus(db, id1, 'complete');
    transitionWorktreeStatus(db, id2, 'running');
    transitionWorktreeStatus(db, id2, 'complete');

    // Collect successful branches for consolidation
    const complete = getWorktreesByWorkGroup(db, 'wg-consol')
      .filter(w => w.status === 'complete');

    const branches = complete.map(w => w.branch);
    expect(branches).toHaveLength(2);
    expect(branches).toContain('forge/isolate-api');
    expect(branches).toContain('forge/isolate-auth');
  });

  test('level 1 worktrees would be created from consolidated state', () => {
    // This tests the conceptual flow: level 1 uses a startPoint from consolidation
    const consolidationBranch = 'forge/wg-consol-level-0';

    // Level 1 worktrees should use consolidationBranch as startPoint
    // The createWorktree call would include: startPoint: consolidationBranch
    expect(consolidationBranch).toContain('level-0');
  });
});

// ── Progress display shows level boundaries ─────────────────────

describe('progress display level boundaries', () => {
  test('levels produce correct display format', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: [] },
      { name: 'b.md', path: '/tmp/b.md', depends: [] },
      { name: 'c.md', path: '/tmp/c.md', depends: ['a.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(2);

    // Format: "Level {idx+1}/{total}: {count} spec(s)"
    for (let i = 0; i < levels.length; i++) {
      const display = `Level ${i + 1}/${levels.length}: ${levels[i].specs.length} spec(s)`;
      expect(display).toContain('Level');
      expect(display).toContain('spec(s)');
    }

    expect(`Level 1/${levels.length}: ${levels[0].specs.length} spec(s)`).toBe('Level 1/2: 2 spec(s)');
    expect(`Level 2/${levels.length}: ${levels[1].specs.length} spec(s)`).toBe('Level 2/2: 1 spec(s)');
  });
});

// ── hasDependencies detection ───────────────────────────────────

describe('hasDependencies for isolate mode branching', () => {
  test('returns true when any spec has depends', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: [] },
      { name: 'b.md', path: '/tmp/b.md', depends: ['a.md'] },
    ];
    expect(hasDependencies(specs)).toBe(true);
  });

  test('returns false when no spec has depends', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: [] },
      { name: 'b.md', path: '/tmp/b.md', depends: [] },
    ];
    expect(hasDependencies(specs)).toBe(false);
  });
});

// ── detectCycle for safety ──────────────────────────────────────

describe('cycle detection for isolate mode safety', () => {
  test('returns null for acyclic graph', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: [] },
      { name: 'b.md', path: '/tmp/b.md', depends: ['a.md'] },
    ];
    expect(detectCycle(specs)).toBeNull();
  });

  test('detects direct cycle', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: ['b.md'] },
      { name: 'b.md', path: '/tmp/b.md', depends: ['a.md'] },
    ];
    const cycle = detectCycle(specs);
    expect(cycle).not.toBeNull();
    expect(cycle!.length).toBeGreaterThanOrEqual(2);
  });

  test('detects transitive cycle', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/tmp/a.md', depends: ['c.md'] },
      { name: 'b.md', path: '/tmp/b.md', depends: ['a.md'] },
      { name: 'c.md', path: '/tmp/c.md', depends: ['b.md'] },
    ];
    const cycle = detectCycle(specs);
    expect(cycle).not.toBeNull();
  });
});

// ── Complex multi-level scenario ────────────────────────────────

describe('complex multi-level dependency graph', () => {
  test('5 specs across 3 levels with fan-out and fan-in', () => {
    const specs: SpecDep[] = [
      { name: 'schema.md', path: '/tmp/schema.md', depends: [] },
      { name: 'api.md', path: '/tmp/api.md', depends: ['schema.md'] },
      { name: 'auth.md', path: '/tmp/auth.md', depends: ['schema.md'] },
      { name: 'ui.md', path: '/tmp/ui.md', depends: ['api.md', 'auth.md'] },
      { name: 'e2e.md', path: '/tmp/e2e.md', depends: ['ui.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(4);

    // Level 0: schema (no deps)
    expect(levels[0].specs.map(s => s.name)).toEqual(['schema.md']);
    // Level 1: api, auth (both depend on schema)
    expect(levels[1].specs.map(s => s.name).sort()).toEqual(['api.md', 'auth.md']);
    // Level 2: ui (depends on api + auth)
    expect(levels[2].specs.map(s => s.name)).toEqual(['ui.md']);
    // Level 3: e2e (depends on ui)
    expect(levels[3].specs.map(s => s.name)).toEqual(['e2e.md']);
  });
});
