// Generated by forge proof from execution-mode-single.md, execution-mode-isolate.md, dependency-level-gates.md
import { describe, test, expect, beforeAll, afterAll, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  getWorktreesByWorkGroup,
  updateWorktreeStatus,
  listWorktrees,
} from './db.js';
import { generateWorkGroupId, deriveSpecName } from './utils.js';
import { topoSort, loadSpecDeps } from './deps.js';
import type { SpecDep, DepLevel } from './deps.js';
import type { Database } from 'bun:sqlite';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';

let db: Database;

beforeAll(() => { setupHermeticGit(); });
afterAll(() => { teardownHermeticGit(); });

beforeEach(() => {
  db = getTestDb();
});

// ── Single worktree mode (default) ──────────────────────────

describe('single worktree execution mode', () => {
  test('single worktree registers all spec paths in spec_paths JSON array', () => {
    const wgId = generateWorkGroupId();
    const wtId = `wt-single-${Date.now()}`;

    insertWorktree(db, {
      id: wtId,
      work_group_id: wgId,
      spec_path: 'specs/eng-123/',
      spec_paths: ['specs/eng-123/auth.md', 'specs/eng-123/api.md', 'specs/eng-123/ui.md'],
      branch: 'forge/eng-123',
      worktree_path: '/tmp/project-eng-123',
    });

    const wt = getWorktree(db, wtId);
    expect(wt).not.toBeNull();
    const paths = JSON.parse(wt!.spec_paths);
    expect(paths).toHaveLength(3);
    expect(paths).toContain('specs/eng-123/auth.md');
  });

  test('single worktree transitions through lifecycle', () => {
    const wtId = `wt-lifecycle-${Date.now()}`;
    insertWorktree(db, {
      id: wtId,
      spec_path: 'specs/feature.md',
      branch: 'forge/feature',
      worktree_path: '/tmp/project-feature',
      status: 'created',
    });

    updateWorktreeStatus(db, wtId, 'running');
    expect(getWorktree(db, wtId)!.status).toBe('running');

    updateWorktreeStatus(db, wtId, 'complete');
    expect(getWorktree(db, wtId)!.status).toBe('complete');
  });

  test('batch summary includes worktree path', () => {
    const wtId = `wt-path-${Date.now()}`;
    const wtPath = '/home/dev/project-auth-login';
    insertWorktree(db, {
      id: wtId,
      spec_path: 'specs/auth-login.md',
      branch: 'forge/auth-login',
      worktree_path: wtPath,
    });

    const wt = getWorktree(db, wtId);
    expect(wt!.worktree_path).toBe(wtPath);
  });
});

// ── Isolate mode (worktree-per-spec) ─────────────────────────

describe('isolate mode worktree-per-spec', () => {
  test('each spec gets its own worktree with same work_group_id', () => {
    const wgId = generateWorkGroupId();
    const specs = ['auth.md', 'api.md', 'ui.md'];

    for (const spec of specs) {
      const name = deriveSpecName(spec);
      insertWorktree(db, {
        id: `wt-iso-${name}-${Date.now()}`,
        work_group_id: wgId,
        spec_path: `specs/${spec}`,
        branch: `forge/${name}`,
        worktree_path: `/tmp/project-${name}`,
      });
    }

    const group = getWorktreesByWorkGroup(db, wgId);
    expect(group).toHaveLength(3);
    expect(group.every(w => w.work_group_id === wgId)).toBe(true);
  });

  test('each worktree transitions independently', () => {
    const wgId = generateWorkGroupId();

    const wt1 = `wt-ind-1-${Date.now()}`;
    const wt2 = `wt-ind-2-${Date.now()}`;

    insertWorktree(db, {
      id: wt1,
      work_group_id: wgId,
      spec_path: 'a.md',
      branch: 'forge/a',
      worktree_path: '/tmp/a',
      status: 'created',
    });
    insertWorktree(db, {
      id: wt2,
      work_group_id: wgId,
      spec_path: 'b.md',
      branch: 'forge/b',
      worktree_path: '/tmp/b',
      status: 'created',
    });

    // wt1 succeeds
    updateWorktreeStatus(db, wt1, 'running');
    updateWorktreeStatus(db, wt1, 'complete');

    // wt2 fails
    updateWorktreeStatus(db, wt2, 'running');
    updateWorktreeStatus(db, wt2, 'failed', 'Build error');

    expect(getWorktree(db, wt1)!.status).toBe('complete');
    expect(getWorktree(db, wt2)!.status).toBe('failed');
    expect(getWorktree(db, wt2)!.error).toBe('Build error');
  });

  test('results from all worktrees persist to the same work group', () => {
    const wgId = generateWorkGroupId();

    for (let i = 0; i < 4; i++) {
      insertWorktree(db, {
        id: `wt-persist-${i}-${Date.now()}`,
        work_group_id: wgId,
        spec_path: `spec-${i}.md`,
        branch: `forge/spec-${i}`,
        worktree_path: `/tmp/spec-${i}`,
        status: 'created',
      });
    }

    const all = getWorktreesByWorkGroup(db, wgId);
    expect(all).toHaveLength(4);
  });
});

// ── Dependency Level Gates ───────────────────────────────────

describe('dependency level gates for isolated execution', () => {
  test('topoSort groups specs into dependency levels', () => {
    const specs: SpecDep[] = [
      { name: 'base.md', path: '/specs/base.md', depends: [] },
      { name: 'auth.md', path: '/specs/auth.md', depends: ['base.md'] },
      { name: 'api.md', path: '/specs/api.md', depends: ['base.md'] },
      { name: 'ui.md', path: '/specs/ui.md', depends: ['auth.md', 'api.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels).toHaveLength(3);

    // Level 0: no deps
    expect(levels[0].specs.map(s => s.name)).toEqual(['base.md']);
    // Level 1: depends on base
    expect(levels[1].specs.map(s => s.name).sort()).toEqual(['api.md', 'auth.md']);
    // Level 2: depends on auth + api
    expect(levels[2].specs.map(s => s.name)).toEqual(['ui.md']);
  });

  test('level 0 specs have no dependencies', () => {
    const specs: SpecDep[] = [
      { name: 'a.md', path: '/specs/a.md', depends: [] },
      { name: 'b.md', path: '/specs/b.md', depends: [] },
      { name: 'c.md', path: '/specs/c.md', depends: ['a.md'] },
    ];

    const levels = topoSort(specs);
    expect(levels[0].specs.every(s => s.depends.length === 0)).toBe(true);
    expect(levels[0].specs).toHaveLength(2);
  });

  test('specs within same level can run in parallel', () => {
    const specs: SpecDep[] = [
      { name: 'dep.md', path: '/specs/dep.md', depends: [] },
      { name: 'a.md', path: '/specs/a.md', depends: ['dep.md'] },
      { name: 'b.md', path: '/specs/b.md', depends: ['dep.md'] },
      { name: 'c.md', path: '/specs/c.md', depends: ['dep.md'] },
    ];

    const levels = topoSort(specs);
    // Level 1 has 3 independent specs
    expect(levels[1].specs).toHaveLength(3);
  });

  test('failed spec in a level blocks dependent levels', () => {
    const wgId = generateWorkGroupId();

    // Level 0 worktrees
    const wt0a = `wt-l0a-${Date.now()}`;
    insertWorktree(db, {
      id: wt0a,
      work_group_id: wgId,
      spec_path: 'base.md',
      branch: 'forge/base',
      worktree_path: '/tmp/base',
      status: 'created',
    });
    updateWorktreeStatus(db, wt0a, 'running');
    updateWorktreeStatus(db, wt0a, 'failed', 'Build error');

    // Level 1 should see level 0 failed
    const group = getWorktreesByWorkGroup(db, wgId);
    const failed = group.filter(w => w.status === 'failed');
    expect(failed).toHaveLength(1);
  });

  test('loadSpecDeps parses dependencies from spec files', async () => {
    const specDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-dep-test-'));
    try {
      await fs.writeFile(
        path.join(specDir, 'base.md'),
        '# Base\n\nNo deps',
      );
      await fs.writeFile(
        path.join(specDir, 'auth.md'),
        '---\ndepends: [base.md]\n---\n# Auth',
      );

      const deps = await loadSpecDeps(
        [path.join(specDir, 'base.md'), path.join(specDir, 'auth.md')],
        ['base.md', 'auth.md'],
      );

      expect(deps).toHaveLength(2);
      expect(deps[0].depends).toEqual([]);
      expect(deps[1].depends).toEqual(['base.md']);
    } finally {
      await fs.rm(specDir, { recursive: true, force: true });
    }
  });
});
