// Generated by forge proof from executor-worktree-creation.md
import { describe, test, expect, beforeEach } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  insertTask,
  getTaskById,
  claimTask,
  linkWorktreeTask,
  linkWorktreeSession,
  updateWorktreePid,
  transitionWorktreeStatus,
} from './db.js';
import type { Database } from 'bun:sqlite';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function makeWorktreeId(): string {
  return `wt-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeWorktreeId();
  insertWorktree(db, {
    id,
    spec_path: 'specs/feature.md',
    branch: 'forge/feature',
    worktree_path: '/tmp/project-feature',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── Task params with worktree intent ─────────────────────────

describe('task params store worktree intent', () => {
  test('worktree boolean flag stored in task params', () => {
    const now = new Date().toISOString();
    const params = { worktree: true, specPath: 'specs/feature.md' };
    db.run(
      `INSERT INTO tasks (id, command, status, cwd, stdout, stderr, params, createdAt, updatedAt)
       VALUES ('task-wt-intent', 'forge run', 'pending', '/repo', '[]', '[]', ?, ?, ?)`,
      [JSON.stringify(params), now, now],
    );

    const row = getTaskById(db, 'task-wt-intent');
    expect(row).not.toBeNull();
    const parsed = JSON.parse(row!.params);
    expect(parsed.worktree).toBe(true);
    expect(parsed.specPath).toBe('specs/feature.md');
  });

  test('worktreeId stored in task params for existing worktree', () => {
    const now = new Date().toISOString();
    const params = { worktreeId: 'wt-existing-123', specPath: 'specs/auth.md' };
    db.run(
      `INSERT INTO tasks (id, command, status, cwd, stdout, stderr, params, createdAt, updatedAt)
       VALUES ('task-wt-existing', 'forge run', 'pending', '/repo', '[]', '[]', ?, ?, ?)`,
      [JSON.stringify(params), now, now],
    );

    const row = getTaskById(db, 'task-wt-existing');
    const parsed = JSON.parse(row!.params);
    expect(parsed.worktreeId).toBe('wt-existing-123');
  });

  test('isolate flag stored in task params', () => {
    const now = new Date().toISOString();
    const params = { isolate: true, specPath: 'specs/' };
    db.run(
      `INSERT INTO tasks (id, command, status, cwd, stdout, stderr, params, createdAt, updatedAt)
       VALUES ('task-isolate', 'forge run', 'pending', '/repo', '[]', '[]', ?, ?, ?)`,
      [JSON.stringify(params), now, now],
    );

    const row = getTaskById(db, 'task-isolate');
    const parsed = JSON.parse(row!.params);
    expect(parsed.isolate).toBe(true);
  });
});

// ── Executor claims task and creates worktree ────────────────

describe('executor worktree lifecycle on task claim', () => {
  test('worktree transitions created -> running on task start', () => {
    const wtId = insertTestWorktree({ status: 'created' });

    transitionWorktreeStatus(db, wtId, 'running');
    const wt = getWorktree(db, wtId);
    expect(wt!.status).toBe('running');
  });

  test('executor records PID in worktree row', () => {
    const wtId = insertTestWorktree();
    updateWorktreePid(db, wtId, 54321);

    const wt = getWorktree(db, wtId);
    expect(wt!.pid).toBe(54321);
  });

  test('executor links task_id to worktree', () => {
    const wtId = insertTestWorktree();
    linkWorktreeTask(db, wtId, 'task-exec-001');

    const wt = getWorktree(db, wtId);
    expect(wt!.task_id).toBe('task-exec-001');
  });

  test('executor links session_id to worktree after SDK session starts', () => {
    const wtId = insertTestWorktree();
    linkWorktreeSession(db, wtId, 'sess-exec-001');

    const wt = getWorktree(db, wtId);
    expect(wt!.session_id).toBe('sess-exec-001');
  });
});

// ── Executor handles success/failure ─────────────────────────

describe('executor worktree completion handling', () => {
  test('worktree transitions to complete on task success', () => {
    const wtId = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, wtId, 'running');
    transitionWorktreeStatus(db, wtId, 'complete');

    expect(getWorktree(db, wtId)!.status).toBe('complete');
  });

  test('worktree transitions to failed with error on task failure', () => {
    const wtId = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, wtId, 'running');
    transitionWorktreeStatus(db, wtId, 'failed', 'Build failed: tsc errors');

    const wt = getWorktree(db, wtId);
    expect(wt!.status).toBe('failed');
    expect(wt!.error).toBe('Build failed: tsc errors');
  });

  test('worktree creation failure marks task as failed', () => {
    const now = new Date().toISOString();
    db.run(
      `INSERT INTO tasks (id, command, status, cwd, stdout, stderr, params, createdAt, updatedAt)
       VALUES ('task-wt-fail', 'forge run', 'running', '/repo', '[]', '[]', '{}', ?, ?)`,
      [now, now],
    );

    // Simulate executor marking task as failed due to worktree creation error
    db.run(
      `UPDATE tasks SET status = 'failed', stderr = ? WHERE id = 'task-wt-fail'`,
      [JSON.stringify(['Worktree creation failed: branch already checked out'])],
    );

    const row = getTaskById(db, 'task-wt-fail');
    expect(row!.status).toBe('failed');
    const stderr = JSON.parse(row!.stderr) as string[];
    expect(stderr[0]).toContain('Worktree creation failed');
  });
});

// ── Full executor-worktree integration flow ──────────────────

describe('executor-worktree full lifecycle', () => {
  test('task claim -> worktree create -> run -> complete', () => {
    // 1. Task inserted (pending)
    const now = new Date().toISOString();
    const params = { worktree: true, specPath: 'specs/auth.md' };
    db.run(
      `INSERT INTO tasks (id, command, status, cwd, stdout, stderr, params, createdAt, updatedAt)
       VALUES ('task-full-flow', 'forge run', 'pending', '/repo', '[]', '[]', ?, ?, ?)`,
      [JSON.stringify(params), now, now],
    );

    // 2. Executor claims task
    const claimed = claimTask(db, 'task-full-flow', process.pid);
    expect(claimed).toBe(true);
    expect(getTaskById(db, 'task-full-flow')!.status).toBe('running');

    // 3. Worktree created and registered
    const wtId = insertTestWorktree({
      spec_path: 'specs/auth.md',
      worktree_path: '/tmp/project-auth-wt',
      status: 'created',
    });

    // 4. Link worktree to task
    linkWorktreeTask(db, wtId, 'task-full-flow');
    updateWorktreePid(db, wtId, process.pid);

    // 5. Transition worktree to running
    transitionWorktreeStatus(db, wtId, 'running');
    expect(getWorktree(db, wtId)!.status).toBe('running');

    // 6. Link session after SDK starts
    linkWorktreeSession(db, wtId, 'sess-full-flow');

    // 7. Success: transition worktree to complete
    transitionWorktreeStatus(db, wtId, 'complete');

    // Verify final state
    const finalWt = getWorktree(db, wtId)!;
    expect(finalWt.status).toBe('complete');
    expect(finalWt.task_id).toBe('task-full-flow');
    expect(finalWt.session_id).toBe('sess-full-flow');
    expect(finalWt.pid).toBe(process.pid);
  });
});
