// Generated by forge proof from fs-watch-sessions-list.md, fs-watch-specs-tab.md, fs-watch-pipeline-tab.md, fs-watch-session-events.md, fs-watch-rerender-profile.md
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { createFileWatcher, type FileWatcherHandle } from './file-watcher.js';
import { writeFile, mkdir, rm, readFile } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';
import { randomUUID } from 'crypto';

// ── Helpers ──────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

let testDir: string;
let handles: FileWatcherHandle[];

beforeEach(async () => {
  testDir = join(tmpdir(), `forge-fw-tui-test-${randomUUID()}`);
  await mkdir(testDir, { recursive: true });
  handles = [];
});

afterEach(async () => {
  for (const h of handles) h.dispose();
  handles = [];
  await rm(testDir, { recursive: true, force: true }).catch(() => {});
});

function track(handle: FileWatcherHandle): FileWatcherHandle {
  handles.push(handle);
  return handle;
}

// ── Sessions list: directory watching ───────────────────────

describe('fs-watch sessions list: directory watches', () => {
  test('watches .forge/sessions/ directory for new sessions', async () => {
    const sessionsDir = join(testDir, '.forge', 'sessions');
    await mkdir(sessionsDir, { recursive: true });

    let callCount = 0;
    const handle = track(createFileWatcher(sessionsDir, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
      type: 'directory',
    }));

    // Create a new session directory
    await mkdir(join(sessionsDir, 'new-session'));
    await sleep(300);

    expect(callCount).toBeGreaterThanOrEqual(1);
  });

  test('watches .forge/results/ directory for completed sessions', async () => {
    const resultsDir = join(testDir, '.forge', 'results');
    await mkdir(resultsDir, { recursive: true });

    let callCount = 0;
    const handle = track(createFileWatcher(resultsDir, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
      type: 'directory',
    }));

    // Create a result directory
    const resultDir = join(resultsDir, '2026-03-11T00:00:00Z');
    await mkdir(resultDir, { recursive: true });
    await writeFile(join(resultDir, 'summary.json'), '{}');
    await sleep(300);

    expect(callCount).toBeGreaterThanOrEqual(1);
  });

  test('watches .forge/latest-session.json for session start', async () => {
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });
    const latestPath = join(forgeDir, 'latest-session.json');
    await writeFile(latestPath, JSON.stringify({ sessionId: 'old' }));

    let callCount = 0;
    const handle = track(createFileWatcher(latestPath, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    }));

    // Update latest-session.json
    await writeFile(latestPath, JSON.stringify({ sessionId: 'new-session' }));
    await sleep(300);

    expect(callCount).toBeGreaterThanOrEqual(1);
  });

  test('handles missing .forge/sessions/ directory gracefully', () => {
    const missingPath = join(testDir, '.forge', 'sessions');
    // Should not throw when directory doesn't exist
    let callCount = 0;
    const handle = track(createFileWatcher(missingPath, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 200,
      type: 'directory',
    }));

    // Falls back to polling without crash
    expect(handle).toBeDefined();
  });

  test('all watchers disposed on cleanup', async () => {
    const sessionsDir = join(testDir, '.forge', 'sessions');
    const resultsDir = join(testDir, '.forge', 'results');
    const latestPath = join(testDir, '.forge', 'latest-session.json');
    await mkdir(sessionsDir, { recursive: true });
    await mkdir(resultsDir, { recursive: true });
    await writeFile(latestPath, '{}');

    const h1 = track(createFileWatcher(sessionsDir, () => {}, { type: 'directory', debounceMs: 50, fallbackIntervalMs: 60000 }));
    const h2 = track(createFileWatcher(resultsDir, () => {}, { type: 'directory', debounceMs: 50, fallbackIntervalMs: 60000 }));
    const h3 = track(createFileWatcher(latestPath, () => {}, { debounceMs: 50, fallbackIntervalMs: 60000 }));

    // Dispose all
    h1.dispose();
    h2.dispose();
    h3.dispose();

    // Should not throw or produce errors
    await sleep(100);
  });
});

// ── Sessions list: debounced callback ───────────────────────

describe('fs-watch sessions list: debounced reload', () => {
  test('single debounced callback handles all three watch sources', async () => {
    let reloadCount = 0;
    const reload = () => { reloadCount++; };

    const forgeDir = join(testDir, '.forge');
    await mkdir(join(forgeDir, 'sessions'), { recursive: true });
    await mkdir(join(forgeDir, 'results'), { recursive: true });
    await writeFile(join(forgeDir, 'latest-session.json'), '{}');

    // All three watchers call the same reload function
    const h1 = track(createFileWatcher(join(forgeDir, 'sessions'), reload, { type: 'directory', debounceMs: 100, fallbackIntervalMs: 60000 }));
    const h2 = track(createFileWatcher(join(forgeDir, 'results'), reload, { type: 'directory', debounceMs: 100, fallbackIntervalMs: 60000 }));
    const h3 = track(createFileWatcher(join(forgeDir, 'latest-session.json'), reload, { debounceMs: 100, fallbackIntervalMs: 60000 }));

    // Trigger changes on multiple sources rapidly
    await mkdir(join(forgeDir, 'sessions', 'new-sess'));
    await writeFile(join(forgeDir, 'latest-session.json'), JSON.stringify({ sessionId: 'new-sess' }));
    await sleep(300);

    // Reload called at least once from the changes
    expect(reloadCount).toBeGreaterThanOrEqual(1);
  });

  test('initial load happens immediately on mount (not deferred)', async () => {
    // Simulate initial load pattern: load first, then set up watchers
    let loaded = false;
    const load = () => { loaded = true; };

    // Initial load (synchronous-style)
    load();
    expect(loaded).toBe(true);

    // Then set up watcher for subsequent changes
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });
    await writeFile(join(forgeDir, 'latest-session.json'), '{}');
    const handle = track(createFileWatcher(join(forgeDir, 'latest-session.json'), load, { debounceMs: 50, fallbackIntervalMs: 60000 }));
  });
});

// ── Specs tab: manifest file watching ───────────────────────

describe('fs-watch specs tab: manifest watching', () => {
  test('watches .forge/specs.json for manifest changes', async () => {
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });
    const specsPath = join(forgeDir, 'specs.json');
    await writeFile(specsPath, JSON.stringify({ version: 1, specs: [] }));

    let callCount = 0;
    const handle = track(createFileWatcher(specsPath, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    }));

    // Simulate manifest update (atomic write: tmp + rename)
    const tmpPath = specsPath + '.tmp';
    await writeFile(tmpPath, JSON.stringify({ version: 1, specs: [{ spec: 'new.md' }] }));
    const { rename } = await import('fs/promises');
    await rename(tmpPath, specsPath);

    await sleep(300);
    expect(callCount).toBeGreaterThanOrEqual(1);
  });

  test('no duplicate loadManifest calls from overlapping debounce and fallback', async () => {
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });
    const specsPath = join(forgeDir, 'specs.json');
    await writeFile(specsPath, '{}');

    let callCount = 0;
    const handle = track(createFileWatcher(specsPath, () => { callCount++; }, {
      debounceMs: 200,
      fallbackIntervalMs: 200,
    }));

    // Wait for at most one debounce + one fallback cycle
    await sleep(500);

    // Should be a reasonable number (not excessive duplicates)
    // Fallback fires every 200ms, so expect ~2-3 in 500ms
    expect(callCount).toBeLessThanOrEqual(5);
  });

  test('watcher disposed on unmount', async () => {
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });
    const specsPath = join(forgeDir, 'specs.json');
    await writeFile(specsPath, '{}');

    let callCount = 0;
    const handle = createFileWatcher(specsPath, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    });

    handle.dispose();
    const countAtDispose = callCount;

    await sleep(300);
    expect(callCount).toBe(countAtDispose);
  });
});

// ── Pipeline tab: pipeline.json watching ────────────────────

describe('fs-watch pipeline tab: state watching', () => {
  test('watches .forge/pipeline.json for state changes', async () => {
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });
    const pipelinePath = join(forgeDir, 'pipeline.json');
    await writeFile(pipelinePath, JSON.stringify({ id: 'p1', status: 'running' }));

    let callCount = 0;
    const handle = track(createFileWatcher(pipelinePath, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    }));

    // Update pipeline state (simulates pipeline process writing)
    await writeFile(pipelinePath, JSON.stringify({ id: 'p1', status: 'paused_at_gate' }));
    await sleep(300);

    expect(callCount).toBeGreaterThanOrEqual(1);
  });

  test('watches .forge/pipelines/ directory for historical states', async () => {
    const pipelinesDir = join(testDir, '.forge', 'pipelines');
    await mkdir(pipelinesDir, { recursive: true });

    let callCount = 0;
    const handle = track(createFileWatcher(pipelinesDir, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
      type: 'directory',
    }));

    // Create a new historical pipeline file
    await writeFile(join(pipelinesDir, 'p1.json'), '{}');
    await sleep(300);

    expect(callCount).toBeGreaterThanOrEqual(1);
  });

  test('debounces rapid pipeline state writes during gate polling', async () => {
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });
    const pipelinePath = join(forgeDir, 'pipeline.json');
    await writeFile(pipelinePath, '{"status": "running"}');

    let callCount = 0;
    const handle = track(createFileWatcher(pipelinePath, () => { callCount++; }, {
      debounceMs: 100,
      fallbackIntervalMs: 60000,
    }));

    // Rapid writes (pipeline polls and writes every 2s, but debounce coalesces)
    await writeFile(pipelinePath, '{"status": "running", "tick": 1}');
    await sleep(20);
    await writeFile(pipelinePath, '{"status": "running", "tick": 2}');
    await sleep(20);
    await writeFile(pipelinePath, '{"status": "paused_at_gate", "tick": 3}');

    await sleep(250);

    // Debounced: should be fewer than 3 calls
    expect(callCount).toBeLessThanOrEqual(3);
  });
});

// ── Session events: events.jsonl watching ───────────────────

describe('fs-watch session events: events.jsonl watching', () => {
  test('watches specific events.jsonl file for selected session', async () => {
    const sessionDir = join(testDir, '.forge', 'sessions', 'sess-1');
    await mkdir(sessionDir, { recursive: true });
    const eventsPath = join(sessionDir, 'events.jsonl');
    await writeFile(eventsPath, '{"type":"session_start"}\n');

    let callCount = 0;
    const handle = track(createFileWatcher(eventsPath, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    }));

    // Append new event
    const { appendFile } = await import('fs/promises');
    await appendFile(eventsPath, '{"type":"text_delta","content":"hello"}\n');
    await sleep(300);

    expect(callCount).toBeGreaterThanOrEqual(1);
  });

  test('previous session watcher disposed before creating new one', async () => {
    const session1Dir = join(testDir, '.forge', 'sessions', 'sess-1');
    const session2Dir = join(testDir, '.forge', 'sessions', 'sess-2');
    await mkdir(session1Dir, { recursive: true });
    await mkdir(session2Dir, { recursive: true });
    const events1 = join(session1Dir, 'events.jsonl');
    const events2 = join(session2Dir, 'events.jsonl');
    await writeFile(events1, '{"type":"session_start"}\n');
    await writeFile(events2, '{"type":"session_start"}\n');

    let call1Count = 0;
    let call2Count = 0;

    // Watch session 1
    const handle1 = createFileWatcher(events1, () => { call1Count++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    });

    // Dispose session 1 before watching session 2
    handle1.dispose();
    const countAfterDispose = call1Count;

    // Watch session 2
    const handle2 = track(createFileWatcher(events2, () => { call2Count++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    }));

    await sleep(300);

    // Session 1 watcher should not fire after dispose
    expect(call1Count).toBe(countAfterDispose);
    // Session 2 watcher should be active
    expect(call2Count).toBeGreaterThanOrEqual(1);
  });

  test('adaptive fallback: short interval while running, long when idle', () => {
    // Adaptive fallback intervals
    const runningInterval = 3000; // 2-5s while session is running
    const idleInterval = 15000;   // 15-30s when completed

    expect(runningInterval).toBeLessThanOrEqual(5000);
    expect(idleInterval).toBeGreaterThanOrEqual(15000);
  });

  test('handles legacy stream.log fallback path', async () => {
    const sessionDir = join(testDir, '.forge', 'sessions', 'legacy-sess');
    await mkdir(sessionDir, { recursive: true });
    // Only stream.log, no events.jsonl
    const logPath = join(sessionDir, 'stream.log');
    await writeFile(logPath, '[ts] Session started\n');

    let callCount = 0;
    const handle = track(createFileWatcher(logPath, () => { callCount++; }, {
      debounceMs: 50,
      fallbackIntervalMs: 100,
    }));

    // Append to stream.log
    const { appendFile } = await import('fs/promises');
    await appendFile(logPath, '[ts] Reading file...\n');
    await sleep(300);

    expect(callCount).toBeGreaterThanOrEqual(1);
  });
});

// ── Incremental byte-offset pattern preservation ────────────

describe('fs-watch session events: incremental reader', () => {
  test('byte offset tracks position for incremental reads', async () => {
    const sessionDir = join(testDir, '.forge', 'sessions', 'incr-sess');
    await mkdir(sessionDir, { recursive: true });
    const eventsPath = join(sessionDir, 'events.jsonl');

    // Write initial events
    const event1 = JSON.stringify({ type: 'session_start', timestamp: '2026-01-01T00:00:00Z' });
    const event2 = JSON.stringify({ type: 'text_delta', timestamp: '2026-01-01T00:00:01Z', content: 'hello' });
    await writeFile(eventsPath, event1 + '\n' + event2 + '\n');

    // Read full content and track offset
    const content = await readFile(eventsPath, 'utf-8');
    let offset = Buffer.byteLength(content, 'utf-8');

    // Append more events
    const event3 = JSON.stringify({ type: 'session_end', timestamp: '2026-01-01T00:01:00Z', durationSeconds: 60, status: 'success' });
    const { appendFile } = await import('fs/promises');
    await appendFile(eventsPath, event3 + '\n');

    // Read only new content from offset
    const fullContent = await readFile(eventsPath, 'utf-8');
    const newContent = fullContent.slice(offset);
    const newEvents = newContent.split('\n').filter(l => l.trim()).map(l => JSON.parse(l));

    expect(newEvents).toHaveLength(1);
    expect(newEvents[0].type).toBe('session_end');
  });
});

// ── Re-render profiling ─────────────────────────────────────

describe('fs-watch rerender profile: benchmark validation', () => {
  test('manifest parse time for typical 36k specs.json', async () => {
    const forgeDir = join(testDir, '.forge');
    await mkdir(forgeDir, { recursive: true });

    // Create a ~36k manifest
    const specs = Array.from({ length: 50 }, (_, i) => ({
      spec: `specs/feature-${i}.md`,
      status: i % 3 === 0 ? 'passed' : i % 3 === 1 ? 'failed' : 'pending',
      runs: Array.from({ length: 3 }, (_, j) => ({
        runId: `run-${i}-${j}`,
        timestamp: `2026-0${(j + 1)}-01T00:00:00Z`,
        resultPath: `.forge/results/run-${i}-${j}`,
        status: j === 2 ? 'passed' : 'failed',
        costUsd: 0.5 + Math.random(),
        durationSeconds: 30 + Math.random() * 90,
      })),
      source: 'file',
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    }));
    const manifest = JSON.stringify({ version: 1, specs });

    const manifestPath = join(forgeDir, 'specs.json');
    await writeFile(manifestPath, manifest);

    // Measure parse time
    const start = performance.now();
    const raw = await readFile(manifestPath, 'utf-8');
    JSON.parse(raw);
    const elapsed = performance.now() - start;

    // Parse should be well under 16ms for 36k JSON
    expect(elapsed).toBeLessThan(100); // generous bound; typically <5ms
  });

  test('session scan time for moderate session count', async () => {
    const sessionsDir = join(testDir, '.forge', 'sessions');
    const resultsDir = join(testDir, '.forge', 'results');
    await mkdir(sessionsDir, { recursive: true });
    await mkdir(resultsDir, { recursive: true });

    // Create 20 sessions
    for (let i = 0; i < 20; i++) {
      const sid = `sess-${String(i).padStart(3, '0')}`;
      await mkdir(join(sessionsDir, sid), { recursive: true });
      await writeFile(join(sessionsDir, sid, 'events.jsonl'), '{}');
    }
    // Create 20 results
    for (let i = 0; i < 20; i++) {
      const ts = `2026-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`;
      await mkdir(join(resultsDir, ts), { recursive: true });
      await writeFile(join(resultsDir, ts, 'summary.json'), JSON.stringify({ status: 'success' }));
    }

    // Measure scan time
    const start = performance.now();
    const [sessionDirs, resultDirs] = await Promise.all([
      import('fs/promises').then(f => f.readdir(sessionsDir)),
      import('fs/promises').then(f => f.readdir(resultsDir)),
    ]);
    const elapsed = performance.now() - start;

    expect(sessionDirs).toHaveLength(20);
    expect(resultDirs).toHaveLength(20);
    // Directory scan should be fast
    expect(elapsed).toBeLessThan(500); // generous bound
  });

  test('debounce interval validation: 50-100ms debounce keeps UI responsive', () => {
    // The chosen debounce interval should be >= 50ms (avoid excessive redraws)
    // and <= 100ms (keep updates feeling responsive)
    const debounceMs = 100; // default from file-watcher.ts
    expect(debounceMs).toBeGreaterThanOrEqual(50);
    expect(debounceMs).toBeLessThanOrEqual(200);
  });

  test('fallback polling interval: 10-30s as safety net', () => {
    const fallbackMs = 15000; // default from file-watcher.ts
    expect(fallbackMs).toBeGreaterThanOrEqual(10000);
    expect(fallbackMs).toBeLessThanOrEqual(30000);
  });
});
