// Generated by forge proof from execution-mode-isolate.md
import { describe, test, expect, beforeAll, afterAll, beforeEach, afterEach, mock, spyOn } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import type { ForgeResult, SpecManifest } from './types.js';
import { ForgeError } from './utils.js';
import { getDb, insertRun, closeDb, getWorktreesByWorkGroup, listWorktrees, getWorktreeByPath } from './db.js';
import type { RunRow } from './db.js';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';

// ── Mock boundary: runSingleSpec ─────────────────────────────

const mockRunCalls: Array<{ specPath: string; cwd?: string; _resultDir?: string }> = [];
let mockRunBehavior: 'success' | 'fail' | ((opts: any) => ForgeResult | Promise<ForgeResult>) = 'success';

mock.module('./run.js', () => ({
  runSingleSpec: async (opts: any): Promise<ForgeResult> => {
    mockRunCalls.push({ specPath: opts.specPath, cwd: opts.cwd, _resultDir: opts._resultDir });

    if (typeof mockRunBehavior === 'function') {
      return mockRunBehavior(opts);
    }

    if (mockRunBehavior === 'fail') {
      const result: ForgeResult = {
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        durationSeconds: 1,
        status: 'error_execution',
        costUsd: 0.25,
        prompt: opts.prompt || 'test',
        model: 'sonnet',
        cwd: opts.cwd || '/tmp',
      };
      throw new ForgeError('Mock verification failure', result);
    }

    return {
      startedAt: new Date().toISOString(),
      completedAt: new Date().toISOString(),
      durationSeconds: 1,
      status: 'success',
      costUsd: 0.50,
      prompt: opts.prompt || 'test',
      model: 'sonnet',
      cwd: opts.cwd || '/tmp',
    };
  },
}));

import { autoDetectConcurrency, runSpecBatch, printBatchSummary, runForge } from './parallel.js';
import { withSpecTransaction, findOrCreateEntry, loadManifest, specKey } from './specs.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];
const execAsync = promisify(exec);

beforeAll(() => { setupHermeticGit(); });
afterAll(() => { teardownHermeticGit(); });

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-isolate-test-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

async function setupForge(dir: string): Promise<void> {
  await fs.mkdir(path.join(dir, '.forge'), { recursive: true });
}

async function makeGitRepo(): Promise<string> {
  const dir = await makeTmpDir();
  await execAsync('git init', { cwd: dir });
  await execAsync('git config user.email "test@forge.dev"', { cwd: dir });
  await execAsync('git config user.name "Forge Test"', { cwd: dir });
  await fs.writeFile(path.join(dir, 'README.md'), '# Test\n');
  await execAsync('git add README.md && git commit -m "initial commit"', { cwd: dir });
  await setupForge(dir);
  return dir;
}

async function writeSpec(dir: string, relPath: string, content = '# Spec'): Promise<string> {
  const full = path.join(dir, relPath);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, content);
  return full;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    closeDb(d);
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
  mockRunCalls.length = 0;
  mockRunBehavior = 'success';
});

// ── autoDetectConcurrency ────────────────────────────────────

describe('autoDetectConcurrency', () => {
  test('returns at least 1', () => {
    const result = autoDetectConcurrency();
    expect(result).toBeGreaterThanOrEqual(1);
  });

  test('returns at most 5 (CPU cap)', () => {
    const result = autoDetectConcurrency();
    expect(result).toBeLessThanOrEqual(5);
  });

  test('returns a whole number', () => {
    const result = autoDetectConcurrency();
    expect(Number.isInteger(result)).toBe(true);
  });
});

// ── --isolate flag acceptance via runSpecBatch ────────────────

describe('isolate mode batch execution', () => {
  test('sequential batch runs all specs and persists manifest entries', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);
    await writeSpec(dir, 'specs/a.md', '# A');
    await writeSpec(dir, 'specs/b.md', '# B');

    const specPaths = ['a.md', 'b.md'].map(f => path.join(dir, 'specs', f));
    const specNames = ['a.md', 'b.md'];

    const { results } = await runSpecBatch(
      specPaths,
      specNames,
      { prompt: 'test', sequential: true, quiet: true, cwd: dir },
      1,
      'test-isolate-1',
    );

    expect(results).toHaveLength(2);
    expect(results.every(r => r.status === 'success')).toBe(true);

    const manifest = await loadManifest(dir);
    expect(manifest.specs).toHaveLength(2);
  });

  test('parallel batch respects concurrency parameter', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);
    await writeSpec(dir, 'specs/a.md', '# A');
    await writeSpec(dir, 'specs/b.md', '# B');
    await writeSpec(dir, 'specs/c.md', '# C');

    const specPaths = ['a.md', 'b.md', 'c.md'].map(f => path.join(dir, 'specs', f));

    const { results } = await runSpecBatch(
      specPaths,
      ['a.md', 'b.md', 'c.md'],
      { prompt: 'test', sequential: false, quiet: true, cwd: dir },
      2,
      'test-isolate-conc',
    );

    expect(results).toHaveLength(3);
    expect(mockRunCalls).toHaveLength(3);
  });
});

// ── Batch result shape ──────────────────────────────────────

describe('batch result includes per-spec details', () => {
  test('each result has spec name, status, cost, and duration', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);
    await writeSpec(dir, 'specs/x.md', '# X');

    const specPaths = [path.join(dir, 'specs', 'x.md')];

    const { results } = await runSpecBatch(
      specPaths,
      ['x.md'],
      { prompt: 'test', sequential: true, quiet: true, cwd: dir },
      1,
      'test-result-shape',
    );

    expect(results).toHaveLength(1);
    expect(results[0].spec).toBe('x.md');
    expect(results[0].status).toBe('success');
    expect(results[0].cost).toBe(0.50);
    expect(typeof results[0].duration).toBe('number');
    expect(results[0].duration).toBeGreaterThanOrEqual(0);
  });

  test('failed spec result includes error message', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);
    await writeSpec(dir, 'specs/fail.md', '# Fail');

    mockRunBehavior = 'fail';

    const specPaths = [path.join(dir, 'specs', 'fail.md')];

    const { results } = await runSpecBatch(
      specPaths,
      ['fail.md'],
      { prompt: 'test', sequential: true, quiet: true, cwd: dir },
      1,
      'test-fail-result',
    );

    expect(results).toHaveLength(1);
    expect(results[0].status).toContain('failed');
    expect(results[0].cost).toBe(0.25);
  });
});

// ── printBatchSummary with worktree path ─────────────────────

describe('printBatchSummary worktree info', () => {
  test('shows worktree path when provided', () => {
    const logs: string[] = [];
    const spy = spyOn(console, 'log').mockImplementation((...args: any[]) => {
      logs.push(args.join(' '));
    });

    const results = [
      { spec: 'a.md', status: 'success', cost: 0.5, duration: 10 },
    ];

    printBatchSummary(results, 10, false, false, 'specs/', false, '/tmp/worktree-path');

    const output = logs.join('\n');
    expect(output).toContain('/tmp/worktree-path');
    expect(output).toContain('Worktree:');

    spy.mockRestore();
  });

  test('omits worktree line when path not provided', () => {
    const logs: string[] = [];
    const spy = spyOn(console, 'log').mockImplementation((...args: any[]) => {
      logs.push(args.join(' '));
    });

    const results = [
      { spec: 'a.md', status: 'success', cost: 0.5, duration: 10 },
    ];

    printBatchSummary(results, 10, false, false, 'specs/');

    const output = logs.join('\n');
    expect(output).not.toContain('Worktree:');

    spy.mockRestore();
  });
});

// ── Dependency-aware isolate consolidation ──────────────────

describe('dependency-aware isolate consolidation', () => {
  test('dependent specs start from the consolidated parent state', async () => {
    const dir = await makeGitRepo();
    await writeSpec(dir, 'specs/a.md', `# A

## Acceptance Criteria

- Create a.txt
`);
    await writeSpec(dir, 'specs/b.md', `# B

## Acceptance Criteria

- Create b.txt
`);
    await writeSpec(dir, 'specs/dependent.md', `---
depends: [a.md, b.md]
---

# Dependent

## Acceptance Criteria

- See a.txt and b.txt before creating dependent.txt
`);

    mockRunBehavior = async (opts: any): Promise<ForgeResult> => {
      const specName = path.basename(opts.specPath);
      if (specName === 'a.md') {
        await fs.writeFile(path.join(opts.cwd, 'a.txt'), 'A\n');
      } else if (specName === 'b.md') {
        await fs.writeFile(path.join(opts.cwd, 'b.txt'), 'B\n');
      } else if (specName === 'dependent.md') {
        await fs.access(path.join(opts.cwd, 'a.txt'));
        await fs.access(path.join(opts.cwd, 'b.txt'));
        await fs.writeFile(path.join(opts.cwd, 'dependent.txt'), 'D\n');
      }

      return {
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        durationSeconds: 1,
        status: 'success',
        costUsd: 0.5,
        prompt: opts.prompt || 'test',
        model: 'sonnet',
        cwd: opts.cwd,
      };
    };

    const outcome = await runForge({
      prompt: 'test consolidation',
      specDir: path.join(dir, 'specs'),
      cwd: dir,
      isolate: true,
      force: true,
      quiet: true,
    });

    expect(outcome.allPassed).toBe(true);

    const { stdout: aShow } = await execAsync('git show forge/a:a.txt', { cwd: dir });
    const { stdout: bShow } = await execAsync('git show forge/b:b.txt', { cwd: dir });
    const { stdout: mergeShow } = await execAsync('git show forge/dependent:a.txt && git show forge/dependent:b.txt', { cwd: dir });

    expect(aShow).toBe('A\n');
    expect(bShow).toBe('B\n');
    expect(mergeShow).toContain('A\n');
    expect(mergeShow).toContain('B\n');
  });

  test('isolate batches fail when a successful spec leaves uncommitted changes', async () => {
    const dir = await makeGitRepo();
    const hooksDir = path.join(dir, '.hooks');
    await fs.mkdir(hooksDir, { recursive: true });
    await fs.writeFile(path.join(hooksDir, 'pre-commit'), '#!/bin/sh\nexit 1\n');
    await fs.chmod(path.join(hooksDir, 'pre-commit'), 0o755);
    await execAsync(`git config core.hooksPath "${hooksDir}"`, { cwd: dir });

    await writeSpec(dir, 'specs/a.md', '# A');

    mockRunBehavior = async (opts: any): Promise<ForgeResult> => {
      await fs.writeFile(path.join(opts.cwd, 'a.txt'), 'A\n');
      return {
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        durationSeconds: 1,
        status: 'success',
        costUsd: 0.5,
        prompt: opts.prompt || 'test',
        model: 'sonnet',
        cwd: opts.cwd,
      };
    };

    await expect(runForge({
      prompt: 'test commit failure',
      specDir: path.join(dir, 'specs'),
      cwd: dir,
      isolate: true,
      force: true,
      quiet: true,
    })).rejects.toThrow('One or more specs failed');
  });
});
