// Generated by forge proof from mcp-worktree-tools.md, executor-worktree-creation.md
import { describe, test, expect, beforeEach } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  getWorktreesByWorkGroup,
  listWorktrees,
  updateWorktreeStatus,
  updateWorktreePid,
  linkWorktreeTask,
  linkWorktreeSession,
  insertTask,
  getTaskById,
  updateTaskParams,
} from './db.js';
import type { Database } from 'bun:sqlite';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = `wt-mcp-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
  insertWorktree(db, {
    id,
    spec_path: 'specs/test.md',
    branch: 'forge/test',
    worktree_path: '/tmp/project-test',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── forge_worktrees MCP tool ─────────────────────────────────

describe('forge_worktrees data layer', () => {
  test('lists all worktrees with status, spec, branch, path', () => {
    insertTestWorktree({
      spec_path: 'auth.md',
      branch: 'forge/auth',
      worktree_path: '/tmp/auth',
      status: 'running' as any,
    });
    insertTestWorktree({
      spec_path: 'api.md',
      branch: 'forge/api',
      worktree_path: '/tmp/api',
      status: 'complete' as any,
    });

    const all = listWorktrees(db);
    expect(all).toHaveLength(2);

    const running = all.find(w => w.spec_path === 'auth.md');
    expect(running!.status).toBe('running');
    expect(running!.branch).toBe('forge/auth');
  });

  test('filters by work_group_id', () => {
    insertTestWorktree({ work_group_id: 'wg-mcp-A', branch: 'forge/a', worktree_path: '/tmp/a' });
    insertTestWorktree({ work_group_id: 'wg-mcp-B', branch: 'forge/b', worktree_path: '/tmp/b' });

    const groupA = getWorktreesByWorkGroup(db, 'wg-mcp-A');
    expect(groupA).toHaveLength(1);
  });

  test('filters by status', () => {
    insertTestWorktree({ status: 'running' as any, branch: 'forge/r', worktree_path: '/tmp/r' });
    insertTestWorktree({ status: 'complete' as any, branch: 'forge/c', worktree_path: '/tmp/c' });

    const running = listWorktrees(db, 'running');
    expect(running).toHaveLength(1);
  });
});

// ── forge_start with worktree_id ─────────────────────────────

describe('forge_start worktree context', () => {
  test('task params can store worktree intent', () => {
    insertTask(db, {
      id: 'task-wt-intent',
      command: 'run',
      description: 'run auth spec',
      status: 'pending',
      cwd: '/dev/project',
      params: { worktree: true, spec_path: 'auth.md' },
    });

    const task = getTaskById(db, 'task-wt-intent');
    const params = JSON.parse(task!.params);
    expect(params.worktree).toBe(true);
    expect(params.spec_path).toBe('auth.md');
  });

  test('task params can store worktree_id for existing worktree', () => {
    const wtId = insertTestWorktree({ worktree_path: '/tmp/existing-wt' });

    insertTask(db, {
      id: 'task-wt-id',
      command: 'run',
      status: 'pending',
      cwd: '/dev/project',
      params: { worktree_id: wtId },
    });

    const task = getTaskById(db, 'task-wt-id');
    const params = JSON.parse(task!.params);
    expect(params.worktree_id).toBe(wtId);
  });

  test('task params can store isolate flag', () => {
    insertTask(db, {
      id: 'task-isolate',
      command: 'run',
      status: 'pending',
      cwd: '/dev/project',
      params: { isolate: true, spec_dir: 'specs/' },
    });

    const task = getTaskById(db, 'task-isolate');
    const params = JSON.parse(task!.params);
    expect(params.isolate).toBe(true);
  });
});

// ── Executor worktree creation ──────────────────────────────

describe('executor worktree lifecycle', () => {
  test('executor stores worktree path in task params after creation', () => {
    const taskId = 'task-exec-wt';
    insertTask(db, {
      id: taskId,
      command: 'run',
      status: 'running',
      cwd: '/dev/project',
      params: { worktree: true },
    });

    // Simulate executor updating params with worktree path
    updateTaskParams(db, taskId, {
      worktree: true,
      worktree_path: '/dev/project-auth-login',
    });

    const task = getTaskById(db, taskId);
    const params = JSON.parse(task!.params);
    expect(params.worktree_path).toBe('/dev/project-auth-login');
  });

  test('executor links worktree to task and sets PID', () => {
    const wtId = insertTestWorktree();

    linkWorktreeTask(db, wtId, 'task-linked');
    updateWorktreePid(db, wtId, 12345);

    const wt = getWorktree(db, wtId);
    expect(wt!.task_id).toBe('task-linked');
    expect(wt!.pid).toBe(12345);
  });

  test('executor links session to worktree after SDK starts', () => {
    const wtId = insertTestWorktree();

    linkWorktreeSession(db, wtId, 'sess-abc');

    const wt = getWorktree(db, wtId);
    expect(wt!.session_id).toBe('sess-abc');
  });

  test('executor transitions worktree status on task completion', () => {
    const wtId = insertTestWorktree({ status: 'created' });

    updateWorktreeStatus(db, wtId, 'running');
    expect(getWorktree(db, wtId)!.status).toBe('running');

    updateWorktreeStatus(db, wtId, 'complete');
    expect(getWorktree(db, wtId)!.status).toBe('complete');
  });

  test('executor marks worktree as failed on task failure', () => {
    const wtId = insertTestWorktree({ status: 'created' });
    updateWorktreeStatus(db, wtId, 'running');
    updateWorktreeStatus(db, wtId, 'failed', 'Build error: type check failed');

    const wt = getWorktree(db, wtId);
    expect(wt!.status).toBe('failed');
    expect(wt!.error).toBe('Build error: type check failed');
  });

  test('worktree creation failure marks task as failed', () => {
    // Simulate: task is pending, executor tries to create worktree and fails
    insertTask(db, {
      id: 'task-wt-fail',
      command: 'run',
      status: 'running',
      cwd: '/dev/project',
      params: { worktree: true },
    });

    // Executor would mark the task as failed
    db.run("UPDATE tasks SET status = 'failed', updatedAt = datetime('now') WHERE id = 'task-wt-fail'");

    const task = getTaskById(db, 'task-wt-fail');
    expect(task!.status).toBe('failed');
  });
});

// ── forge_task worktree enrichment ──────────────────────────

describe('forge_task worktree enrichment', () => {
  test('task with associated worktree provides worktree metadata', () => {
    const wtId = insertTestWorktree({
      worktree_path: '/dev/project-enriched',
      status: 'running' as any,
    });

    linkWorktreeTask(db, wtId, 'task-enriched');

    const wt = getWorktree(db, wtId);
    expect(wt!.task_id).toBe('task-enriched');
    expect(wt!.worktree_path).toBe('/dev/project-enriched');
    expect(wt!.status).toBe('running');
  });
});
