// Generated by forge proof from monorepo-worktree-support.md
import { describe, test, expect, beforeAll, afterAll, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';
import { parseScope, parseDependencies } from './deps.js';
import { detectSetupCommands, detectScopedSetupCommands, setupWorktree } from './workspace.js';
import type { WorkspaceLifecycleOptions } from './workspace.js';
import { detectVerification } from './verify.js';

// ── Hermetic Git ─────────────────────────────────────────────

beforeAll(() => { setupHermeticGit(); });
afterAll(() => { teardownHermeticGit(); });

// ── Helpers ──────────────────────────────────────────────────

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-monorepo-test-'));
});

afterEach(async () => {
  await fs.rm(tmpDir, { recursive: true, force: true });
});

// ── Spec frontmatter scope parsing ──────────────────────────

describe('monorepo: spec frontmatter scope parsing', () => {
  test('parseScope extracts scope from frontmatter', () => {
    const content = `---
scope: packages/api
depends: [base.md]
---

# API feature`;
    expect(parseScope(content)).toBe('packages/api');
  });

  test('parseScope normalizes leading/trailing slashes', () => {
    const content = `---
scope: /packages/api/
---

# Feature`;
    expect(parseScope(content)).toBe('packages/api');
  });

  test('parseScope returns undefined when no scope field', () => {
    const content = `---
depends: [base.md]
---

# Feature`;
    expect(parseScope(content)).toBeUndefined();
  });

  test('parseScope returns undefined when no frontmatter', () => {
    const content = `# Feature without frontmatter`;
    expect(parseScope(content)).toBeUndefined();
  });

  test('parseScope handles apps directory', () => {
    const content = `---
scope: apps/web
---

# Web feature`;
    expect(parseScope(content)).toBe('apps/web');
  });

  test('parseScope handles nested package paths', () => {
    const content = `---
scope: packages/shared/utils
---

# Utils feature`;
    expect(parseScope(content)).toBe('packages/shared/utils');
  });
});

// ── Workspace setup: root-level install ─────────────────────

describe('monorepo: root-level setup detection', () => {
  test('detects bun install when bun.lockb exists', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('bun install');
  });

  test('detects pnpm install when pnpm-lock.yaml exists', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'pnpm-lock.yaml'), '');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('pnpm install');
  });

  test('detects npm install when package-lock.json exists', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'package-lock.json'), '{}');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('npm install');
  });

  test('detects yarn install when yarn.lock exists', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'yarn.lock'), '');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('yarn install');
  });
});

// ── Scoped setup: package-level build ───────────────────────

describe('monorepo: scoped setup detection', () => {
  test('detects package-level build script', async () => {
    // Create root with bun lockfile
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    // Create scoped package with build script
    const pkgDir = path.join(tmpDir, 'packages', 'api');
    await fs.mkdir(pkgDir, { recursive: true });
    await fs.writeFile(path.join(pkgDir, 'package.json'), JSON.stringify({
      name: '@test/api',
      scripts: { build: 'tsc -b' },
    }));

    const result = await detectScopedSetupCommands(tmpDir, 'packages/api');
    expect(result.commands.length).toBeGreaterThanOrEqual(1);
    expect(result.commands.some(c => c.includes('run build'))).toBe(true);
    expect(result.cwd).toBe(pkgDir);
  });

  test('returns empty commands when no package.json in scope', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    const pkgDir = path.join(tmpDir, 'packages', 'missing');
    await fs.mkdir(pkgDir, { recursive: true });
    // No package.json in scoped dir

    const result = await detectScopedSetupCommands(tmpDir, 'packages/missing');
    expect(result.commands.length).toBe(0);
  });

  test('returns empty when package.json has no build script', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const pkgDir = path.join(tmpDir, 'packages', 'no-build');
    await fs.mkdir(pkgDir, { recursive: true });
    await fs.writeFile(path.join(pkgDir, 'package.json'), JSON.stringify({
      name: '@test/no-build',
      scripts: { test: 'vitest' },
    }));

    const result = await detectScopedSetupCommands(tmpDir, 'packages/no-build');
    // Should not include a build command
    expect(result.commands.filter(c => c.includes('build'))).toHaveLength(0);
  });

  test('detects Cargo.toml in scoped directory', async () => {
    const pkgDir = path.join(tmpDir, 'packages', 'rust-service');
    await fs.mkdir(pkgDir, { recursive: true });
    await fs.writeFile(path.join(pkgDir, 'Cargo.toml'), '[package]\nname = "test"');

    const result = await detectScopedSetupCommands(tmpDir, 'packages/rust-service');
    expect(result.commands).toContain('cargo build');
  });
});

// ── Verification scoping ────────────────────────────────────

describe('monorepo: verification scoping', () => {
  test('detectVerification finds TypeScript commands at project root', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), JSON.stringify({
      scripts: { build: 'tsc' },
      devDependencies: { typescript: '^5.0.0' },
    }));
    await fs.writeFile(path.join(tmpDir, 'tsconfig.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const commands = await detectVerification(tmpDir);
    expect(commands.some(c => c.includes('tsc --noEmit'))).toBe(true);
  });

  test('no verification commands for empty directory', async () => {
    const emptyDir = path.join(tmpDir, 'empty');
    await fs.mkdir(emptyDir, { recursive: true });

    const commands = await detectVerification(emptyDir);
    expect(commands.length).toBe(0);
  });

  test('detectVerification finds Go commands', async () => {
    await fs.writeFile(path.join(tmpDir, 'go.mod'), 'module test\n\ngo 1.21');

    const commands = await detectVerification(tmpDir);
    expect(commands.some(c => c.includes('go build'))).toBe(true);
    expect(commands.some(c => c.includes('go test'))).toBe(true);
  });

  test('detectVerification finds Cargo commands', async () => {
    await fs.writeFile(path.join(tmpDir, 'Cargo.toml'), '[package]\nname = "test"\nversion = "0.1.0"');

    const commands = await detectVerification(tmpDir);
    expect(commands.some(c => c.includes('cargo'))).toBe(true);
  });
});

// ── Scope integration with spec frontmatter ─────────────────

describe('monorepo: scope from spec content used in merge', () => {
  test('parseScope provides scope for package-scoped type-check', () => {
    const specContent = `---
scope: packages/api
depends: [auth-base.md]
---

# API endpoints
## Acceptance Criteria
- Implements REST endpoints
`;

    const scope = parseScope(specContent);
    expect(scope).toBe('packages/api');

    // This scope would be passed to runIncrementalTypeCheck(workingDir, quiet, scope)
    // in the real consolidation flow
  });

  test('spec without scope defaults to repo-root verification', () => {
    const specContent = `---
depends: [base.md]
---

# Root-level feature`;

    const scope = parseScope(specContent);
    expect(scope).toBeUndefined();
    // When scope is undefined, detectVerification() runs at root -- existing behavior
  });
});

// ── Non-overlapping package merges ──────────────────────────

describe('monorepo: non-overlapping package directories', () => {
  test('different packages target different directories (reducing conflicts)', () => {
    const pkgA = 'packages/api';
    const pkgB = 'packages/web';

    // Different packages should have non-overlapping paths
    expect(pkgA.startsWith(pkgB)).toBe(false);
    expect(pkgB.startsWith(pkgA)).toBe(false);
  });

  test('scope field correctly identifies target package', () => {
    const scopes = [
      { spec: 'api-auth.md', scope: 'packages/api' },
      { spec: 'web-ui.md', scope: 'packages/web' },
      { spec: 'shared-types.md', scope: 'packages/shared' },
    ];

    const uniqueDirs = new Set(scopes.map(s => s.scope));
    expect(uniqueDirs.size).toBe(3);
  });
});
