// Generated by forge proof from proof-batch-generation.md
import { describe, test, expect, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import type { ProofManifest, ProofManifestEntry } from './types.js';
import { detectTestConvention } from './proof.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-proof-batch-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
});

function makeManifest(overrides: Partial<ProofManifest> = {}): ProofManifest {
  return {
    generatedAt: '2026-01-01T00:00:00Z',
    specDir: 'specs/',
    entries: [],
    manualCheckCount: 0,
    ...overrides,
  };
}

function makeEntry(overrides: Partial<ProofManifestEntry> = {}): ProofManifestEntry {
  return {
    specFile: 'feature.md',
    category: 'unit',
    testFile: 'src/feature.test.ts',
    description: 'Test feature implementation',
    ...overrides,
  };
}

async function writeManifest(dir: string, manifest: ProofManifest): Promise<string> {
  const outputDir = path.join(dir, '.forge', 'proofs');
  await fs.mkdir(outputDir, { recursive: true });
  const manifestPath = path.join(outputDir, 'manifest.json');
  await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2));
  return manifestPath;
}

// ── ProofManifest structure ─────────────────────────────────

describe('proof batch: ProofManifest structure', () => {
  test('manifest has generatedAt ISO timestamp', () => {
    const manifest = makeManifest({ generatedAt: '2026-03-11T10:00:00.000Z' });
    expect(manifest.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  test('manifest has specDir path', () => {
    const manifest = makeManifest({ specDir: 'specs/auth/' });
    expect(manifest.specDir).toBe('specs/auth/');
  });

  test('manifest entries array holds ProofManifestEntry items', () => {
    const entries: ProofManifestEntry[] = [
      makeEntry({ specFile: 'auth.md', testFile: 'src/auth.test.ts' }),
      makeEntry({ specFile: 'db.md', testFile: 'src/db.test.ts' }),
    ];
    const manifest = makeManifest({ entries });
    expect(manifest.entries).toHaveLength(2);
    expect(manifest.entries[0].specFile).toBe('auth.md');
    expect(manifest.entries[1].specFile).toBe('db.md');
  });

  test('manualCheckCount reflects manual.md steps', () => {
    const manifest = makeManifest({ manualCheckCount: 5 });
    expect(manifest.manualCheckCount).toBe(5);
  });

  test('entry has specFile, category, testFile, description', () => {
    const entry = makeEntry({
      specFile: 'auth/login.md',
      category: 'integration',
      testFile: 'src/auth/login.test.ts',
      description: 'Verify login flow end-to-end',
    });
    expect(entry.specFile).toBe('auth/login.md');
    expect(entry.category).toBe('integration');
    expect(entry.testFile).toBe('src/auth/login.test.ts');
    expect(entry.description).toBe('Verify login flow end-to-end');
  });

  test('category is unit or integration', () => {
    const unit = makeEntry({ category: 'unit' });
    const integration = makeEntry({ category: 'integration' });
    expect(unit.category).toBe('unit');
    expect(integration.category).toBe('integration');
  });
});

// ── Manifest file write and read roundtrip ──────────────────

describe('proof batch: manifest file roundtrip', () => {
  test('manifest.json writes and reads back correctly', async () => {
    const dir = await makeTmpDir();
    const manifest = makeManifest({
      entries: [
        makeEntry({ specFile: 'a.md', testFile: 'src/a.test.ts', category: 'unit' }),
        makeEntry({ specFile: 'b.md', testFile: 'src/b.test.ts', category: 'integration' }),
      ],
      manualCheckCount: 3,
    });
    const manifestPath = await writeManifest(dir, manifest);

    const raw = await fs.readFile(manifestPath, 'utf-8');
    const loaded: ProofManifest = JSON.parse(raw);
    expect(loaded.generatedAt).toBe(manifest.generatedAt);
    expect(loaded.specDir).toBe(manifest.specDir);
    expect(loaded.entries).toHaveLength(2);
    expect(loaded.manualCheckCount).toBe(3);
  });

  test('manifest.json is valid JSON', async () => {
    const dir = await makeTmpDir();
    const manifest = makeManifest({ entries: [makeEntry()] });
    const manifestPath = await writeManifest(dir, manifest);

    const raw = await fs.readFile(manifestPath, 'utf-8');
    expect(() => JSON.parse(raw)).not.toThrow();
  });

  test('manifest lives at <outputDir>/manifest.json', async () => {
    const dir = await makeTmpDir();
    const manifest = makeManifest();
    const manifestPath = await writeManifest(dir, manifest);
    expect(manifestPath).toContain(path.join('.forge', 'proofs', 'manifest.json'));
  });
});

// ── Test convention detection ───────────────────────────────

describe('proof batch: detectTestConvention', () => {
  test('detects colocated convention when src/ has test files', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'core.ts'), 'export function core() {}');
    await fs.writeFile(path.join(srcDir, 'core.test.ts'), 'test("core", () => {})');
    await fs.writeFile(path.join(srcDir, 'utils.ts'), 'export function utils() {}');
    await fs.writeFile(path.join(srcDir, 'utils.test.ts'), 'test("utils", () => {})');

    const convention = await detectTestConvention(dir);
    expect(convention.style).toBe('colocated');
  });

  test('detects separate convention when tests/ directory exists', async () => {
    const dir = await makeTmpDir();
    await fs.mkdir(path.join(dir, 'src'), { recursive: true });
    await fs.writeFile(path.join(dir, 'src', 'core.ts'), 'export function core() {}');
    const testsDir = path.join(dir, 'tests');
    await fs.mkdir(testsDir, { recursive: true });
    await fs.writeFile(path.join(testsDir, 'core.test.ts'), 'test("core", () => {})');
    await fs.writeFile(path.join(testsDir, 'utils.test.ts'), 'test("utils", () => {})');

    const convention = await detectTestConvention(dir);
    expect(convention.style).toBe('separate');
  });

  test('defaults to colocated when no test files found', async () => {
    const dir = await makeTmpDir();
    await fs.mkdir(path.join(dir, 'src'), { recursive: true });
    await fs.writeFile(path.join(dir, 'src', 'core.ts'), 'export function core() {}');

    const convention = await detectTestConvention(dir);
    expect(convention.style).toBe('colocated');
  });

  test('returns examples of existing test files', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'one.test.ts'), 'test(1)');
    await fs.writeFile(path.join(srcDir, 'two.test.ts'), 'test(2)');
    await fs.writeFile(path.join(srcDir, 'three.test.ts'), 'test(3)');

    const convention = await detectTestConvention(dir);
    expect(convention.examples.length).toBeGreaterThanOrEqual(1);
  });
});

// ── Output directory layout ─────────────────────────────────

describe('proof batch: output directory layout', () => {
  test('manual.md created alongside manifest.json', async () => {
    const dir = await makeTmpDir();
    const outputDir = path.join(dir, '.forge', 'proofs');
    await fs.mkdir(outputDir, { recursive: true });
    await fs.writeFile(path.join(outputDir, 'manifest.json'), JSON.stringify(makeManifest()));
    await fs.writeFile(path.join(outputDir, 'manual.md'), '# Manual Steps\n- [ ] Visual check');

    const manifestExists = await fs.access(path.join(outputDir, 'manifest.json')).then(() => true).catch(() => false);
    const manualExists = await fs.access(path.join(outputDir, 'manual.md')).then(() => true).catch(() => false);
    expect(manifestExists).toBe(true);
    expect(manualExists).toBe(true);
  });

  test('test files referenced in manifest can be absolute or relative', () => {
    const absEntry = makeEntry({ testFile: '/Users/dev/forge/src/core.test.ts' });
    const relEntry = makeEntry({ testFile: 'src/core.test.ts' });
    expect(path.isAbsolute(absEntry.testFile)).toBe(true);
    expect(path.isAbsolute(relEntry.testFile)).toBe(false);
  });
});

// ── Single-spec mode ────────────────────────────────────────

describe('proof batch: single-spec mode', () => {
  test('single spec produces valid manifest with one entry', () => {
    const manifest = makeManifest({
      specDir: 'specs/',
      entries: [
        makeEntry({ specFile: 'single-feature.md', testFile: 'src/single-feature.test.ts' }),
      ],
      manualCheckCount: 0,
    });
    expect(manifest.entries).toHaveLength(1);
    expect(manifest.entries[0].specFile).toBe('single-feature.md');
  });
});
