// Generated by forge proof from verify-proof-parser.md, verify-run-checks.md, verify-pr-creation.md
import { describe, test, expect, afterEach, beforeEach, spyOn } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { readProofManifest, detectTestRunner, buildPRBody, createVerifyPR, runVerify } from './proof-runner.js';
import type { VerifyOptions, VerifyResult, ProofManifest, ProofManifestEntry, ForgeResult } from './types.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-verify-test-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
  // Reset process.exitCode after tests that set it
  process.exitCode = 0;
});

function makeManifest(overrides: Partial<ProofManifest> = {}): ProofManifest {
  return {
    generatedAt: new Date().toISOString(),
    specDir: 'specs/',
    entries: [
      { specFile: 'auth.md', category: 'unit', testFile: '/abs/path/auth.test.ts', description: 'Auth tests' },
    ],
    manualCheckCount: 0,
    ...overrides,
  };
}

function makeEntry(overrides: Partial<ProofManifestEntry> = {}): ProofManifestEntry {
  return {
    specFile: 'feature.md',
    category: 'unit',
    testFile: 'feature.test.ts',
    description: 'Feature tests',
    ...overrides,
  };
}

function makeResult(overrides: Partial<VerifyResult> = {}): VerifyResult {
  return {
    testFile: 'auth.test.ts',
    status: 'pass',
    exitCode: 0,
    stderr: '',
    durationSeconds: 1.5,
    ...overrides,
  };
}

async function writeManifest(dir: string, manifest: ProofManifest): Promise<void> {
  await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
}

async function writeManual(dir: string, content: string): Promise<void> {
  await fs.writeFile(path.join(dir, 'manual.md'), content);
}

/** Create a minimal bun test file that passes */
async function writePassingTest(filePath: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, `
import { test, expect } from 'bun:test';
test('passes', () => { expect(1 + 1).toBe(2); });
`);
}

/** Create a minimal bun test file that fails */
async function writeFailingTest(filePath: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, `
import { test, expect } from 'bun:test';
test('fails', () => { expect(1).toBe(2); });
`);
}

/**
 * Set up a project dir with bun.lockb so detectTestRunner returns 'bun test'.
 * Creates .forge dir structure and proof dir with manifest.
 */
async function setupProjectWithProofs(opts: {
  entries: ProofManifestEntry[];
  manualContent?: string;
}): Promise<{ cwd: string; proofDir: string }> {
  const cwd = await makeTmpDir();
  const proofDir = path.join(cwd, '.forge', 'proofs', 'test-proof');
  await fs.mkdir(proofDir, { recursive: true });

  // Make it look like a bun project
  await fs.writeFile(path.join(cwd, 'bun.lockb'), '');

  // Write manifest
  await writeManifest(proofDir, makeManifest({ entries: opts.entries }));

  // Write manual.md if content provided
  if (opts.manualContent) {
    await writeManual(proofDir, opts.manualContent);
  }

  return { cwd, proofDir };
}

// ══════════════════════════════════════════════════════════════
// verify-proof-parser.md — Types, manifest parsing, manual steps
// ══════════════════════════════════════════════════════════════

// ── readProofManifest ────────────────────────────────────────

describe('readProofManifest', () => {
  test('reads and returns valid manifest with all fields', async () => {
    const dir = await makeTmpDir();
    const manifest = makeManifest({
      entries: [
        { specFile: 'auth.md', category: 'unit', testFile: '/abs/auth.test.ts', description: 'Auth tests' },
        { specFile: 'api.md', category: 'integration', testFile: '/abs/api.test.ts', description: 'API tests' },
      ],
      manualCheckCount: 2,
    });
    await writeManifest(dir, manifest);

    const result = await readProofManifest(dir);
    expect(result.entries).toHaveLength(2);
    expect(result.entries[0].specFile).toBe('auth.md');
    expect(result.entries[0].category).toBe('unit');
    expect(result.entries[1].specFile).toBe('api.md');
    expect(result.entries[1].category).toBe('integration');
    expect(result.manualCheckCount).toBe(2);
  });

  test('throws clear error when manifest.json is missing', async () => {
    const dir = await makeTmpDir();
    await expect(readProofManifest(dir)).rejects.toThrow('manifest.json not found');
  });

  test('error message suggests forge proof when manifest missing', async () => {
    const dir = await makeTmpDir();
    try {
      await readProofManifest(dir);
      expect(true).toBe(false); // should not reach
    } catch (err) {
      expect((err as Error).message).toContain('forge proof');
    }
  });

  test('error includes the proof directory path', async () => {
    const dir = await makeTmpDir();
    try {
      await readProofManifest(dir);
      expect(true).toBe(false);
    } catch (err) {
      expect((err as Error).message).toContain(dir);
    }
  });

  test('throws when manifest.json is invalid JSON', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'manifest.json'), 'not valid json {{{');
    await expect(readProofManifest(dir)).rejects.toThrow('not valid JSON');
  });

  test('throws when manifest is missing entries array', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify({ generatedAt: 'now', specDir: '.' }));
    await expect(readProofManifest(dir)).rejects.toThrow('missing "entries" array');
  });

  test('throws when entries is not an array', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify({ entries: 'not-array' }));
    await expect(readProofManifest(dir)).rejects.toThrow('missing "entries" array');
  });

  test('throws when entries is an object', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify({ entries: { a: 1 } }));
    await expect(readProofManifest(dir)).rejects.toThrow('missing "entries" array');
  });

  test('accepts manifest with empty entries array', async () => {
    const dir = await makeTmpDir();
    await writeManifest(dir, makeManifest({ entries: [] }));
    const result = await readProofManifest(dir);
    expect(result.entries).toHaveLength(0);
  });

  test('preserves all entry fields through roundtrip', async () => {
    const dir = await makeTmpDir();
    await writeManifest(dir, makeManifest({
      entries: [{
        specFile: 'complex.md',
        category: 'integration',
        testFile: '/repo/tests/complex.test.ts',
        description: 'Complex integration tests for auth flow',
      }],
    }));

    const result = await readProofManifest(dir);
    expect(result.entries[0].specFile).toBe('complex.md');
    expect(result.entries[0].category).toBe('integration');
    expect(result.entries[0].testFile).toBe('/repo/tests/complex.test.ts');
    expect(result.entries[0].description).toBe('Complex integration tests for auth flow');
  });

  test('preserves generatedAt and specDir fields', async () => {
    const dir = await makeTmpDir();
    const ts = '2026-03-11T12:00:00.000Z';
    await writeManifest(dir, makeManifest({ generatedAt: ts, specDir: 'my-specs/' }));

    const result = await readProofManifest(dir);
    expect(result.generatedAt).toBe(ts);
    expect(result.specDir).toBe('my-specs/');
  });

  test('handles manifest with many entries', async () => {
    const dir = await makeTmpDir();
    const entries: ProofManifestEntry[] = Array.from({ length: 20 }, (_, i) =>
      makeEntry({ specFile: `spec-${i}.md`, testFile: `/abs/spec-${i}.test.ts` }),
    );
    await writeManifest(dir, makeManifest({ entries }));

    const result = await readProofManifest(dir);
    expect(result.entries).toHaveLength(20);
  });
});

// ── VerifyOptions and VerifyResult type shape at runtime ─────

describe('VerifyOptions and VerifyResult runtime usage', () => {
  test('VerifyOptions with only required field', () => {
    const opts: VerifyOptions = { proofDir: '.forge/proofs/test' };
    expect(opts.proofDir).toBe('.forge/proofs/test');
    expect(opts.dryRun).toBeUndefined();
    expect(opts.quiet).toBeUndefined();
  });

  test('VerifyOptions with all fields populated', () => {
    const opts: VerifyOptions = {
      proofDir: '.forge/proofs/test',
      outputDir: './output',
      prompt: 'test context',
      cwd: '/repo',
      model: 'sonnet',
      maxTurns: 100,
      maxBudgetUsd: 5.0,
      quiet: true,
      dryRun: true,
    };
    expect(opts.maxBudgetUsd).toBe(5.0);
    expect(opts.model).toBe('sonnet');
  });

  test('VerifyResult pass status has exitCode 0 and empty stderr', () => {
    const result = makeResult({ status: 'pass', exitCode: 0, stderr: '' });
    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe('');
    expect(result.status).toBe('pass');
  });

  test('VerifyResult fail status has non-zero exitCode and stderr content', () => {
    const result = makeResult({
      status: 'fail',
      exitCode: 1,
      stderr: 'FAIL src/auth.test.ts\n  Expected true, received false',
    });
    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain('Expected true');
  });

  test('VerifyResult skipped status with exitCode -1 for missing test file', () => {
    const result = makeResult({
      status: 'skipped',
      exitCode: -1,
      stderr: 'Test file not found: /path/to/test.ts',
    });
    expect(result.status).toBe('skipped');
    expect(result.exitCode).toBe(-1);
  });

  test('VerifyResult durationSeconds is optional', () => {
    const result = makeResult({ durationSeconds: undefined });
    expect(result.durationSeconds).toBeUndefined();
  });

  test('ForgeResult.type includes verify', () => {
    const result: Partial<ForgeResult> = { type: 'verify' };
    expect(result.type).toBe('verify');
  });
});

// ── detectTestRunner ─────────────────────────────────────────

describe('detectTestRunner', () => {
  test('detects bun from bun.lockb', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lockb'), '');
    expect(await detectTestRunner(dir)).toBe('bun test');
  });

  test('detects bun from bun.lock', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lock'), '');
    expect(await detectTestRunner(dir)).toBe('bun test');
  });

  test('detects vitest from devDependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { vitest: '^1.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('vitest run');
  });

  test('detects vitest from regular dependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ dependencies: { vitest: '^1.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('vitest run');
  });

  test('detects jest from devDependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { jest: '^29.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('npx jest');
  });

  test('detects jest from regular dependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ dependencies: { jest: '^29.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('npx jest');
  });

  test('falls back to npm test when no runner detected', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { typescript: '^5.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('npm test --');
  });

  test('falls back to npm test when no package.json', async () => {
    const dir = await makeTmpDir();
    expect(await detectTestRunner(dir)).toBe('npm test --');
  });

  test('bun lockfile takes priority over vitest in package.json', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lockb'), '');
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { vitest: '^1.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('bun test');
  });

  test('vitest takes priority over jest', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { vitest: '^1.0.0', jest: '^29.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('vitest run');
  });

  test('handles corrupt package.json gracefully', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'package.json'), 'not json {{{');
    expect(await detectTestRunner(dir)).toBe('npm test --');
  });

  test('handles package.json with empty devDependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: {} }),
    );
    expect(await detectTestRunner(dir)).toBe('npm test --');
  });
});

// ══════════════════════════════════════════════════════════════
// verify-run-checks.md — runVerify execution flow
// ══════════════════════════════════════════════════════════════

describe('runVerify', () => {
  test('throws when manifest has no entries', async () => {
    const { cwd, proofDir } = await setupProjectWithProofs({ entries: [] });

    await expect(
      runVerify({ proofDir, cwd, quiet: true }),
    ).rejects.toThrow('No test file entries');
  });

  test('throws when manifest.json is missing', async () => {
    const cwd = await makeTmpDir();
    const proofDir = path.join(cwd, '.forge', 'proofs', 'test-proof');
    await fs.mkdir(proofDir, { recursive: true });
    await fs.writeFile(path.join(cwd, 'bun.lockb'), '');

    await expect(
      runVerify({ proofDir, cwd, quiet: true }),
    ).rejects.toThrow('manifest.json not found');
  });

  test('dry-run mode does not execute tests or call SDK', async () => {
    const { cwd, proofDir } = await setupProjectWithProofs({
      entries: [
        makeEntry({ testFile: '/nonexistent/will-not-run.test.ts' }),
      ],
    });

    // In dry-run, should return without error — no SDK call, no test execution
    await runVerify({ proofDir, cwd, quiet: true, dryRun: true });
  });

  test('all exported functions are accessible', async () => {
    const mod = await import('./proof-runner.js');
    expect(typeof mod.runVerify).toBe('function');
    expect(typeof mod.readProofManifest).toBe('function');
    expect(typeof mod.detectTestRunner).toBe('function');
    expect(typeof mod.buildPRBody).toBe('function');
    expect(typeof mod.createVerifyPR).toBe('function');
  });
});

// ══════════════════════════════════════════════════════════════
// verify-pr-creation.md — PR body building and creation
// ══════════════════════════════════════════════════════════════

// ── buildPRBody ──────────────────────────────────────────────

describe('buildPRBody', () => {
  test('starts with ## Summary section', () => {
    const body = buildPRBody([makeResult()], []);
    expect(body.startsWith('## Summary')).toBe(true);
  });

  test('generates summary table with correct columns', () => {
    const body = buildPRBody([makeResult()], []);
    expect(body).toContain('| File | Status | Duration |');
    expect(body).toContain('|------|--------|----------|');
  });

  test('maps pass/fail/skipped statuses correctly', () => {
    const results: VerifyResult[] = [
      makeResult({ testFile: 'auth.test.ts', status: 'pass', durationSeconds: 1.2 }),
      makeResult({ testFile: 'api.test.ts', status: 'fail', durationSeconds: 3.5 }),
      makeResult({ testFile: 'missing.test.ts', status: 'skipped', durationSeconds: undefined }),
    ];

    const body = buildPRBody(results, []);
    expect(body).toContain('| auth.test.ts | PASS | 1.2s |');
    expect(body).toContain('| api.test.ts | FAIL | 3.5s |');
    expect(body).toContain('| missing.test.ts | SKIPPED | N/A |');
  });

  test('formats duration with one decimal place', () => {
    const body = buildPRBody([makeResult({ durationSeconds: 12.345 })], []);
    expect(body).toContain('12.3s');
  });

  test('shows N/A for undefined duration', () => {
    const body = buildPRBody([makeResult({ durationSeconds: undefined })], []);
    expect(body).toContain('N/A');
  });

  test('includes human verification section when steps provided', () => {
    const humanSteps = [
      '- Check the login page renders correctly',
      '- Verify OAuth redirect works',
    ];

    const body = buildPRBody([makeResult()], humanSteps);
    expect(body).toContain('## Human Verification');
    expect(body).toContain('- [ ] Check the login page renders correctly');
    expect(body).toContain('- [ ] Verify OAuth redirect works');
  });

  test('omits human verification section when no steps', () => {
    const body = buildPRBody([makeResult()], []);
    expect(body).not.toContain('## Human Verification');
  });

  test('strips leading dash markers from human steps', () => {
    const body = buildPRBody([makeResult()], ['- Manually check X']);
    expect(body).toContain('- [ ] Manually check X');
    expect(body).not.toContain('- [ ] - ');
  });

  test('strips leading asterisk markers from human steps', () => {
    const body = buildPRBody([makeResult()], ['* Verify Y']);
    expect(body).toContain('- [ ] Verify Y');
    expect(body).not.toContain('- [ ] * ');
  });

  test('strips numbered list markers from human steps', () => {
    const body = buildPRBody([makeResult()], ['1. Check Z']);
    expect(body).toContain('- [ ] Check Z');
    expect(body).not.toContain('- [ ] 1. ');
  });

  test('handles steps without markers', () => {
    const body = buildPRBody([makeResult()], ['Plain text step']);
    expect(body).toContain('- [ ] Plain text step');
  });

  test('handles empty results array', () => {
    const body = buildPRBody([], []);
    expect(body).toContain('## Summary');
    expect(body).toContain('| File | Status | Duration |');
  });

  test('result body is trimmed (no trailing whitespace)', () => {
    const body = buildPRBody([makeResult()], []);
    expect(body).toBe(body.trimEnd());
  });

  test('one table row per test file', () => {
    const results = [
      makeResult({ testFile: 'a.test.ts' }),
      makeResult({ testFile: 'b.test.ts' }),
      makeResult({ testFile: 'c.test.ts' }),
    ];
    const body = buildPRBody(results, []);
    // Count data rows (exclude header and separator)
    const tableRows = body.split('\n').filter(l =>
      l.startsWith('| ') && !l.startsWith('| File') && !l.startsWith('|---'),
    );
    expect(tableRows).toHaveLength(3);
  });

  test('handles many human steps', () => {
    const steps = Array.from({ length: 20 }, (_, i) => `- Step ${i + 1}`);
    const body = buildPRBody([makeResult()], steps);
    expect(body).toContain('## Human Verification');
    // All 20 steps should be present
    for (let i = 1; i <= 20; i++) {
      expect(body).toContain(`- [ ] Step ${i}`);
    }
  });
});

// ── createVerifyPR ───────────────────────────────────────────

describe('createVerifyPR', () => {
  test('skips silently when no results', async () => {
    const dir = await makeTmpDir();
    // Should not throw, just return silently
    await createVerifyPR(dir, [], [], dir, { quiet: true });
  });

  test('skips PR when any test fails and sets exitCode to 1', async () => {
    const dir = await makeTmpDir();
    const results = [
      makeResult({ status: 'pass' }),
      makeResult({ testFile: 'fail.test.ts', status: 'fail', exitCode: 1, stderr: 'assertion error' }),
    ];

    await createVerifyPR(dir, results, [], dir, { quiet: true });
    expect(process.exitCode).toBe(1);
  });

  test('skips PR when all tests fail', async () => {
    const dir = await makeTmpDir();
    const results = [
      makeResult({ status: 'fail', exitCode: 1 }),
      makeResult({ testFile: 'b.test.ts', status: 'fail', exitCode: 1 }),
    ];

    await createVerifyPR(dir, results, [], dir, { quiet: true });
    expect(process.exitCode).toBe(1);
  });

  test('does not set exitCode when all tests pass', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];

    // This will try to call gh and fail (not in git repo), but should handle gracefully
    await createVerifyPR(dir, results, [], dir, { quiet: true });
    // exitCode should not be 1 (gh failure is caught gracefully)
    expect(process.exitCode).not.toBe(1);
  });

  test('skipped results do not count as failures', async () => {
    const dir = await makeTmpDir();
    const results = [
      makeResult({ status: 'pass' }),
      makeResult({ testFile: 'skip.test.ts', status: 'skipped' }),
    ];

    // skipped is not 'fail', so PR should be attempted (gh will fail gracefully)
    await createVerifyPR(dir, results, [], dir, { quiet: true });
    expect(process.exitCode).not.toBe(1);
  });

  test('dry-run mode does not create PR and does not throw', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];

    // In dry-run mode, should return without error even without gh
    await createVerifyPR(dir, results, [], dir, { dryRun: true, quiet: true });
    expect(process.exitCode).not.toBe(1);
  });

  test('dry-run with quiet mode is completely silent', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];
    const logSpy = spyOn(console, 'log').mockImplementation(() => {});

    await createVerifyPR(dir, results, [], dir, { dryRun: true, quiet: true });

    // Should not have printed anything
    expect(logSpy).not.toHaveBeenCalled();
    logSpy.mockRestore();
  });

  test('dry-run without quiet prints PR title and body', async () => {
    const dir = await makeTmpDir();
    const proofDir = path.join(dir, 'my-feature');
    await fs.mkdir(proofDir, { recursive: true });
    const results = [makeResult({ status: 'pass' })];
    const logged: string[] = [];
    const logSpy = spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logged.push(args.join(' '));
    });

    await createVerifyPR(proofDir, results, [], dir, { dryRun: true, quiet: false });

    const output = logged.join('\n');
    expect(output).toContain('Verify: my-feature');
    expect(output).toContain('gh pr create');
    logSpy.mockRestore();
  });

  test('PR title follows pattern Verify: <proof-dir-basename>', () => {
    const proofDir = '/repo/.forge/proofs/gtmeng-590';
    const title = `Verify: ${path.basename(proofDir)}`;
    expect(title).toBe('Verify: gtmeng-590');
  });

  test('PR title uses last component of nested proofDir', () => {
    expect(`Verify: ${path.basename('/deep/nested/proof/dir')}`).toBe('Verify: dir');
    expect(`Verify: ${path.basename('/repo/.forge/proofs/my-feature')}`).toBe('Verify: my-feature');
  });

  test('gh error is surfaced gracefully without throwing', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];

    // dir is not a git repo, so gh pr create will fail
    // createVerifyPR should catch the error and not throw
    await createVerifyPR(dir, results, [], dir, { quiet: false });

    // Should not have set exitCode to 1 (gh failure is not a verify failure)
    // The function returns without throwing
    expect(process.exitCode).not.toBe(1);
  });

  test('gh error prints failure message when not quiet', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];
    const logged: string[] = [];
    const logSpy = spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logged.push(args.join(' '));
    });

    await createVerifyPR(dir, results, [], dir, { quiet: false });

    const output = logged.join('\n');
    expect(output).toContain('PR creation failed');
    logSpy.mockRestore();
  });

  test('gh error is silent in quiet mode', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];
    const logSpy = spyOn(console, 'log').mockImplementation(() => {});

    await createVerifyPR(dir, results, [], dir, { quiet: true });

    // In quiet mode, no output even on failure
    expect(logSpy).not.toHaveBeenCalled();
    logSpy.mockRestore();
  });

  test('failure summary lists failed test files when not quiet', async () => {
    const dir = await makeTmpDir();
    const results = [
      makeResult({ testFile: 'auth.test.ts', status: 'fail' }),
      makeResult({ testFile: 'api.test.ts', status: 'fail' }),
    ];
    const logged: string[] = [];
    const logSpy = spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logged.push(args.join(' '));
    });

    await createVerifyPR(dir, results, [], dir, { quiet: false });

    const output = logged.join('\n');
    expect(output).toContain('PR creation skipped');
    expect(output).toContain('2 test file(s) failed');
    expect(output).toContain('auth.test.ts');
    expect(output).toContain('api.test.ts');
    logSpy.mockRestore();
  });

  test('cleans up temp file even when gh fails', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];

    await createVerifyPR(dir, results, [], dir, { quiet: true });

    // After the function returns, temp files should be cleaned up
    // We can't directly check since the temp file name is dynamic,
    // but we can verify the function completed without error
    const tmpFiles = await fs.readdir(os.tmpdir());
    const verifyTmpFiles = tmpFiles.filter(f => f.startsWith('forge-verify-pr-'));
    // All forge-verify-pr temp files should be cleaned up
    // (there might be 0 — cleanup happened in finally block)
    expect(verifyTmpFiles.length).toBeLessThanOrEqual(0);
  });
});

// ── CLI and MCP integration ──────────────────────────────────

describe('verify CLI registration', () => {
  test('verify command is registered in index.ts', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain(".command('verify')");
  });

  test('verify command accepts proof-dir argument', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain("'<proof-dir>'");
  });

  test('verify command has --dry-run option', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain("'--dry-run'");
  });

  test('verify calls guardNestedSession (uses SDK)', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    // Verify command action calls guardNestedSession since it now uses runQuery
    const verifySection = indexContent.slice(indexContent.indexOf(".command('verify')"));
    const nextCommand = verifySection.indexOf(".command('", 10);
    const verifyBlock = verifySection.slice(0, nextCommand > 0 ? nextCommand : undefined);
    expect(verifyBlock).toContain('guardNestedSession()');
  });
});

describe('verify MCP integration', () => {
  test('forge_start command enum includes verify in mcp.ts', async () => {
    const mcpContent = await fs.readFile(path.join(import.meta.dirname, 'mcp.ts'), 'utf-8');
    expect(mcpContent).toContain("'verify'");
  });

  test('forge_start handles verify command', async () => {
    const mcpContent = await fs.readFile(path.join(import.meta.dirname, 'mcp.ts'), 'utf-8');
    expect(mcpContent).toContain("command === 'verify'");
  });
});
