// Generated by forge proof from verify-proof-parser.md, verify-run-checks.md, verify-pr-creation.md, verify-cli.md, verify-mcp.md, proof-verify-manifest.md
import { describe, test, expect, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { readProofManifest, detectTestRunner, buildPRBody, createVerifyPR } from './proof-runner.js';
import type { VerifyOptions, VerifyResult, ProofManifest, ForgeResult } from './types.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-verify-test-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
});

function makeManifest(overrides: Partial<ProofManifest> = {}): ProofManifest {
  return {
    generatedAt: new Date().toISOString(),
    specDir: 'specs/',
    entries: [
      { specFile: 'auth.md', category: 'unit', testFile: '/abs/path/auth.test.ts', description: 'Auth tests' },
    ],
    manualCheckCount: 0,
    ...overrides,
  };
}

function makeResult(overrides: Partial<VerifyResult> = {}): VerifyResult {
  return {
    testFile: 'auth.test.ts',
    status: 'pass',
    exitCode: 0,
    stderr: '',
    durationSeconds: 1.5,
    ...overrides,
  };
}

async function writeManifest(dir: string, manifest: ProofManifest): Promise<void> {
  await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
}

async function writeManual(dir: string, content: string): Promise<void> {
  await fs.writeFile(path.join(dir, 'manual.md'), content);
}

// ── readProofManifest ────────────────────────────────────────

describe('readProofManifest', () => {
  test('reads and returns valid manifest with all fields', async () => {
    const dir = await makeTmpDir();
    const manifest = makeManifest({
      entries: [
        { specFile: 'auth.md', category: 'unit', testFile: '/abs/auth.test.ts', description: 'Auth tests' },
        { specFile: 'api.md', category: 'integration', testFile: '/abs/api.test.ts', description: 'API tests' },
      ],
      manualCheckCount: 2,
    });
    await writeManifest(dir, manifest);

    const result = await readProofManifest(dir);
    expect(result.entries).toHaveLength(2);
    expect(result.entries[0].specFile).toBe('auth.md');
    expect(result.entries[0].category).toBe('unit');
    expect(result.entries[1].specFile).toBe('api.md');
    expect(result.entries[1].category).toBe('integration');
    expect(result.manualCheckCount).toBe(2);
  });

  test('throws clear error when manifest.json is missing', async () => {
    const dir = await makeTmpDir();
    await expect(readProofManifest(dir)).rejects.toThrow('manifest.json not found');
  });

  test('error message mentions forge proof when manifest missing', async () => {
    const dir = await makeTmpDir();
    try {
      await readProofManifest(dir);
      expect(true).toBe(false); // should not reach here
    } catch (err) {
      expect((err as Error).message).toContain('forge proof');
    }
  });

  test('throws when manifest.json is invalid JSON', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'manifest.json'), 'not valid json {{{');
    await expect(readProofManifest(dir)).rejects.toThrow('not valid JSON');
  });

  test('throws when manifest is missing entries array', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify({ generatedAt: 'now', specDir: '.' }));
    await expect(readProofManifest(dir)).rejects.toThrow('missing "entries" array');
  });

  test('throws when entries is not an array', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify({ entries: 'not-array' }));
    await expect(readProofManifest(dir)).rejects.toThrow('missing "entries" array');
  });

  test('accepts manifest with empty entries array', async () => {
    const dir = await makeTmpDir();
    await writeManifest(dir, makeManifest({ entries: [] }));
    const result = await readProofManifest(dir);
    expect(result.entries).toHaveLength(0);
  });

  test('preserves all entry fields through roundtrip', async () => {
    const dir = await makeTmpDir();
    await writeManifest(dir, makeManifest({
      entries: [{
        specFile: 'complex.md',
        category: 'integration',
        testFile: '/repo/tests/complex.test.ts',
        description: 'Complex integration tests for auth flow',
      }],
    }));

    const result = await readProofManifest(dir);
    expect(result.entries[0].specFile).toBe('complex.md');
    expect(result.entries[0].category).toBe('integration');
    expect(result.entries[0].testFile).toBe('/repo/tests/complex.test.ts');
    expect(result.entries[0].description).toBe('Complex integration tests for auth flow');
  });
});

// ── detectTestRunner ─────────────────────────────────────────

describe('detectTestRunner', () => {
  test('detects bun from bun.lockb', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lockb'), '');
    expect(await detectTestRunner(dir)).toBe('bun test');
  });

  test('detects bun from bun.lock', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lock'), '');
    expect(await detectTestRunner(dir)).toBe('bun test');
  });

  test('detects vitest from devDependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { vitest: '^1.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('vitest run');
  });

  test('detects vitest from regular dependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ dependencies: { vitest: '^1.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('vitest run');
  });

  test('detects jest from devDependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { jest: '^29.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('npx jest');
  });

  test('falls back to npm test when no runner detected', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { typescript: '^5.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('npm test --');
  });

  test('falls back to npm test when no package.json', async () => {
    const dir = await makeTmpDir();
    expect(await detectTestRunner(dir)).toBe('npm test --');
  });

  test('bun lockfile takes priority over vitest in package.json', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lockb'), '');
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { vitest: '^1.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('bun test');
  });

  test('vitest takes priority over jest', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { vitest: '^1.0.0', jest: '^29.0.0' } }),
    );
    expect(await detectTestRunner(dir)).toBe('vitest run');
  });
});

// ── buildPRBody ──────────────────────────────────────────────

describe('buildPRBody', () => {
  test('generates summary table with pass/fail/skip statuses', () => {
    const results: VerifyResult[] = [
      makeResult({ testFile: 'auth.test.ts', status: 'pass', durationSeconds: 1.2 }),
      makeResult({ testFile: 'api.test.ts', status: 'fail', durationSeconds: 3.5 }),
      makeResult({ testFile: 'missing.test.ts', status: 'skipped', durationSeconds: undefined }),
    ];

    const body = buildPRBody(results, []);
    expect(body).toContain('## Summary');
    expect(body).toContain('| File | Status | Duration |');
    expect(body).toContain('auth.test.ts');
    expect(body).toContain('PASS');
    expect(body).toContain('api.test.ts');
    expect(body).toContain('FAIL');
    expect(body).toContain('SKIPPED');
    expect(body).toContain('1.2s');
    expect(body).toContain('3.5s');
    expect(body).toContain('N/A');
  });

  test('includes human verification section when steps provided', () => {
    const results: VerifyResult[] = [makeResult()];
    const humanSteps = [
      '- Check the login page renders correctly',
      '- Verify OAuth redirect works',
    ];

    const body = buildPRBody(results, humanSteps);
    expect(body).toContain('## Human Verification');
    expect(body).toContain('- [ ] Check the login page renders correctly');
    expect(body).toContain('- [ ] Verify OAuth redirect works');
  });

  test('omits human verification section when no steps', () => {
    const body = buildPRBody([makeResult()], []);
    expect(body).not.toContain('## Human Verification');
  });

  test('strips leading list markers from human steps', () => {
    const body = buildPRBody([makeResult()], [
      '- Manually check X',
      '* Verify Y',
      '1. Check Z',
    ]);
    expect(body).toContain('- [ ] Manually check X');
    expect(body).toContain('- [ ] Verify Y');
    expect(body).toContain('- [ ] Check Z');
    // No doubled markers
    expect(body).not.toContain('- [ ] - ');
    expect(body).not.toContain('- [ ] * ');
    expect(body).not.toContain('- [ ] 1. ');
  });

  test('handles empty results array', () => {
    const body = buildPRBody([], []);
    expect(body).toContain('## Summary');
    expect(body).toContain('| File | Status | Duration |');
  });

  test('result body is trimmed (no trailing whitespace)', () => {
    const body = buildPRBody([makeResult()], []);
    expect(body).toBe(body.trimEnd());
  });

  test('table row per test file', () => {
    const results = [
      makeResult({ testFile: 'a.test.ts' }),
      makeResult({ testFile: 'b.test.ts' }),
      makeResult({ testFile: 'c.test.ts' }),
    ];
    const body = buildPRBody(results, []);
    // Count table rows (lines starting with |, excluding header and separator)
    const tableRows = body.split('\n').filter(l => l.startsWith('| ') && !l.startsWith('| File') && !l.startsWith('|---'));
    expect(tableRows).toHaveLength(3);
  });
});

// ── createVerifyPR ───────────────────────────────────────────

describe('createVerifyPR', () => {
  test('skips PR when no results', async () => {
    const dir = await makeTmpDir();
    // Should not throw, just return silently
    await createVerifyPR(dir, [], [], dir, { quiet: true });
  });

  test('skips PR when any test fails', async () => {
    const dir = await makeTmpDir();
    const results = [
      makeResult({ status: 'pass' }),
      makeResult({ status: 'fail', exitCode: 1, stderr: 'assertion error' }),
    ];
    // Should set process.exitCode to 1 and skip PR
    await createVerifyPR(dir, results, [], dir, { quiet: true });
    expect(process.exitCode).toBe(1);
    process.exitCode = 0;
  });

  test('dry-run mode prints PR details without creating', async () => {
    const dir = await makeTmpDir();
    const results = [makeResult({ status: 'pass' })];

    // In dry run, should not throw and should not call gh
    await createVerifyPR(dir, results, [], dir, { dryRun: true, quiet: true });
    // No error means it succeeded without actually creating the PR
  });

  test('PR title follows pattern: Verify: <dirname>', () => {
    const proofDir = '/repo/.forge/proofs/gtmeng-590';
    const dirBasename = path.basename(proofDir);
    const title = `Verify: ${dirBasename}`;
    expect(title).toBe('Verify: gtmeng-590');
  });

  test('PR title uses basename of proofDir', () => {
    expect(path.basename('/repo/.forge/proofs/my-feature')).toBe('my-feature');
    expect(path.basename('/repo/.forge/proofs')).toBe('proofs');
  });
});

// ── verify CLI registration ──────────────────────────────────

describe('verify CLI registration', () => {
  test('verify command is registered in index.ts', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain(".command('verify')");
  });

  test('verify command accepts proof-dir argument', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain("'<proof-dir>'");
  });

  test('verify command has --dry-run option', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    // verify command block should contain dry-run
    expect(indexContent).toContain("'--dry-run'");
  });

  test('verify command has -C/--cwd option', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    // Multiple commands have -C, but verify should too
    expect(indexContent).toContain("'-C, --cwd <path>'");
  });

  test('verify command has -q/--quiet option', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain("'-q, --quiet'");
  });

  test('verify does NOT call guardNestedSession (no SDK call)', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    // Find the verify command action block and check it doesn't have guardNestedSession
    // The comment in index.ts says: "No guardNestedSession() — verify runs test files directly, no SDK call"
    expect(indexContent).toContain('No guardNestedSession()');
  });

  test('runVerify is exported from proof-runner.ts', async () => {
    const mod = await import('./proof-runner.js');
    expect(typeof mod.runVerify).toBe('function');
  });

  test('all verify helper functions are exported', async () => {
    const mod = await import('./proof-runner.js');
    expect(typeof mod.readProofManifest).toBe('function');
    expect(typeof mod.detectTestRunner).toBe('function');
    expect(typeof mod.buildPRBody).toBe('function');
    expect(typeof mod.createVerifyPR).toBe('function');
  });

  test('verify command description mentions proof test protocols', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain('Execute proof test protocols');
  });
});

// ── verify MCP integration ───────────────────────────────────

describe('verify MCP integration', () => {
  test('forge_start command enum includes verify in mcp.ts', async () => {
    const mcpContent = await fs.readFile(path.join(import.meta.dirname, 'mcp.ts'), 'utf-8');
    // The z.enum for command should include verify
    expect(mcpContent).toContain("'verify'");
  });

  test('forge_start handles verify command with spec_path as positional arg', async () => {
    const mcpContent = await fs.readFile(path.join(import.meta.dirname, 'mcp.ts'), 'utf-8');
    // verify follows same pattern as audit for positional path
    expect(mcpContent).toContain("command === 'verify'");
  });

  test('forge_start description mentions verify', async () => {
    const mcpContent = await fs.readFile(path.join(import.meta.dirname, 'mcp.ts'), 'utf-8');
    expect(mcpContent).toContain('verify');
  });

  test('ForgeResult.type supports verify literal', () => {
    const result: Partial<ForgeResult> = { type: 'verify' };
    expect(result.type).toBe('verify');
  });
});

// ── VerifyResult shape ───────────────────────────────────────

describe('VerifyResult', () => {
  test('pass result has exitCode 0 and empty stderr', () => {
    const result = makeResult({ status: 'pass', exitCode: 0, stderr: '' });
    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe('');
  });

  test('fail result has non-zero exitCode and stderr content', () => {
    const result = makeResult({
      status: 'fail',
      exitCode: 1,
      stderr: 'FAIL src/auth.test.ts\n  Expected true, received false',
    });
    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain('Expected true');
  });

  test('skipped result has exitCode -1 for missing test file', () => {
    const result = makeResult({
      status: 'skipped',
      exitCode: -1,
      stderr: 'Test file not found: /path/to/test.ts',
    });
    expect(result.status).toBe('skipped');
    expect(result.exitCode).toBe(-1);
  });

  test('durationSeconds is optional', () => {
    const result = makeResult({ durationSeconds: undefined });
    expect(result.durationSeconds).toBeUndefined();
  });
});
