// Generated by forge proof from proof-verify-manifest.md
import { describe, test, expect, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import type { ProofManifest, VerifyResult } from './types.js';
import { readProofManifest, detectTestRunner, buildPRBody } from './proof-runner.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-verify-test-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
});

function makeVerifyResult(overrides: Partial<VerifyResult> = {}): VerifyResult {
  return {
    testFile: 'src/feature.test.ts',
    status: 'pass',
    exitCode: 0,
    stderr: '',
    durationSeconds: 1.5,
    ...overrides,
  };
}

async function setupProofDir(
  baseDir: string,
  manifest: ProofManifest,
  opts?: { manual?: string; testFiles?: Array<{ path: string; content: string }> },
): Promise<string> {
  const proofDir = path.join(baseDir, 'proofs');
  await fs.mkdir(proofDir, { recursive: true });

  await fs.writeFile(path.join(proofDir, 'manifest.json'), JSON.stringify(manifest, null, 2));

  if (opts?.manual) {
    await fs.writeFile(path.join(proofDir, 'manual.md'), opts.manual);
  }

  if (opts?.testFiles) {
    for (const tf of opts.testFiles) {
      const fullPath = path.join(baseDir, tf.path);
      await fs.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.writeFile(fullPath, tf.content);
    }
  }

  return proofDir;
}

// ── readProofManifest ───────────────────────────────────────

describe('verify: readProofManifest', () => {
  test('reads and parses valid manifest.json', async () => {
    const dir = await makeTmpDir();
    const manifest: ProofManifest = {
      generatedAt: '2026-01-01T00:00:00Z',
      specDir: 'specs/',
      entries: [
        { specFile: 'auth.md', category: 'unit', testFile: 'src/auth.test.ts', description: 'Auth tests' },
        { specFile: 'db.md', category: 'integration', testFile: 'src/db.test.ts', description: 'DB tests' },
      ],
      manualCheckCount: 2,
    };
    const proofDir = await setupProofDir(dir, manifest);

    const loaded = await readProofManifest(proofDir);
    expect(loaded.generatedAt).toBe('2026-01-01T00:00:00Z');
    expect(loaded.specDir).toBe('specs/');
    expect(loaded.entries).toHaveLength(2);
    expect(loaded.entries[0].specFile).toBe('auth.md');
    expect(loaded.entries[1].category).toBe('integration');
    expect(loaded.manualCheckCount).toBe(2);
  });

  test('throws when manifest.json is missing', async () => {
    const dir = await makeTmpDir();
    const emptyProofDir = path.join(dir, 'no-manifest');
    await fs.mkdir(emptyProofDir, { recursive: true });

    try {
      await readProofManifest(emptyProofDir);
      expect(true).toBe(false); // Should not reach here
    } catch (err) {
      expect((err as Error).message).toContain('manifest.json');
    }
  });

  test('throws when manifest.json is invalid JSON', async () => {
    const dir = await makeTmpDir();
    const proofDir = path.join(dir, 'bad-json');
    await fs.mkdir(proofDir, { recursive: true });
    await fs.writeFile(path.join(proofDir, 'manifest.json'), 'not valid json <<<');

    try {
      await readProofManifest(proofDir);
      expect(true).toBe(false);
    } catch (err) {
      expect((err as Error).message).toContain('parse');
    }
  });

  test('throws when manifest.json has no entries array', async () => {
    const dir = await makeTmpDir();
    const proofDir = path.join(dir, 'no-entries');
    await fs.mkdir(proofDir, { recursive: true });
    await fs.writeFile(
      path.join(proofDir, 'manifest.json'),
      JSON.stringify({ generatedAt: '2026-01-01T00:00:00Z', specDir: 'specs/' }),
    );

    try {
      await readProofManifest(proofDir);
      expect(true).toBe(false);
    } catch (err) {
      expect((err as Error).message).toContain('entries');
    }
  });

  test('handles empty entries array', async () => {
    const dir = await makeTmpDir();
    const manifest: ProofManifest = {
      generatedAt: '2026-01-01T00:00:00Z',
      specDir: 'specs/',
      entries: [],
      manualCheckCount: 0,
    };
    const proofDir = await setupProofDir(dir, manifest);

    const loaded = await readProofManifest(proofDir);
    expect(loaded.entries).toHaveLength(0);
  });
});

// ── detectTestRunner ────────────────────────────────────────

describe('verify: detectTestRunner', () => {
  test('detects bun when bun.lockb exists', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lockb'), '');
    await fs.writeFile(path.join(dir, 'package.json'), JSON.stringify({ devDependencies: {} }));

    const runner = await detectTestRunner(dir);
    expect(runner).toBe('bun test');
  });

  test('detects bun when bun.lock exists', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(path.join(dir, 'bun.lock'), '');
    await fs.writeFile(path.join(dir, 'package.json'), JSON.stringify({ devDependencies: {} }));

    const runner = await detectTestRunner(dir);
    expect(runner).toBe('bun test');
  });

  test('detects vitest from devDependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { vitest: '^1.0.0' } }),
    );

    const runner = await detectTestRunner(dir);
    expect(runner).toBe('vitest run');
  });

  test('detects jest from devDependencies', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { jest: '^29.0.0' } }),
    );

    const runner = await detectTestRunner(dir);
    expect(runner).toBe('npx jest');
  });

  test('defaults to npm test when no recognized runner', async () => {
    const dir = await makeTmpDir();
    await fs.writeFile(
      path.join(dir, 'package.json'),
      JSON.stringify({ devDependencies: { mocha: '^10.0.0' } }),
    );

    const runner = await detectTestRunner(dir);
    expect(runner).toBe('npm test --');
  });

  test('defaults to npm test when no package.json', async () => {
    const dir = await makeTmpDir();
    // No package.json

    const runner = await detectTestRunner(dir);
    expect(runner).toBe('npm test --');
  });
});

// ── buildPRBody ─────────────────────────────────────────────

describe('verify: buildPRBody', () => {
  test('generates markdown with results table', () => {
    const results: VerifyResult[] = [
      makeVerifyResult({ testFile: 'src/auth.test.ts', status: 'pass', durationSeconds: 2.1 }),
      makeVerifyResult({ testFile: 'src/db.test.ts', status: 'fail', exitCode: 1, durationSeconds: 0.8 }),
    ];

    const body = buildPRBody(results, []);
    expect(body).toContain('auth.test.ts');
    expect(body).toContain('db.test.ts');
    // Contains table-like structure
    expect(body).toContain('|');
  });

  test('includes human verification checkboxes when humanSteps provided', () => {
    const results: VerifyResult[] = [
      makeVerifyResult({ testFile: 'src/feature.test.ts' }),
    ];
    const humanSteps = [
      'Verify the login page renders correctly',
      'Check that dark mode toggle works visually',
    ];

    const body = buildPRBody(results, humanSteps);
    expect(body).toContain('- [ ]');
    expect(body).toContain('login page');
    expect(body).toContain('dark mode');
  });

  test('omits human section when no human steps', () => {
    const results: VerifyResult[] = [
      makeVerifyResult({ testFile: 'src/auto.test.ts' }),
    ];

    const body = buildPRBody(results, []);
    // Should still have the results table
    expect(body).toContain('auto.test.ts');
  });

  test('shows pass/fail status for each test file', () => {
    const results: VerifyResult[] = [
      makeVerifyResult({ testFile: 'src/a.test.ts', status: 'pass' }),
      makeVerifyResult({ testFile: 'src/b.test.ts', status: 'fail' }),
      makeVerifyResult({ testFile: 'src/c.test.ts', status: 'skipped' }),
    ];

    const body = buildPRBody(results, []);
    // Body should include status indicators for all three
    expect(body).toContain('a.test.ts');
    expect(body).toContain('b.test.ts');
    expect(body).toContain('c.test.ts');
  });

  test('handles empty results array', () => {
    const body = buildPRBody([], []);
    // Should not throw and should produce some markdown
    expect(typeof body).toBe('string');
  });
});

// ── VerifyResult structure ──────────────────────────────────

describe('verify: VerifyResult structure', () => {
  test('pass result has exitCode 0 and empty stderr', () => {
    const result = makeVerifyResult({ status: 'pass', exitCode: 0, stderr: '' });
    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe('');
    expect(result.status).toBe('pass');
  });

  test('fail result captures exitCode and stderr', () => {
    const result = makeVerifyResult({
      status: 'fail',
      exitCode: 1,
      stderr: 'TypeError: Cannot read property of undefined',
    });
    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain('TypeError');
    expect(result.status).toBe('fail');
  });

  test('skipped result for missing test files', () => {
    const result = makeVerifyResult({
      status: 'skipped',
      testFile: 'src/missing.test.ts',
      exitCode: -1,
      stderr: 'File not found',
    });
    expect(result.status).toBe('skipped');
  });

  test('durationSeconds captures test execution time', () => {
    const result = makeVerifyResult({ durationSeconds: 3.456 });
    expect(result.durationSeconds).toBeCloseTo(3.456, 2);
  });
});
