// Generated by forge proof from proof-rename.md
import { describe, test, expect } from 'bun:test';
import { STAGE_ORDER, DEFAULT_GATES } from './pipeline-types.js';
import type { StageName, GateKey } from './pipeline-types.js';

// ── Pipeline types: prove -> proof rename ───────────────────

describe('proof rename: pipeline types', () => {
  test('STAGE_ORDER contains "proof" not "prove"', () => {
    expect(STAGE_ORDER).toContain('proof');
    expect(STAGE_ORDER).not.toContain('prove');
  });

  test('STAGE_ORDER has correct order: define -> run -> audit -> proof -> verify', () => {
    expect(STAGE_ORDER).toEqual(['define', 'run', 'audit', 'proof', 'verify']);
  });

  test('StageName type includes "proof"', () => {
    // Runtime check: STAGE_ORDER is the source of truth for StageName values
    const stages: StageName[] = [...STAGE_ORDER];
    expect(stages).toContain('proof');
    expect(stages.indexOf('proof')).toBe(3);
  });

  test('DEFAULT_GATES uses "proof" in gate key strings', () => {
    const gateKeys = Object.keys(DEFAULT_GATES) as GateKey[];
    const proofGates = gateKeys.filter(k => k.includes('proof'));
    expect(proofGates).toHaveLength(2);
    expect(proofGates).toContain('audit -> proof');
    expect(proofGates).toContain('proof -> verify');
  });

  test('DEFAULT_GATES does not contain "prove" in any key', () => {
    const gateKeys = Object.keys(DEFAULT_GATES) as GateKey[];
    const proveGates = gateKeys.filter(k => k.includes('prove'));
    expect(proveGates).toHaveLength(0);
  });

  test('audit -> proof gate defaults to "confirm"', () => {
    expect(DEFAULT_GATES['audit -> proof']).toBe('confirm');
  });

  test('proof -> verify gate defaults to "auto"', () => {
    expect(DEFAULT_GATES['proof -> verify']).toBe('auto');
  });

  test('all four gates present with correct keys', () => {
    const keys = Object.keys(DEFAULT_GATES);
    expect(keys).toHaveLength(4);
    expect(keys).toEqual(
      expect.arrayContaining([
        'define -> run',
        'run -> audit',
        'audit -> proof',
        'proof -> verify',
      ]),
    );
  });
});

// ── ForgeResult type: prove -> proof ────────────────────────

describe('proof rename: ForgeResult type field', () => {
  test('ForgeResult type literal "proof" is valid', () => {
    // Runtime verification that the type field accepts 'proof'
    const result = {
      startedAt: '2026-01-01T00:00:00Z',
      completedAt: '2026-01-01T00:01:00Z',
      durationSeconds: 60,
      status: 'success' as const,
      prompt: 'test',
      model: 'sonnet',
      cwd: '/test',
      type: 'proof' as const,
    };
    expect(result.type).toBe('proof');
  });
});

// ── CLI command registration ────────────────────────────────

describe('proof rename: CLI commands', () => {
  test('proof.ts module exports runProof function', async () => {
    const proofModule = await import('./proof.js');
    expect(typeof proofModule.runProof).toBe('function');
  });

  test('proof.ts module exports detectTestConvention function', async () => {
    const proofModule = await import('./proof.js');
    expect(typeof proofModule.detectTestConvention).toBe('function');
  });

  test('proof-runner.ts exports runVerify function', async () => {
    const runnerModule = await import('./proof-runner.js');
    expect(typeof runnerModule.runVerify).toBe('function');
  });

  test('proof-runner.ts exports readProofManifest function', async () => {
    const runnerModule = await import('./proof-runner.js');
    expect(typeof runnerModule.readProofManifest).toBe('function');
  });

  test('proof-runner.ts exports detectTestRunner function', async () => {
    const runnerModule = await import('./proof-runner.js');
    expect(typeof runnerModule.detectTestRunner).toBe('function');
  });

  test('proof-runner.ts exports buildPRBody function', async () => {
    const runnerModule = await import('./proof-runner.js');
    expect(typeof runnerModule.buildPRBody).toBe('function');
  });
});

// ── Import path: proof.js not prove.js ──────────────────────

describe('proof rename: import paths', () => {
  test('./proof.js module resolves successfully', async () => {
    let resolved = false;
    try {
      await import('./proof.js');
      resolved = true;
    } catch { /* import failed */ }
    expect(resolved).toBe(true);
  });

  test('./proof-runner.js module resolves successfully', async () => {
    let resolved = false;
    try {
      await import('./proof-runner.js');
      resolved = true;
    } catch { /* import failed */ }
    expect(resolved).toBe(true);
  });
});
