// Generated by forge proof from proof-rename.md, proof-batch-generation.md
import { describe, test, expect, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { detectTestConvention } from './proof.js';
import type { ProofOptions, ProofManifest, ProofManifestEntry, ForgeResult } from './types.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-proof-test-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
});

function makeManifest(overrides: Partial<ProofManifest> = {}): ProofManifest {
  return {
    generatedAt: new Date().toISOString(),
    specDir: 'specs/',
    entries: [],
    manualCheckCount: 0,
    ...overrides,
  };
}

function makeEntry(overrides: Partial<ProofManifestEntry> = {}): ProofManifestEntry {
  return {
    specFile: 'feature.md',
    category: 'unit',
    testFile: '/path/to/src/feature.test.ts',
    description: 'Tests for feature spec',
    ...overrides,
  };
}

// ── proof rename (prove -> proof) ────────────────────────────

describe('proof rename (prove -> proof)', () => {
  test('runProof is exported from proof.ts (not runProve)', async () => {
    const mod = await import('./proof.js');
    expect(typeof mod.runProof).toBe('function');
    expect((mod as Record<string, unknown>).runProve).toBeUndefined();
  });

  test('detectTestConvention is exported from proof.ts', async () => {
    const mod = await import('./proof.js');
    expect(typeof mod.detectTestConvention).toBe('function');
  });

  test('ProofOptions uses specPaths array (not specPath string)', () => {
    const options: ProofOptions = {
      specPaths: ['spec1.md', 'spec2.md', 'spec3.md'],
    };
    expect(Array.isArray(options.specPaths)).toBe(true);
    expect(options.specPaths).toHaveLength(3);
  });

  test('ForgeResult.type includes proof literal', () => {
    const result: Partial<ForgeResult> = { type: 'proof' };
    expect(result.type).toBe('proof');
  });

  test('STAGE_ORDER includes proof (not prove)', async () => {
    const { STAGE_ORDER } = await import('./pipeline-types.js');
    expect(STAGE_ORDER).toContain('proof');
    expect(STAGE_ORDER).not.toContain('prove');
    expect(STAGE_ORDER).toEqual(['define', 'run', 'audit', 'proof', 'verify']);
  });

  test('DEFAULT_GATES uses proof gate keys (not prove)', async () => {
    const { DEFAULT_GATES } = await import('./pipeline-types.js');
    expect(DEFAULT_GATES['audit -> proof']).toBeDefined();
    expect(DEFAULT_GATES['proof -> verify']).toBeDefined();
    expect((DEFAULT_GATES as Record<string, unknown>)['audit -> prove']).toBeUndefined();
    expect((DEFAULT_GATES as Record<string, unknown>)['prove -> verify']).toBeUndefined();
  });

  test('forge prove alias still works (backward compatible)', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    // proof is the primary command
    expect(indexContent).toContain(".command('proof')");
    // prove is the deprecated hidden alias
    expect(indexContent).toContain(".command('prove'");
    expect(indexContent).toContain('hidden: true');
  });

  test('CLI proof action maps to runProof import', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain("import { runProof } from './proof.js'");
  });

  test('pipeline imports runProof (not runProve)', async () => {
    const pipelineContent = await fs.readFile(path.join(import.meta.dirname, 'pipeline.ts'), 'utf-8');
    expect(pipelineContent).toContain('runProof');
    expect(pipelineContent).not.toContain('runProve');
  });
});

// ── detectTestConvention ─────────────────────────────────────

describe('detectTestConvention', () => {
  test('detects colocated tests in src/ when 2+ test files exist', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'foo.test.ts'), '');
    await fs.writeFile(path.join(srcDir, 'bar.test.ts'), '');
    await fs.writeFile(path.join(srcDir, 'foo.ts'), '');

    const result = await detectTestConvention(dir);
    expect(result.style).toBe('colocated');
    expect(result.testDir).toBe('src');
    expect(result.examples).toContain('src/foo.test.ts');
    expect(result.examples).toContain('src/bar.test.ts');
  });

  test('detects separate tests/ directory', async () => {
    const dir = await makeTmpDir();
    const testsDir = path.join(dir, 'tests');
    await fs.mkdir(testsDir, { recursive: true });
    await fs.writeFile(path.join(testsDir, 'foo.test.ts'), '');

    const result = await detectTestConvention(dir);
    expect(result.style).toBe('separate');
    expect(result.testDir).toBe('tests');
    expect(result.examples).toContain('tests/foo.test.ts');
  });

  test('detects test/ directory (singular)', async () => {
    const dir = await makeTmpDir();
    const testDir = path.join(dir, 'test');
    await fs.mkdir(testDir, { recursive: true });
    await fs.writeFile(path.join(testDir, 'foo.test.ts'), '');

    const result = await detectTestConvention(dir);
    expect(result.style).toBe('separate');
    expect(result.testDir).toBe('test');
  });

  test('detects __tests__/ directory', async () => {
    const dir = await makeTmpDir();
    const testsDir = path.join(dir, '__tests__');
    await fs.mkdir(testsDir, { recursive: true });
    await fs.writeFile(path.join(testsDir, 'foo.spec.ts'), '');

    const result = await detectTestConvention(dir);
    expect(result.style).toBe('separate');
    expect(result.testDir).toBe('__tests__');
  });

  test('prefers colocated when src/ has 2+ test files over separate tests/', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'a.test.ts'), '');
    await fs.writeFile(path.join(srcDir, 'b.test.ts'), '');

    const testsDir = path.join(dir, 'tests');
    await fs.mkdir(testsDir, { recursive: true });
    await fs.writeFile(path.join(testsDir, 'c.test.ts'), '');

    const result = await detectTestConvention(dir);
    expect(result.style).toBe('colocated');
  });

  test('defaults to colocated in src/ when no test files exist', async () => {
    const dir = await makeTmpDir();
    const result = await detectTestConvention(dir);
    expect(result.style).toBe('colocated');
    expect(result.testDir).toBe('src');
    expect(result.examples).toEqual([]);
  });

  test('requires 2+ test files in src/ for colocated (1 is not enough)', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'only.test.ts'), '');

    const result = await detectTestConvention(dir);
    // Falls through to default colocated with empty examples
    expect(result.style).toBe('colocated');
    expect(result.testDir).toBe('src');
  });

  test('detects .spec.ts files as well as .test.ts', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'foo.spec.ts'), '');
    await fs.writeFile(path.join(srcDir, 'bar.spec.ts'), '');

    const result = await detectTestConvention(dir);
    expect(result.style).toBe('colocated');
    expect(result.examples).toContain('src/foo.spec.ts');
  });

  test('detects .tsx and .jsx test files', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'app.test.tsx'), '');
    await fs.writeFile(path.join(srcDir, 'button.test.jsx'), '');

    const result = await detectTestConvention(dir);
    expect(result.style).toBe('colocated');
    expect(result.examples.length).toBe(2);
  });

  test('caps examples at 5 files', async () => {
    const dir = await makeTmpDir();
    const srcDir = path.join(dir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    for (let i = 0; i < 10; i++) {
      await fs.writeFile(path.join(srcDir, `file${i}.test.ts`), '');
    }

    const result = await detectTestConvention(dir);
    expect(result.examples.length).toBeLessThanOrEqual(5);
  });
});

// ── ProofManifest filesystem roundtrip ───────────────────────

describe('ProofManifest filesystem roundtrip', () => {
  test('manifest with entries roundtrips through JSON file', async () => {
    const dir = await makeTmpDir();
    const manifestPath = path.join(dir, 'manifest.json');

    const manifest = makeManifest({
      entries: [
        makeEntry({ specFile: 'auth.md', testFile: '/abs/path/auth.test.ts', category: 'unit' }),
        makeEntry({ specFile: 'api.md', testFile: '/abs/path/api.test.ts', category: 'integration' }),
      ],
      manualCheckCount: 3,
    });

    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2));
    const raw = await fs.readFile(manifestPath, 'utf-8');
    const parsed: ProofManifest = JSON.parse(raw);

    expect(parsed.entries).toHaveLength(2);
    expect(parsed.entries[0].specFile).toBe('auth.md');
    expect(parsed.entries[0].category).toBe('unit');
    expect(parsed.entries[1].specFile).toBe('api.md');
    expect(parsed.entries[1].category).toBe('integration');
    expect(parsed.manualCheckCount).toBe(3);
  });

  test('manifest with zero entries is valid', async () => {
    const dir = await makeTmpDir();
    const manifestPath = path.join(dir, 'manifest.json');

    const manifest = makeManifest({ entries: [] });
    await fs.writeFile(manifestPath, JSON.stringify(manifest));
    const parsed: ProofManifest = JSON.parse(await fs.readFile(manifestPath, 'utf-8'));
    expect(parsed.entries).toEqual([]);
  });

  test('generatedAt is ISO 8601 timestamp', () => {
    const manifest = makeManifest();
    expect(() => new Date(manifest.generatedAt)).not.toThrow();
    expect(new Date(manifest.generatedAt).toISOString()).toBe(manifest.generatedAt);
  });

  test('entry testFile can be absolute path', () => {
    const entry = makeEntry({ testFile: '/absolute/path/to/test.test.ts' });
    expect(path.isAbsolute(entry.testFile)).toBe(true);
  });

  test('entry testFile can be relative path', () => {
    const entry = makeEntry({ testFile: 'unit/auth.test.ts' });
    expect(path.isAbsolute(entry.testFile)).toBe(false);
  });

  test('entry category is unit or integration', () => {
    const unit = makeEntry({ category: 'unit' });
    const integration = makeEntry({ category: 'integration' });
    expect(unit.category).toBe('unit');
    expect(integration.category).toBe('integration');
  });
});

// ── Batch generation behavior ────────────────────────────────

describe('batch generation', () => {
  test('single-spec mode writes to same structured output', () => {
    // forge proof single.md -> still produces manifest.json + manual.md
    const outputDir = '.forge/proofs';
    expect(path.join(outputDir, 'manifest.json')).toBe('.forge/proofs/manifest.json');
    expect(path.join(outputDir, 'manual.md')).toBe('.forge/proofs/manual.md');
  });

  test('SKIP_FILES excludes index.md and readme.md from spec scanning', async () => {
    const dir = await makeTmpDir();
    const SKIP_FILES = new Set(['index.md', 'readme.md']);

    await fs.writeFile(path.join(dir, 'feature.md'), '# Feature');
    await fs.writeFile(path.join(dir, 'index.md'), '# Index');
    await fs.writeFile(path.join(dir, 'README.md'), '# Readme');
    await fs.writeFile(path.join(dir, 'auth.md'), '# Auth');

    const entries = await fs.readdir(dir);
    const specFiles = entries.filter(f => f.endsWith('.md') && !SKIP_FILES.has(f.toLowerCase()));
    expect(specFiles).toContain('feature.md');
    expect(specFiles).toContain('auth.md');
    expect(specFiles).not.toContain('index.md');
    expect(specFiles).not.toContain('README.md');
  });

  test('batch size threshold is 20 specs', () => {
    // From proof.ts: BATCH_SIZE_THRESHOLD = 20
    const BATCH_SIZE_THRESHOLD = 20;
    const smallBatch = Array.from({ length: 15 }, (_, i) => `spec${i}.md`);
    const largeBatch = Array.from({ length: 25 }, (_, i) => `spec${i}.md`);

    // Small batch: single group
    expect(smallBatch.length <= BATCH_SIZE_THRESHOLD).toBe(true);
    // Large batch: needs splitting
    expect(largeBatch.length > BATCH_SIZE_THRESHOLD).toBe(true);
  });

  test('directory grouping for large batches', () => {
    const specFiles = [
      'auth/login.md', 'auth/oauth.md', 'auth/session.md',
      'api/users.md', 'api/products.md',
      'db/migrate.md',
    ];

    const groups = new Map<string, string[]>();
    for (const file of specFiles) {
      const dir = path.dirname(file);
      const group = groups.get(dir) ?? [];
      group.push(file);
      groups.set(dir, group);
    }

    expect(groups.get('auth')).toHaveLength(3);
    expect(groups.get('api')).toHaveLength(2);
    expect(groups.get('db')).toHaveLength(1);
  });
});
