// Generated by forge proof from plan-mode.md
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';

// ── Helpers ──────────────────────────────────────────────────

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-plan-test-'));
  await fs.mkdir(path.join(tmpDir, '.forge'), { recursive: true });
});

afterEach(async () => {
  await fs.rm(tmpDir, { recursive: true, force: true });
});

// ── Planning prompt structure ─────────────────────────────────

describe('plan-mode prompt construction', () => {
  // These tests verify the planning prompt template by reading run.ts source.
  // The critical sections required by the spec must be present.

  test('run.ts source includes disallowedTools enforcement for planOnly', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // Verify SDK-level tool restriction is set for plan-only mode
    expect(runSrc).toContain("disallowedTools: ['Write', 'Edit']");
    expect(runSrc).toContain('planOnly');
  });

  test('run.ts planning prompt includes required output sections', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // The planning prompt must include all required structured sections
    expect(runSrc).toContain('Goal Summary');
    expect(runSrc).toContain('File Inventory');
    expect(runSrc).toContain('Dependency Analysis');
    expect(runSrc).toContain('Implementation Steps');
    expect(runSrc).toContain('Risk Assessment');
  });

  test('run.ts planning prompt instructs read-only tools only', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // Planning mode prompt should explicitly restrict to read-only operations
    expect(runSrc).toContain('read-only');
    expect(runSrc).toContain('Do not create, modify, or delete files');
  });

  test('run.ts verification is skipped for planOnly', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // Verification must be skipped for plan-only runs
    expect(runSrc).toContain('planOnly');
    // The guard condition for verification
    expect(runSrc).toMatch(/!planOnly/);
  });

  test('run.ts uses planModel when planOnly is set', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // Plan model override must be applied
    expect(runSrc).toContain('planModel');
    expect(runSrc).toContain('planOnly && planModel');
  });
});

// ── CLI plan-only options ─────────────────────────────────────

describe('plan-mode CLI options in index.ts', () => {
  test('index.ts includes --plan-only option', async () => {
    const indexSrc = await fs.readFile(
      path.join(import.meta.dir, 'index.ts'),
      'utf-8',
    );
    expect(indexSrc).toContain('plan-only');
    expect(indexSrc).toContain('planOnly');
  });

  test('index.ts includes --plan-model option', async () => {
    const indexSrc = await fs.readFile(
      path.join(import.meta.dir, 'index.ts'),
      'utf-8',
    );
    expect(indexSrc).toContain('plan-model');
  });
});

// ── ForgeOptions type includes plan-mode fields ───────────────

describe('plan-mode type definitions', () => {
  test('types.ts ForgeOptions includes planOnly field', async () => {
    const typesSrc = await fs.readFile(
      path.join(import.meta.dir, 'types.ts'),
      'utf-8',
    );
    expect(typesSrc).toContain('planOnly');
  });

  test('types.ts ForgeOptions includes planModel field', async () => {
    const typesSrc = await fs.readFile(
      path.join(import.meta.dir, 'types.ts'),
      'utf-8',
    );
    expect(typesSrc).toContain('planModel');
  });
});

// ── core.ts QueryConfig includes disallowedTools ─────────────

describe('SDK disallowedTools in QueryConfig', () => {
  test('core.ts QueryConfig includes disallowedTools field', async () => {
    const coreSrc = await fs.readFile(
      path.join(import.meta.dir, 'core.ts'),
      'utf-8',
    );
    expect(coreSrc).toContain('disallowedTools');
  });

  test('SDK query() is called with disallowedTools from QueryConfig', async () => {
    const coreSrc = await fs.readFile(
      path.join(import.meta.dir, 'core.ts'),
      'utf-8',
    );
    // Verify the disallowedTools is passed to the SDK call
    expect(coreSrc).toContain('disallowedTools');
  });
});

// ── plan-only budget default ──────────────────────────────────

describe('plan-mode budget defaults', () => {
  test('run.ts applies lower budget for plan-only mode', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // Plan mode should have a lower budget limit than regular run
    // The spec says $5 vs $50 default
    expect(runSrc).toContain('planOnly');
    // There should be some budget cap difference for plan mode
    // Look for conditional budget assignment
    expect(runSrc.indexOf('planOnly')).toBeGreaterThan(-1);
  });

  test('run.ts uses fewer max turns for plan-only mode', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // planOnly has 50 max turns vs effectiveMaxTurns for regular
    expect(runSrc).toContain('planOnly ? 50');
  });
});

// ── Bash tool available in plan mode (read-only exploration) ──

describe('plan-mode tool restrictions', () => {
  test('only Write and Edit are blocked (not Bash)', async () => {
    const runSrc = await fs.readFile(
      path.join(import.meta.dir, 'run.ts'),
      'utf-8',
    );
    // Should block Write and Edit but NOT Bash
    expect(runSrc).toContain("'Write'");
    expect(runSrc).toContain("'Edit'");
    // Bash should not be in the disallowedTools list
    const disallowedMatch = runSrc.match(/disallowedTools:\s*\[([^\]]+)\]/);
    if (disallowedMatch) {
      expect(disallowedMatch[1]).not.toContain('Bash');
    }
  });
});
