// Generated by forge proof from sibling-worktree-creation.md
import { describe, test, expect, beforeAll, afterAll, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import {
  getTestDb,
  getDb,
  closeDb,
  getWorktreeByPath,
  getWorktreeByBranch,
  listWorktrees,
} from './db.js';
import {
  createWorktree,
  cleanupWorktree,
  deriveSpecName,
  generateWorkGroupId,
} from './utils.js';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';
import type { Database } from 'bun:sqlite';

const execAsync = promisify(exec);

// ── Hermetic Git ─────────────────────────────────────────────

beforeAll(() => { setupHermeticGit(); });
afterAll(() => { teardownHermeticGit(); });

// ── Helpers ──────────────────────────────────────────────────

let repoDir: string;
const createdWorktrees: string[] = [];

async function makeGitRepo(): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-sibling-test-'));
  await execAsync('git init', { cwd: dir });
  await execAsync('git config user.email "test@forge.dev"', { cwd: dir });
  await execAsync('git config user.name "Forge Test"', { cwd: dir });
  await fs.writeFile(path.join(dir, 'README.md'), '# Test');
  await execAsync('git add . && git commit -m "initial commit"', { cwd: dir });
  // Ensure .forge dir exists for DB
  await fs.mkdir(path.join(dir, '.forge'), { recursive: true });
  return dir;
}

beforeEach(async () => {
  repoDir = await makeGitRepo();
  createdWorktrees.length = 0;
});

afterEach(async () => {
  // Clean up worktrees
  for (const wt of createdWorktrees) {
    try {
      await cleanupWorktree(wt, repoDir);
    } catch {
      // Best effort
    }
  }
  closeDb(repoDir);
  await fs.rm(repoDir, { recursive: true, force: true });
});

// ── deriveSpecName ───────────────────────────────────────────

describe('deriveSpecName', () => {
  test('strips .md extension', () => {
    expect(deriveSpecName('auth-login.md')).toBe('auth-login');
  });

  test('converts to lowercase', () => {
    expect(deriveSpecName('Auth-Login.md')).toBe('auth-login');
  });

  test('replaces non-alphanumeric with hyphens', () => {
    expect(deriveSpecName('my_feature (v2).md')).toBe('my-feature-v2');
  });

  test('collapses consecutive hyphens', () => {
    expect(deriveSpecName('some---spec___file.md')).toBe('some-spec-file');
  });

  test('trims leading and trailing hyphens', () => {
    expect(deriveSpecName('-leading-trailing-.md')).toBe('leading-trailing');
  });

  test('handles nested path — takes basename', () => {
    expect(deriveSpecName('specs/auth/oauth-flow.md')).toBe('oauth-flow');
  });

  test('handles spec name with numbers', () => {
    expect(deriveSpecName('01-setup.md')).toBe('01-setup');
  });

  test('handles single character name', () => {
    expect(deriveSpecName('a.md')).toBe('a');
  });
});

// ── Sibling directory worktree creation ──────────────────────

describe('createWorktree with sibling directory mode', () => {
  test('creates worktree as sibling directory with spec name', async () => {
    const wgId = generateWorkGroupId();
    const wtPath = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/auth-login.md',
      work_group_id: wgId,
      force: true,
    });
    createdWorktrees.push(wtPath);

    // Verify sibling directory pattern: {project}-{spec-name}
    // Use realpath to normalize macOS /var/ -> /private/var/ symlink
    const realWtPath = await fs.realpath(wtPath);
    const realRepoDir = await fs.realpath(repoDir);
    const parentDir = path.dirname(realRepoDir);
    expect(path.dirname(realWtPath)).toBe(parentDir);
    expect(path.basename(wtPath)).toContain('auth-login');

    // Verify it's a valid git worktree
    const { stdout } = await execAsync('git rev-parse --git-dir', { cwd: wtPath });
    expect(stdout.trim()).toBeTruthy();
  });

  test('includes linear issue ID in directory name when present', async () => {
    const wgId = generateWorkGroupId();
    const wtPath = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/auth.md',
      linear_issue_id: 'ENG-123',
      work_group_id: wgId,
      force: true,
    });
    createdWorktrees.push(wtPath);

    expect(path.basename(wtPath)).toContain('ENG-123');
    expect(path.basename(wtPath)).toContain('auth');
  });

  test('branch naming without Linear issue: forge/{spec-name}', async () => {
    const wgId = generateWorkGroupId();
    const wtPath = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/rate-limiting.md',
      work_group_id: wgId,
      force: true,
    });
    createdWorktrees.push(wtPath);

    const { stdout: branch } = await execAsync('git branch --show-current', { cwd: wtPath });
    expect(branch.trim()).toContain('forge/');
    expect(branch.trim()).toContain('rate-limiting');
  });

  test('branch naming with Linear issue: forge/{issue-id}/{spec-name}', async () => {
    const wgId = generateWorkGroupId();
    const wtPath = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/api-setup.md',
      linear_issue_id: 'ENG-456',
      work_group_id: wgId,
      force: true,
    });
    createdWorktrees.push(wtPath);

    const { stdout: branch } = await execAsync('git branch --show-current', { cwd: wtPath });
    expect(branch.trim()).toContain('forge/ENG-456/api-setup');
  });

  test('registers worktree in DB with status created', async () => {
    const wgId = generateWorkGroupId();
    const wtPath = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/db-migration.md',
      work_group_id: wgId,
      force: true,
    });
    createdWorktrees.push(wtPath);

    const db = getDb(repoDir);
    if (!db) throw new Error('DB unavailable');

    const wt = getWorktreeByPath(db, wtPath);
    expect(wt).not.toBeNull();
    expect(wt!.status).toBe('created');
    expect(wt!.work_group_id).toBe(wgId);
    expect(wt!.spec_path).toBe('specs/db-migration.md');
  });
});

// ── Directory collision handling ─────────────────────────────

describe('directory collision handling', () => {
  test('appends suffix when sibling directory already exists', async () => {
    const wgId1 = generateWorkGroupId();
    const wgId2 = generateWorkGroupId();

    // Create first worktree
    const wt1 = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/collision.md',
      work_group_id: wgId1,
      force: true,
    });
    createdWorktrees.push(wt1);

    // Create second worktree with same spec name (different work group)
    const wt2 = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/collision.md',
      work_group_id: wgId2,
      force: true,
    });
    createdWorktrees.push(wt2);

    // Paths should be different (second gets -2 suffix)
    expect(wt1).not.toBe(wt2);
    expect(path.basename(wt2)).toMatch(/-\d+$/);
  });
});

// ── Branch collision handling ────────────────────────────────

describe('branch collision handling', () => {
  test('appends suffix when branch is checked out in another worktree', async () => {
    const wgId = generateWorkGroupId();

    // Create first worktree — takes forge/branch-test
    const wt1 = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/branch-test.md',
      work_group_id: wgId,
      force: true,
    });
    createdWorktrees.push(wt1);

    const { stdout: branch1 } = await execAsync('git branch --show-current', { cwd: wt1 });

    // Create second worktree with same spec — branch should get suffixed
    const wgId2 = generateWorkGroupId();
    const wt2 = await createWorktree(repoDir, 'auto', {
      spec_path: 'specs/branch-test.md',
      work_group_id: wgId2,
      force: true,
    });
    createdWorktrees.push(wt2);

    const { stdout: branch2 } = await execAsync('git branch --show-current', { cwd: wt2 });

    // Branches should be different
    expect(branch1.trim()).not.toBe(branch2.trim());
    // Second branch should still start with forge/
    expect(branch2.trim()).toMatch(/^forge\//);
  });
});

// ── Legacy mode (backward compat) ────────────────────────────

describe('legacy worktree mode (no spec_path)', () => {
  test('creates worktree in /tmp/ with explicit branch name', async () => {
    const wtPath = await createWorktree(repoDir, 'legacy-branch', { force: true });
    createdWorktrees.push(wtPath);

    expect(wtPath).toContain(os.tmpdir());
    expect(wtPath).toContain('forge-worktree-legacy-branch');

    // Verify branch
    const { stdout: branch } = await execAsync('git branch --show-current', { cwd: wtPath });
    expect(branch.trim()).toBe('legacy-branch');
  });

  test('legacy mode does not register in DB worktrees table', async () => {
    const wtPath = await createWorktree(repoDir, 'unregistered', { force: true });
    createdWorktrees.push(wtPath);

    const db = getDb(repoDir);
    if (!db) throw new Error('DB unavailable');

    const wt = getWorktreeByPath(db, wtPath);
    expect(wt).toBeNull();
  });
});
