// Generated by forge proof from spec-manifest-db-migration.md
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import {
  getTestDb,
  insertSpecEntry,
  listSpecEntries,
  getSpecEntry,
  getSpecRunsByEntry,
  insertSpecRun,
  getDb,
  closeDb,
} from './db.js';
import {
  loadManifest,
  saveManifest,
  withSpecTransaction,
  findOrCreateEntry,
  updateEntryStatus,
} from './specs.js';
import type { SpecManifest, SpecEntry } from './types.js';
import type { Database } from 'bun:sqlite';

// ── Helpers ──────────────────────────────────────────────────

let tmpDir: string;

async function makeTmpDir(): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-manifest-test-'));
  await fs.mkdir(path.join(dir, '.forge'), { recursive: true });
  return dir;
}

function makeManifest(specs: Partial<SpecEntry>[]): SpecManifest {
  const now = new Date().toISOString();
  return {
    version: 1,
    specs: specs.map((s, i) => ({
      spec: s.spec ?? `specs/spec-${i}.md`,
      status: s.status ?? 'pending',
      runs: s.runs ?? [],
      source: s.source ?? 'file',
      workGroupId: s.workGroupId,
      createdAt: s.createdAt ?? now,
      updatedAt: s.updatedAt ?? now,
    })),
  };
}

async function writeJsonManifest(dir: string, manifest: SpecManifest): Promise<void> {
  const manifestPath = path.join(dir, '.forge', 'specs.json');
  await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2));
}

beforeEach(async () => {
  tmpDir = await makeTmpDir();
});

afterEach(async () => {
  closeDb(tmpDir);
  await fs.rm(tmpDir, { recursive: true, force: true });
});

// ── loadManifest ────────────────────────────────────────────

describe('loadManifest reads from DB', () => {
  test('returns empty manifest when no specs exist in DB or JSON', async () => {
    const manifest = await loadManifest(tmpDir);
    expect(manifest.version).toBe(1);
    expect(manifest.specs).toEqual([]);
  });

  test('returns specs from DB when entries exist', async () => {
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');

    insertSpecEntry(db, {
      id: 'test-entry-1',
      spec: 'auth/login.md',
      status: 'passed',
      source: 'file',
      work_group_id: 'wg-123',
    });

    const manifest = await loadManifest(tmpDir);
    expect(manifest.specs).toHaveLength(1);
    expect(manifest.specs[0].spec).toBe('auth/login.md');
    expect(manifest.specs[0].status).toBe('passed');
    expect(manifest.specs[0].source).toBe('file');
    expect(manifest.specs[0].workGroupId).toBe('wg-123');
  });

  test('includes run history from spec_runs table', async () => {
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');

    insertSpecEntry(db, {
      id: 'entry-with-runs',
      spec: 'feature.md',
      status: 'passed',
    });

    insertSpecRun(db, {
      id: 'run-1',
      spec_entry_id: 'entry-with-runs',
      run_id: 'batch-1',
      timestamp: '2026-01-01T00:00:00Z',
      status: 'failed',
      cost_usd: 1.5,
      duration_seconds: 60,
      num_turns: 10,
      verify_attempts: 2,
    });
    insertSpecRun(db, {
      id: 'run-2',
      spec_entry_id: 'entry-with-runs',
      run_id: 'batch-2',
      timestamp: '2026-01-02T00:00:00Z',
      status: 'passed',
      cost_usd: 0.8,
      duration_seconds: 30,
    });

    const manifest = await loadManifest(tmpDir);
    const entry = manifest.specs[0];
    expect(entry.runs).toHaveLength(2);
    // Runs should be in chronological order (ASC) for manifest format
    expect(entry.runs[0].timestamp).toBe('2026-01-01T00:00:00Z');
    expect(entry.runs[0].status).toBe('failed');
    expect(entry.runs[0].costUsd).toBe(1.5);
    expect(entry.runs[0].numTurns).toBe(10);
    expect(entry.runs[0].verifyAttempts).toBe(2);
    expect(entry.runs[1].timestamp).toBe('2026-01-02T00:00:00Z');
    expect(entry.runs[1].status).toBe('passed');
  });
});

// ── Auto-migration from JSON to DB ──────────────────────────

describe('auto-migration from JSON to DB', () => {
  test('imports JSON manifest into empty DB on first access', async () => {
    const jsonManifest = makeManifest([
      { spec: 'auth.md', status: 'passed', source: 'file', runs: [
        { runId: 'run-a', timestamp: '2026-01-01T00:00:00Z', status: 'passed', durationSeconds: 45, costUsd: 2.0 },
      ]},
      { spec: 'api.md', status: 'pending', source: 'define:session-1', workGroupId: 'wg-old' },
    ]);

    await writeJsonManifest(tmpDir, jsonManifest);

    // First access triggers auto-migration
    const manifest = await loadManifest(tmpDir);
    expect(manifest.specs).toHaveLength(2);
    expect(manifest.specs[0].spec).toBe('auth.md');
    expect(manifest.specs[0].status).toBe('passed');
    expect(manifest.specs[0].runs).toHaveLength(1);
    expect(manifest.specs[0].runs[0].costUsd).toBe(2.0);
    expect(manifest.specs[1].spec).toBe('api.md');
    expect(manifest.specs[1].workGroupId).toBe('wg-old');
  });

  test('migration is idempotent — running twice produces same result', async () => {
    const jsonManifest = makeManifest([
      { spec: 'idempotent.md', status: 'failed' },
    ]);
    await writeJsonManifest(tmpDir, jsonManifest);

    const first = await loadManifest(tmpDir);
    expect(first.specs).toHaveLength(1);

    // Force re-migration by clearing the in-memory tracking
    // (The actual code uses migratedDirs Set, but re-loading from a new process would check again)
    // Since we can't clear migratedDirs, let's verify DB state directly
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');
    const entries = listSpecEntries(db);
    expect(entries).toHaveLength(1);
    expect(entries[0].spec).toBe('idempotent.md');
    expect(entries[0].status).toBe('failed');
  });

  test('skips migration when DB already has entries', async () => {
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');

    // Pre-populate DB
    insertSpecEntry(db, { id: 'existing', spec: 'existing.md', status: 'passed' });

    // Write JSON with different content
    const jsonManifest = makeManifest([
      { spec: 'from-json.md', status: 'pending' },
    ]);
    await writeJsonManifest(tmpDir, jsonManifest);

    const manifest = await loadManifest(tmpDir);
    // Should still have only the DB entry, not the JSON one
    expect(manifest.specs).toHaveLength(1);
    expect(manifest.specs[0].spec).toBe('existing.md');
  });
});

// ── saveManifest ─────────────────────────────────────────────

describe('saveManifest writes to DB and exports JSON', () => {
  test('saves manifest to DB and writes JSON file', async () => {
    const manifest = makeManifest([
      { spec: 'saved.md', status: 'passed', source: 'file', runs: [
        { runId: 'r1', timestamp: '2026-01-01T00:00:00Z', status: 'passed', durationSeconds: 10 },
      ]},
    ]);

    await saveManifest(tmpDir, manifest);

    // Verify DB
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');
    const entries = listSpecEntries(db);
    expect(entries).toHaveLength(1);
    expect(entries[0].spec).toBe('saved.md');
    expect(entries[0].status).toBe('passed');

    // Verify run was saved
    const runs = getSpecRunsByEntry(db, entries[0].id);
    expect(runs).toHaveLength(1);

    // Verify JSON export
    const jsonPath = path.join(tmpDir, '.forge', 'specs.json');
    const jsonContent = JSON.parse(await fs.readFile(jsonPath, 'utf-8'));
    expect(jsonContent.version).toBe(1);
    expect(jsonContent.specs).toHaveLength(1);
    expect(jsonContent.specs[0].spec).toBe('saved.md');
  });

  test('JSON export preserves { version: 1, specs: [...] } format', async () => {
    const manifest = makeManifest([
      { spec: 'a.md', status: 'pending' },
      { spec: 'b.md', status: 'passed' },
    ]);

    await saveManifest(tmpDir, manifest);

    const jsonPath = path.join(tmpDir, '.forge', 'specs.json');
    const jsonContent = JSON.parse(await fs.readFile(jsonPath, 'utf-8'));
    expect(jsonContent).toHaveProperty('version', 1);
    expect(jsonContent).toHaveProperty('specs');
    expect(Array.isArray(jsonContent.specs)).toBe(true);
  });

  test('handles empty manifest', async () => {
    const manifest: SpecManifest = { version: 1, specs: [] };
    await saveManifest(tmpDir, manifest);

    const jsonPath = path.join(tmpDir, '.forge', 'specs.json');
    const jsonContent = JSON.parse(await fs.readFile(jsonPath, 'utf-8'));
    expect(jsonContent.specs).toEqual([]);
  });
});

// ── withSpecTransaction ──────────────────────────────────────

describe('withSpecTransaction', () => {
  test('loads from DB, applies updater, saves back to DB', async () => {
    // Seed DB with an entry
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');
    insertSpecEntry(db, { id: 'txn-entry', spec: 'txn.md', status: 'pending' });

    // Use withSpecTransaction to update
    await withSpecTransaction(tmpDir, (manifest) => {
      const entry = manifest.specs.find(e => e.spec === 'txn.md');
      expect(entry).toBeDefined();
      entry!.status = 'passed';
      entry!.updatedAt = new Date().toISOString();
    });

    // Verify DB was updated
    const updated = getSpecEntry(db, 'txn-entry');
    expect(updated!.status).toBe('passed');

    // Verify JSON was exported
    const jsonPath = path.join(tmpDir, '.forge', 'specs.json');
    const json = JSON.parse(await fs.readFile(jsonPath, 'utf-8'));
    expect(json.specs[0].status).toBe('passed');
  });

  test('adds new entries through updater', async () => {
    await withSpecTransaction(tmpDir, (manifest) => {
      findOrCreateEntry(manifest, 'new-spec.md', 'file');
    });

    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');
    const entries = listSpecEntries(db);
    expect(entries).toHaveLength(1);
    expect(entries[0].spec).toBe('new-spec.md');
    expect(entries[0].status).toBe('pending');
  });

  test('removes pruned entries from DB', async () => {
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');
    insertSpecEntry(db, { id: 'keep', spec: 'keep.md', status: 'passed' });
    insertSpecEntry(db, { id: 'remove', spec: 'remove.md', status: 'pending' });

    await withSpecTransaction(tmpDir, (manifest) => {
      manifest.specs = manifest.specs.filter(e => e.spec === 'keep.md');
    });

    const entries = listSpecEntries(db);
    expect(entries).toHaveLength(1);
    expect(entries[0].spec).toBe('keep.md');
  });

  test('concurrent transactions are serialized', async () => {
    // Run two transactions simultaneously
    const results: string[] = [];

    await Promise.all([
      withSpecTransaction(tmpDir, async (manifest) => {
        results.push('start-1');
        await new Promise(r => setTimeout(r, 10));
        findOrCreateEntry(manifest, 'concurrent-1.md', 'file');
        results.push('end-1');
      }),
      withSpecTransaction(tmpDir, async (manifest) => {
        results.push('start-2');
        await new Promise(r => setTimeout(r, 10));
        findOrCreateEntry(manifest, 'concurrent-2.md', 'file');
        results.push('end-2');
      }),
    ]);

    // Both entries should exist in DB
    const db = getDb(tmpDir);
    if (!db) throw new Error('DB unavailable');
    const entries = listSpecEntries(db);
    const specs = entries.map(e => e.spec);
    expect(specs).toContain('concurrent-1.md');
    expect(specs).toContain('concurrent-2.md');

    // Transactions should have been serialized (start-1, end-1, start-2, end-2 OR start-2, end-2, start-1, end-1)
    const firstEnd = results.indexOf('end-1');
    const secondStart = results.indexOf('start-2');
    const isSequential = firstEnd < secondStart ||
      results.indexOf('end-2') < results.indexOf('start-1');
    expect(isSequential).toBe(true);
  });
});

// ── findOrCreateEntry / updateEntryStatus ────────────────────

describe('findOrCreateEntry', () => {
  test('creates new entry when spec not found', () => {
    const manifest: SpecManifest = { version: 1, specs: [] };
    const entry = findOrCreateEntry(manifest, 'new.md', 'file');

    expect(entry.spec).toBe('new.md');
    expect(entry.status).toBe('pending');
    expect(entry.source).toBe('file');
    expect(entry.runs).toEqual([]);
    expect(manifest.specs).toHaveLength(1);
  });

  test('returns existing entry when spec exists', () => {
    const now = new Date().toISOString();
    const manifest: SpecManifest = {
      version: 1,
      specs: [{
        spec: 'existing.md',
        status: 'passed',
        runs: [{ runId: 'r1', timestamp: now, status: 'passed', durationSeconds: 10 }],
        source: 'file',
        createdAt: now,
        updatedAt: now,
      }],
    };

    const entry = findOrCreateEntry(manifest, 'existing.md', 'file');
    expect(entry.status).toBe('passed');
    expect(entry.runs).toHaveLength(1);
    expect(manifest.specs).toHaveLength(1); // No duplicate
  });

  test('assigns work group ID to existing entry when not set', () => {
    const now = new Date().toISOString();
    const manifest: SpecManifest = {
      version: 1,
      specs: [{
        spec: 'unlinked.md',
        status: 'pending',
        runs: [],
        source: 'file',
        createdAt: now,
        updatedAt: now,
      }],
    };

    const entry = findOrCreateEntry(manifest, 'unlinked.md', 'file', 'wg-new');
    expect(entry.workGroupId).toBe('wg-new');
  });

  test('does not overwrite existing work group ID', () => {
    const now = new Date().toISOString();
    const manifest: SpecManifest = {
      version: 1,
      specs: [{
        spec: 'linked.md',
        status: 'pending',
        runs: [],
        source: 'file',
        workGroupId: 'wg-original',
        createdAt: now,
        updatedAt: now,
      }],
    };

    const entry = findOrCreateEntry(manifest, 'linked.md', 'file', 'wg-new');
    expect(entry.workGroupId).toBe('wg-original');
  });
});

describe('updateEntryStatus', () => {
  test('sets status from latest run (passed)', () => {
    const now = new Date().toISOString();
    const entry: SpecEntry = {
      spec: 'test.md',
      status: 'pending',
      runs: [
        { runId: 'r1', timestamp: now, status: 'failed', durationSeconds: 10 },
        { runId: 'r2', timestamp: now, status: 'passed', durationSeconds: 20 },
      ],
      source: 'file',
      createdAt: now,
      updatedAt: now,
    };

    updateEntryStatus(entry);
    expect(entry.status).toBe('passed');
  });

  test('sets status from latest run (failed)', () => {
    const now = new Date().toISOString();
    const entry: SpecEntry = {
      spec: 'test.md',
      status: 'passed',
      runs: [
        { runId: 'r1', timestamp: now, status: 'passed', durationSeconds: 10 },
        { runId: 'r2', timestamp: now, status: 'failed', durationSeconds: 20 },
      ],
      source: 'file',
      createdAt: now,
      updatedAt: now,
    };

    updateEntryStatus(entry);
    expect(entry.status).toBe('failed');
  });

  test('reverts to pending when all runs removed', () => {
    const now = new Date().toISOString();
    const entry: SpecEntry = {
      spec: 'test.md',
      status: 'passed',
      runs: [],
      source: 'file',
      createdAt: now,
      updatedAt: now,
    };

    updateEntryStatus(entry);
    expect(entry.status).toBe('pending');
  });
});

// ── withManifestLock backward compat ─────────────────────────

describe('withManifestLock backward compatibility', () => {
  test('withManifestLock is an alias for withSpecTransaction', async () => {
    // Import the deprecated alias
    const { withManifestLock } = await import('./specs.js');
    expect(withManifestLock).toBe(withSpecTransaction);
  });
});
