// Generated by forge proof from spec-entries-schema.md, spec-manifest-db-migration.md
import { describe, test, expect, beforeEach } from 'bun:test';
import {
  getTestDb,
  getSchemaVersion,
  insertSpecEntry,
  getSpecEntry,
  getSpecEntryByPath,
  updateSpecEntryStatus,
  listSpecEntries,
  listSpecEntriesByWorkGroup,
  deleteSpecEntry,
  insertSpecRun,
  getSpecRunsByEntry,
  getLatestSpecRun,
} from './db.js';
import type { Database } from 'bun:sqlite';
import crypto from 'crypto';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function makeEntryId(): string {
  return crypto.randomUUID();
}

function makeRunId(): string {
  return crypto.randomUUID();
}

// ── Schema ──────────────────────────────────────────────────

describe('spec_entries schema', () => {
  test('schema version is 11 after all migrations', () => {
    expect(getSchemaVersion(db)).toBe(11);
  });

  test('spec_entries table exists with correct columns', () => {
    const cols = db.query("PRAGMA table_info(spec_entries)").all() as Array<{ name: string; type: string }>;
    const colNames = cols.map(c => c.name);
    expect(colNames).toContain('id');
    expect(colNames).toContain('spec');
    expect(colNames).toContain('status');
    expect(colNames).toContain('source');
    expect(colNames).toContain('work_group_id');
    expect(colNames).toContain('created_at');
    expect(colNames).toContain('updated_at');
  });

  test('spec_runs table exists with correct columns', () => {
    const cols = db.query("PRAGMA table_info(spec_runs)").all() as Array<{ name: string; type: string }>;
    const colNames = cols.map(c => c.name);
    expect(colNames).toContain('id');
    expect(colNames).toContain('spec_entry_id');
    expect(colNames).toContain('run_id');
    expect(colNames).toContain('timestamp');
    expect(colNames).toContain('status');
    expect(colNames).toContain('cost_usd');
    expect(colNames).toContain('duration_seconds');
    expect(colNames).toContain('num_turns');
    expect(colNames).toContain('verify_attempts');
  });

  test('indexes exist on spec_entries', () => {
    const indexes = db.query("PRAGMA index_list(spec_entries)").all() as Array<{ name: string }>;
    const names = indexes.map(i => i.name);
    expect(names).toContain('idx_spec_entries_status');
    expect(names).toContain('idx_spec_entries_work_group_id');
  });

  test('indexes exist on spec_runs', () => {
    const indexes = db.query("PRAGMA index_list(spec_runs)").all() as Array<{ name: string }>;
    const names = indexes.map(i => i.name);
    expect(names).toContain('idx_spec_runs_spec_entry_id');
    expect(names).toContain('idx_spec_runs_run_id');
  });

  test('spec column has UNIQUE constraint', () => {
    const id1 = makeEntryId();
    const id2 = makeEntryId();
    insertSpecEntry(db, { id: id1, spec: 'auth/login.md' });
    insertSpecEntry(db, { id: id2, spec: 'auth/login.md' });

    // Second insert should be ignored (INSERT OR IGNORE)
    const entries = listSpecEntries(db);
    const matching = entries.filter(e => e.spec === 'auth/login.md');
    expect(matching).toHaveLength(1);
    expect(matching[0].id).toBe(id1);
  });
});

// ── Spec Entry CRUD ─────────────────────────────────────────

describe('insertSpecEntry / getSpecEntry', () => {
  test('inserts and retrieves a spec entry by ID', () => {
    const id = makeEntryId();
    insertSpecEntry(db, { id, spec: 'auth/login.md', status: 'pending', source: 'define:session-1' });

    const entry = getSpecEntry(db, id);
    expect(entry).not.toBeNull();
    expect(entry!.id).toBe(id);
    expect(entry!.spec).toBe('auth/login.md');
    expect(entry!.status).toBe('pending');
    expect(entry!.source).toBe('define:session-1');
    expect(entry!.created_at).toBeTruthy();
    expect(entry!.updated_at).toBeTruthy();
  });

  test('defaults status to pending and source to file', () => {
    const id = makeEntryId();
    insertSpecEntry(db, { id, spec: 'feature.md' });

    const entry = getSpecEntry(db, id);
    expect(entry!.status).toBe('pending');
    expect(entry!.source).toBe('file');
  });

  test('stores work_group_id when provided', () => {
    const id = makeEntryId();
    insertSpecEntry(db, { id, spec: 'grouped.md', work_group_id: 'wg-123-abcd' });

    const entry = getSpecEntry(db, id);
    expect(entry!.work_group_id).toBe('wg-123-abcd');
  });

  test('work_group_id defaults to null', () => {
    const id = makeEntryId();
    insertSpecEntry(db, { id, spec: 'ungrouped.md' });

    const entry = getSpecEntry(db, id);
    expect(entry!.work_group_id).toBeNull();
  });

  test('returns null for non-existent ID', () => {
    expect(getSpecEntry(db, 'nonexistent')).toBeNull();
  });

  test('INSERT OR IGNORE skips duplicate IDs', () => {
    const id = makeEntryId();
    insertSpecEntry(db, { id, spec: 'first.md', status: 'pending' });
    insertSpecEntry(db, { id, spec: 'second.md', status: 'passed' });

    const entry = getSpecEntry(db, id);
    expect(entry!.spec).toBe('first.md');
    expect(entry!.status).toBe('pending');
  });
});

describe('getSpecEntryByPath', () => {
  test('retrieves entry by spec path', () => {
    const id = makeEntryId();
    insertSpecEntry(db, { id, spec: 'auth/login.md' });

    const entry = getSpecEntryByPath(db, 'auth/login.md');
    expect(entry).not.toBeNull();
    expect(entry!.id).toBe(id);
  });

  test('returns null for non-existent path', () => {
    expect(getSpecEntryByPath(db, 'no-such-spec.md')).toBeNull();
  });
});

describe('updateSpecEntryStatus', () => {
  test('updates status and refreshes updated_at', async () => {
    const id = makeEntryId();
    insertSpecEntry(db, { id, spec: 'update-test.md', status: 'pending' });

    const before = getSpecEntry(db, id)!;
    expect(before.status).toBe('pending');

    // Small delay to ensure timestamp differs
    await new Promise(r => setTimeout(r, 10));
    updateSpecEntryStatus(db, id, 'passed');

    const after = getSpecEntry(db, id)!;
    expect(after.status).toBe('passed');
    expect(after.updated_at >= before.updated_at).toBe(true);
  });
});

describe('listSpecEntries', () => {
  test('returns all entries ordered by created_at ASC', () => {
    insertSpecEntry(db, { id: makeEntryId(), spec: 'a.md', status: 'pending' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'b.md', status: 'passed' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'c.md', status: 'failed' });

    const entries = listSpecEntries(db);
    expect(entries).toHaveLength(3);
    expect(entries[0].spec).toBe('a.md');
    expect(entries[2].spec).toBe('c.md');
  });

  test('filters by status', () => {
    insertSpecEntry(db, { id: makeEntryId(), spec: 'pass1.md', status: 'passed' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'pass2.md', status: 'passed' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'pend1.md', status: 'pending' });

    const passed = listSpecEntries(db, { status: 'passed' });
    expect(passed).toHaveLength(2);
    expect(passed.every(e => e.status === 'passed')).toBe(true);
  });

  test('filters by work_group_id', () => {
    insertSpecEntry(db, { id: makeEntryId(), spec: 'wg1.md', work_group_id: 'wg-A' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'wg2.md', work_group_id: 'wg-A' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'wg3.md', work_group_id: 'wg-B' });

    const groupA = listSpecEntries(db, { work_group_id: 'wg-A' });
    expect(groupA).toHaveLength(2);
    expect(groupA.every(e => e.work_group_id === 'wg-A')).toBe(true);
  });

  test('filters by both status and work_group_id', () => {
    insertSpecEntry(db, { id: makeEntryId(), spec: 'both1.md', status: 'passed', work_group_id: 'wg-X' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'both2.md', status: 'pending', work_group_id: 'wg-X' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'both3.md', status: 'passed', work_group_id: 'wg-Y' });

    const result = listSpecEntries(db, { status: 'passed', work_group_id: 'wg-X' });
    expect(result).toHaveLength(1);
    expect(result[0].spec).toBe('both1.md');
  });

  test('returns empty array when no entries match', () => {
    expect(listSpecEntries(db, { status: 'nonexistent' })).toEqual([]);
  });
});

describe('listSpecEntriesByWorkGroup', () => {
  test('returns entries for a work group', () => {
    insertSpecEntry(db, { id: makeEntryId(), spec: 'g1.md', work_group_id: 'wg-test' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'g2.md', work_group_id: 'wg-test' });
    insertSpecEntry(db, { id: makeEntryId(), spec: 'other.md', work_group_id: 'wg-other' });

    const entries = listSpecEntriesByWorkGroup(db, 'wg-test');
    expect(entries).toHaveLength(2);
    expect(entries.every(e => e.work_group_id === 'wg-test')).toBe(true);
  });

  test('returns empty for non-existent work group', () => {
    expect(listSpecEntriesByWorkGroup(db, 'wg-nope')).toEqual([]);
  });
});

describe('deleteSpecEntry', () => {
  test('deletes entry and cascades to spec_runs', () => {
    const entryId = makeEntryId();
    insertSpecEntry(db, { id: entryId, spec: 'delete-me.md' });
    insertSpecRun(db, {
      id: makeRunId(),
      spec_entry_id: entryId,
      run_id: 'batch-1',
      timestamp: new Date().toISOString(),
      status: 'passed',
    });

    // Verify run exists
    expect(getSpecRunsByEntry(db, entryId)).toHaveLength(1);

    deleteSpecEntry(db, entryId);

    expect(getSpecEntry(db, entryId)).toBeNull();
    expect(getSpecRunsByEntry(db, entryId)).toHaveLength(0);
  });

  test('no-op for non-existent entry', () => {
    // Should not throw
    deleteSpecEntry(db, 'nonexistent-id');
  });
});

// ── Spec Run CRUD ────────────────────────────────────────────

describe('insertSpecRun / getSpecRunsByEntry', () => {
  test('inserts and retrieves runs ordered by timestamp DESC', () => {
    const entryId = makeEntryId();
    insertSpecEntry(db, { id: entryId, spec: 'runs-test.md' });

    insertSpecRun(db, {
      id: makeRunId(),
      spec_entry_id: entryId,
      run_id: 'batch-1',
      timestamp: '2026-01-01T00:00:00Z',
      status: 'failed',
      cost_usd: 1.5,
      duration_seconds: 120,
      num_turns: 10,
      verify_attempts: 2,
    });
    insertSpecRun(db, {
      id: makeRunId(),
      spec_entry_id: entryId,
      run_id: 'batch-2',
      timestamp: '2026-01-02T00:00:00Z',
      status: 'passed',
      cost_usd: 0.8,
      duration_seconds: 60,
    });

    const runs = getSpecRunsByEntry(db, entryId);
    expect(runs).toHaveLength(2);
    // Most recent first
    expect(runs[0].timestamp).toBe('2026-01-02T00:00:00Z');
    expect(runs[0].status).toBe('passed');
    expect(runs[1].timestamp).toBe('2026-01-01T00:00:00Z');
    expect(runs[1].status).toBe('failed');
    expect(runs[1].cost_usd).toBe(1.5);
    expect(runs[1].num_turns).toBe(10);
    expect(runs[1].verify_attempts).toBe(2);
  });

  test('returns empty array for entry with no runs', () => {
    const entryId = makeEntryId();
    insertSpecEntry(db, { id: entryId, spec: 'no-runs.md' });
    expect(getSpecRunsByEntry(db, entryId)).toEqual([]);
  });

  test('INSERT OR IGNORE skips duplicate run IDs', () => {
    const entryId = makeEntryId();
    const runId = makeRunId();
    insertSpecEntry(db, { id: entryId, spec: 'dup-run.md' });

    insertSpecRun(db, {
      id: runId,
      spec_entry_id: entryId,
      run_id: 'batch-1',
      timestamp: '2026-01-01T00:00:00Z',
      status: 'failed',
    });
    insertSpecRun(db, {
      id: runId,
      spec_entry_id: entryId,
      run_id: 'batch-2',
      timestamp: '2026-01-02T00:00:00Z',
      status: 'passed',
    });

    const runs = getSpecRunsByEntry(db, entryId);
    expect(runs).toHaveLength(1);
    expect(runs[0].status).toBe('failed');
  });

  test('nullable fields default to null', () => {
    const entryId = makeEntryId();
    insertSpecEntry(db, { id: entryId, spec: 'nullable.md' });

    insertSpecRun(db, {
      id: makeRunId(),
      spec_entry_id: entryId,
      run_id: 'batch-1',
      timestamp: '2026-01-01T00:00:00Z',
      status: 'passed',
    });

    const runs = getSpecRunsByEntry(db, entryId);
    expect(runs[0].cost_usd).toBeNull();
    expect(runs[0].duration_seconds).toBeNull();
    expect(runs[0].num_turns).toBeNull();
    expect(runs[0].verify_attempts).toBeNull();
  });
});

describe('getLatestSpecRun', () => {
  test('returns the most recent run', () => {
    const entryId = makeEntryId();
    insertSpecEntry(db, { id: entryId, spec: 'latest.md' });

    insertSpecRun(db, {
      id: makeRunId(),
      spec_entry_id: entryId,
      run_id: 'batch-old',
      timestamp: '2026-01-01T00:00:00Z',
      status: 'failed',
    });
    insertSpecRun(db, {
      id: makeRunId(),
      spec_entry_id: entryId,
      run_id: 'batch-new',
      timestamp: '2026-01-05T00:00:00Z',
      status: 'passed',
    });

    const latest = getLatestSpecRun(db, entryId);
    expect(latest).not.toBeNull();
    expect(latest!.run_id).toBe('batch-new');
    expect(latest!.status).toBe('passed');
  });

  test('returns null when no runs exist', () => {
    const entryId = makeEntryId();
    insertSpecEntry(db, { id: entryId, spec: 'no-runs-latest.md' });
    expect(getLatestSpecRun(db, entryId)).toBeNull();
  });

  test('returns null for non-existent entry', () => {
    expect(getLatestSpecRun(db, 'nonexistent')).toBeNull();
  });
});
