// Generated by forge proof from structured-event-log.md
import { describe, test, expect, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import type {
  SessionEvent,
  SessionStartEvent,
  SessionEndEvent,
  TextDeltaEvent,
  ThinkingDeltaEvent,
  ToolCallStartEvent,
  ToolCallResultEvent,
} from './types.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-sel-test-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
});

function makeSessionStart(overrides: Partial<SessionStartEvent> = {}): SessionStartEvent {
  return {
    type: 'session_start',
    timestamp: '2026-01-01T00:00:00.000Z',
    sessionId: 'test-session-001',
    model: 'sonnet',
    prompt: 'test prompt',
    ...overrides,
  };
}

function makeSessionEnd(overrides: Partial<SessionEndEvent> = {}): SessionEndEvent {
  return {
    type: 'session_end',
    timestamp: '2026-01-01T00:01:00.000Z',
    durationSeconds: 60,
    status: 'success',
    ...overrides,
  };
}

function makeTextDelta(overrides: Partial<TextDeltaEvent> = {}): TextDeltaEvent {
  return {
    type: 'text_delta',
    timestamp: '2026-01-01T00:00:30.000Z',
    content: 'Agent reasoning text.',
    ...overrides,
  };
}

function makeThinkingDelta(overrides: Partial<ThinkingDeltaEvent> = {}): ThinkingDeltaEvent {
  return {
    type: 'thinking_delta',
    timestamp: '2026-01-01T00:00:15.000Z',
    content: 'Extended thinking block content.',
    ...overrides,
  };
}

function makeToolCallStart(overrides: Partial<ToolCallStartEvent> = {}): ToolCallStartEvent {
  return {
    type: 'tool_call_start',
    timestamp: '2026-01-01T00:00:20.000Z',
    toolName: 'Bash',
    input: { command: 'echo hello' },
    ...overrides,
  };
}

function makeToolCallResult(overrides: Partial<ToolCallResultEvent> = {}): ToolCallResultEvent {
  return {
    type: 'tool_call_result',
    timestamp: '2026-01-01T00:00:21.000Z',
    toolName: 'Bash',
    output: 'hello\n',
    ...overrides,
  };
}

async function writeEventsJsonl(dir: string, sessionId: string, events: SessionEvent[]): Promise<string> {
  const sessionDir = path.join(dir, '.forge', 'sessions', sessionId);
  await fs.mkdir(sessionDir, { recursive: true });
  const eventsPath = path.join(sessionDir, 'events.jsonl');
  const jsonl = events.map(e => JSON.stringify(e)).join('\n') + '\n';
  await fs.writeFile(eventsPath, jsonl);
  return eventsPath;
}

function parseJsonl(content: string): SessionEvent[] {
  const parsed: SessionEvent[] = [];
  for (const line of content.split('\n')) {
    if (!line.trim()) continue;
    try {
      parsed.push(JSON.parse(line));
    } catch { /* skip malformed */ }
  }
  return parsed;
}

// ── events.jsonl file creation ──────────────────────────────

describe('structured event log: events.jsonl file', () => {
  test('events.jsonl is written to .forge/sessions/{sessionId}/', async () => {
    const dir = await makeTmpDir();
    const sessionId = 'sess-001';
    const events: SessionEvent[] = [makeSessionStart({ sessionId })];
    const eventsPath = await writeEventsJsonl(dir, sessionId, events);

    const exists = await fs.access(eventsPath).then(() => true).catch(() => false);
    expect(exists).toBe(true);
    expect(eventsPath).toContain(path.join('.forge', 'sessions', sessionId, 'events.jsonl'));
  });

  test('events.jsonl lives alongside stream.log in same session dir', async () => {
    const dir = await makeTmpDir();
    const sessionId = 'sess-002';
    const sessionDir = path.join(dir, '.forge', 'sessions', sessionId);
    await fs.mkdir(sessionDir, { recursive: true });

    // Write both files
    const streamLogPath = path.join(sessionDir, 'stream.log');
    await fs.writeFile(streamLogPath, '[2026-01-01T00:00:00Z] Session started\n');
    await writeEventsJsonl(dir, sessionId, [makeSessionStart({ sessionId })]);

    const streamExists = await fs.access(streamLogPath).then(() => true).catch(() => false);
    const eventsExists = await fs.access(path.join(sessionDir, 'events.jsonl')).then(() => true).catch(() => false);
    expect(streamExists).toBe(true);
    expect(eventsExists).toBe(true);
  });
});

// ── session_start event ─────────────────────────────────────

describe('structured event log: session_start event', () => {
  test('session_start event written first with required fields', async () => {
    const dir = await makeTmpDir();
    const sessionId = 'start-test';
    const startEvent = makeSessionStart({
      sessionId,
      model: 'opus',
      prompt: 'implement auth',
      specPath: 'specs/auth.md',
    });
    const eventsPath = await writeEventsJsonl(dir, sessionId, [startEvent]);

    const content = await fs.readFile(eventsPath, 'utf-8');
    const events = parseJsonl(content);
    expect(events.length).toBeGreaterThanOrEqual(1);

    const first = events[0] as SessionStartEvent;
    expect(first.type).toBe('session_start');
    expect(first.timestamp).toBeTruthy();
    expect(first.sessionId).toBe(sessionId);
    expect(first.model).toBe('opus');
    expect(first.prompt).toBe('implement auth');
    expect(first.specPath).toBe('specs/auth.md');
  });

  test('session_start includes commandType from sessionExtra', async () => {
    const dir = await makeTmpDir();
    const startEvent = makeSessionStart({
      sessionId: 'cmdtype-test',
      commandType: 'audit',
    });
    await writeEventsJsonl(dir, 'cmdtype-test', [startEvent]);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'cmdtype-test', 'events.jsonl'),
      'utf-8',
    );
    const events = parseJsonl(content);
    const first = events[0] as SessionStartEvent;
    expect(first.commandType).toBe('audit');
  });
});

// ── thinking_delta events ───────────────────────────────────

describe('structured event log: thinking_delta events', () => {
  test('thinking_delta captures extended thinking content', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'think-1' }),
      makeThinkingDelta({ content: 'Let me analyze the auth module...' }),
      makeSessionEnd(),
    ];
    const eventsPath = await writeEventsJsonl(dir, 'think-1', events);

    const content = await fs.readFile(eventsPath, 'utf-8');
    const parsed = parseJsonl(content);
    const thinking = parsed.find(e => e.type === 'thinking_delta') as ThinkingDeltaEvent;
    expect(thinking).toBeDefined();
    expect(thinking.content).toBe('Let me analyze the auth module...');
    expect(thinking.timestamp).toBeTruthy();
  });

  test('multiple thinking_delta events preserved in order', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'think-multi' }),
      makeThinkingDelta({ content: 'Step 1: read files', timestamp: '2026-01-01T00:00:01Z' }),
      makeThinkingDelta({ content: 'Step 2: design approach', timestamp: '2026-01-01T00:00:02Z' }),
      makeThinkingDelta({ content: 'Step 3: implement', timestamp: '2026-01-01T00:00:03Z' }),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'think-multi', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'think-multi', 'events.jsonl'),
      'utf-8',
    );
    const parsed = parseJsonl(content);
    const thinkEvents = parsed.filter(e => e.type === 'thinking_delta') as ThinkingDeltaEvent[];
    expect(thinkEvents).toHaveLength(3);
    expect(thinkEvents[0].content).toBe('Step 1: read files');
    expect(thinkEvents[2].content).toBe('Step 3: implement');
  });
});

// ── tool_call_start events ──────────────────────────────────

describe('structured event log: tool_call_start events', () => {
  test('tool_call_start captures tool name and full input object', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'tool-start-1' }),
      makeToolCallStart({
        toolName: 'Edit',
        toolUseId: 'tu-abc',
        input: { file_path: 'src/core.ts', old_string: 'foo', new_string: 'bar' },
      }),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'tool-start-1', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'tool-start-1', 'events.jsonl'),
      'utf-8',
    );
    const parsed = parseJsonl(content);
    const tool = parsed.find(e => e.type === 'tool_call_start') as ToolCallStartEvent;
    expect(tool).toBeDefined();
    expect(tool.toolName).toBe('Edit');
    expect(tool.toolUseId).toBe('tu-abc');
    expect(tool.input).toEqual({
      file_path: 'src/core.ts',
      old_string: 'foo',
      new_string: 'bar',
    });
  });

  test('tool_call_start with complex Bash input', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'bash-input' }),
      makeToolCallStart({
        toolName: 'Bash',
        input: { command: 'npm run build && npm test', description: 'Build and test', timeout: 60000 },
      }),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'bash-input', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'bash-input', 'events.jsonl'),
      'utf-8',
    );
    const parsed = parseJsonl(content);
    const tool = parsed.find(e => e.type === 'tool_call_start') as ToolCallStartEvent;
    expect(tool.input.command).toBe('npm run build && npm test');
    expect(tool.input.description).toBe('Build and test');
    expect(tool.input.timeout).toBe(60000);
  });
});

// ── tool_call_result events ─────────────────────────────────

describe('structured event log: tool_call_result events', () => {
  test('tool_call_result captures tool output from PostToolUse hook', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'result-1' }),
      makeToolCallStart({ toolName: 'Bash', toolUseId: 'tu-r1' }),
      makeToolCallResult({ toolName: 'Bash', toolUseId: 'tu-r1', output: 'Build succeeded.\n' }),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'result-1', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'result-1', 'events.jsonl'),
      'utf-8',
    );
    const parsed = parseJsonl(content);
    const result = parsed.find(e => e.type === 'tool_call_result') as ToolCallResultEvent;
    expect(result).toBeDefined();
    expect(result.toolName).toBe('Bash');
    expect(result.toolUseId).toBe('tu-r1');
    expect(result.output).toBe('Build succeeded.\n');
  });

  test('tool_call_start and tool_call_result are paired by toolUseId', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'pair-1' }),
      makeToolCallStart({ toolName: 'Read', toolUseId: 'tu-p1', input: { file_path: 'a.ts' } }),
      makeToolCallResult({ toolName: 'Read', toolUseId: 'tu-p1', output: 'file content' }),
      makeToolCallStart({ toolName: 'Edit', toolUseId: 'tu-p2', input: { file_path: 'b.ts' } }),
      makeToolCallResult({ toolName: 'Edit', toolUseId: 'tu-p2', output: 'edit applied' }),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'pair-1', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'pair-1', 'events.jsonl'),
      'utf-8',
    );
    const parsed = parseJsonl(content);
    const starts = parsed.filter(e => e.type === 'tool_call_start') as ToolCallStartEvent[];
    const results = parsed.filter(e => e.type === 'tool_call_result') as ToolCallResultEvent[];
    expect(starts).toHaveLength(2);
    expect(results).toHaveLength(2);
    expect(starts[0].toolUseId).toBe(results[0].toolUseId);
    expect(starts[1].toolUseId).toBe(results[1].toolUseId);
  });
});

// ── session_end event ───────────────────────────────────────

describe('structured event log: session_end event', () => {
  test('session_end written on completion with required fields', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'end-1' }),
      makeSessionEnd({
        numTurns: 15,
        costUsd: 1.25,
        durationSeconds: 120,
        status: 'success',
      }),
    ];
    await writeEventsJsonl(dir, 'end-1', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'end-1', 'events.jsonl'),
      'utf-8',
    );
    const parsed = parseJsonl(content);
    const end = parsed.find(e => e.type === 'session_end') as SessionEndEvent;
    expect(end).toBeDefined();
    expect(end.type).toBe('session_end');
    expect(end.timestamp).toBeTruthy();
    expect(end.numTurns).toBe(15);
    expect(end.costUsd).toBe(1.25);
    expect(end.durationSeconds).toBe(120);
    expect(end.status).toBe('success');
  });

  test('session_end status captures error conditions', async () => {
    const dir = await makeTmpDir();
    for (const status of ['error_execution', 'error_max_turns', 'error_budget'] as const) {
      const sid = `err-${status}`;
      const events: SessionEvent[] = [
        makeSessionStart({ sessionId: sid }),
        makeSessionEnd({ status, durationSeconds: 30 }),
      ];
      await writeEventsJsonl(dir, sid, events);

      const content = await fs.readFile(
        path.join(dir, '.forge', 'sessions', sid, 'events.jsonl'),
        'utf-8',
      );
      const parsed = parseJsonl(content);
      const end = parsed.find(e => e.type === 'session_end') as SessionEndEvent;
      expect(end.status).toBe(status);
    }
  });
});

// ── JSONL format and parsing ────────────────────────────────

describe('structured event log: JSONL format', () => {
  test('each line is valid JSON', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'jsonl-1' }),
      makeTextDelta({ content: 'Hello world' }),
      makeToolCallStart({ toolName: 'Bash', input: { command: 'ls' } }),
      makeToolCallResult({ toolName: 'Bash', output: 'file1.ts\nfile2.ts' }),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'jsonl-1', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'jsonl-1', 'events.jsonl'),
      'utf-8',
    );
    const lines = content.split('\n').filter(l => l.trim());
    for (const line of lines) {
      expect(() => JSON.parse(line)).not.toThrow();
    }
  });

  test('all events share type and timestamp fields', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'shared-1' }),
      makeThinkingDelta(),
      makeTextDelta(),
      makeToolCallStart(),
      makeToolCallResult(),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'shared-1', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'shared-1', 'events.jsonl'),
      'utf-8',
    );
    const parsed = parseJsonl(content);
    expect(parsed).toHaveLength(6);
    for (const event of parsed) {
      expect(event.type).toBeTruthy();
      expect(event.timestamp).toBeTruthy();
    }
  });

  test('events are line-delimited (one per line)', async () => {
    const dir = await makeTmpDir();
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId: 'lines-1' }),
      makeTextDelta({ content: 'line 1' }),
      makeTextDelta({ content: 'line 2' }),
      makeSessionEnd(),
    ];
    await writeEventsJsonl(dir, 'lines-1', events);

    const content = await fs.readFile(
      path.join(dir, '.forge', 'sessions', 'lines-1', 'events.jsonl'),
      'utf-8',
    );
    const lines = content.split('\n').filter(l => l.trim());
    expect(lines).toHaveLength(4);
  });

  test('malformed lines are skippable during parsing', () => {
    const content = [
      JSON.stringify(makeSessionStart()),
      'not-json <<<',
      '',
      JSON.stringify(makeSessionEnd()),
    ].join('\n');

    const parsed = parseJsonl(content);
    expect(parsed).toHaveLength(2);
    expect(parsed[0].type).toBe('session_start');
    expect(parsed[1].type).toBe('session_end');
  });
});

// ── stream.log backward compatibility ───────────────────────

describe('structured event log: stream.log unchanged', () => {
  test('stream.log continues to be written alongside events.jsonl', async () => {
    const dir = await makeTmpDir();
    const sessionId = 'both-logs';
    const sessionDir = path.join(dir, '.forge', 'sessions', sessionId);
    await fs.mkdir(sessionDir, { recursive: true });

    // Simulate both logs being written
    await fs.writeFile(path.join(sessionDir, 'stream.log'), '[ts] Session started\n');
    await writeEventsJsonl(dir, sessionId, [makeSessionStart({ sessionId })]);

    const streamExists = await fs.access(path.join(sessionDir, 'stream.log')).then(() => true).catch(() => false);
    const eventsExists = await fs.access(path.join(sessionDir, 'events.jsonl')).then(() => true).catch(() => false);
    expect(streamExists).toBe(true);
    expect(eventsExists).toBe(true);
  });
});

// ── Full session roundtrip ──────────────────────────────────

describe('structured event log: full session roundtrip', () => {
  test('complete session event sequence writes and parses correctly', async () => {
    const dir = await makeTmpDir();
    const sessionId = 'roundtrip-1';
    const events: SessionEvent[] = [
      makeSessionStart({ sessionId, model: 'opus', prompt: 'build auth', specPath: 'auth.md' }),
      makeThinkingDelta({ content: 'Planning the auth module...' }),
      makeTextDelta({ content: 'I will implement JWT auth.' }),
      makeToolCallStart({ toolName: 'Read', toolUseId: 'tu-1', input: { file_path: 'src/auth.ts' } }),
      makeToolCallResult({ toolName: 'Read', toolUseId: 'tu-1', output: 'export function login() {}' }),
      makeToolCallStart({ toolName: 'Edit', toolUseId: 'tu-2', input: { file_path: 'src/auth.ts', old_string: '{}', new_string: '{ return jwt; }' } }),
      makeToolCallResult({ toolName: 'Edit', toolUseId: 'tu-2', output: 'Edit applied.' }),
      makeToolCallStart({ toolName: 'Bash', toolUseId: 'tu-3', input: { command: 'npm test' } }),
      makeToolCallResult({ toolName: 'Bash', toolUseId: 'tu-3', output: 'All tests passed.' }),
      makeTextDelta({ content: 'Auth module implemented successfully.' }),
      makeSessionEnd({ numTurns: 5, costUsd: 2.50, durationSeconds: 180, status: 'success' }),
    ];

    const eventsPath = await writeEventsJsonl(dir, sessionId, events);
    const content = await fs.readFile(eventsPath, 'utf-8');
    const parsed = parseJsonl(content);

    expect(parsed).toHaveLength(11);
    expect(parsed[0].type).toBe('session_start');
    expect(parsed[parsed.length - 1].type).toBe('session_end');

    // Verify discriminated union types parsed correctly
    const types = parsed.map(e => e.type);
    expect(types).toEqual([
      'session_start',
      'thinking_delta',
      'text_delta',
      'tool_call_start',
      'tool_call_result',
      'tool_call_start',
      'tool_call_result',
      'tool_call_start',
      'tool_call_result',
      'text_delta',
      'session_end',
    ]);
  });
});
