// Generated by forge proof from tool-block-focus.md, tool-block-expand-toggle.md, tool-block-expanded-content.md
import { describe, test, expect } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import type { ToolCallStartEvent, ToolCallResultEvent } from './types.js';

// ── Helpers ──────────────────────────────────────────────────

function makeToolStart(overrides: Partial<ToolCallStartEvent> = {}): ToolCallStartEvent {
  return {
    type: 'tool_call_start',
    timestamp: '2026-01-01T00:00:00Z',
    toolName: 'Bash',
    input: { command: 'echo hello' },
    ...overrides,
  };
}

function makeToolResult(overrides: Partial<ToolCallResultEvent> = {}): ToolCallResultEvent {
  return {
    type: 'tool_call_result',
    timestamp: '2026-01-01T00:00:01Z',
    toolName: 'Bash',
    output: 'hello\n',
    ...overrides,
  };
}

interface ToolBlock {
  start: ToolCallStartEvent;
  result?: ToolCallResultEvent;
}

function makeToolBlock(toolName: string, input: Record<string, unknown>, output: string, toolUseId?: string): ToolBlock {
  return {
    start: makeToolStart({ toolName, toolUseId, input }),
    result: makeToolResult({ toolName, toolUseId, output }),
  };
}

// ── Tool block focus tracking ───────────────────────────────

describe('tool block focus: state tracking', () => {
  test('focusedToolIndex starts at -1 or 0', () => {
    // Initial state: no tool focused or first tool focused
    const focusedToolIndex = -1;
    expect(focusedToolIndex).toBeLessThanOrEqual(0);
  });

  test('n advances focusedToolIndex forward', () => {
    const toolBlockIndices = [0, 3, 7, 12]; // indices of tool blocks in grouped blocks
    let focusedToolIndex = 0;

    // Press n
    focusedToolIndex = Math.min(focusedToolIndex + 1, toolBlockIndices.length - 1);
    expect(focusedToolIndex).toBe(1);

    // Press n again
    focusedToolIndex = Math.min(focusedToolIndex + 1, toolBlockIndices.length - 1);
    expect(focusedToolIndex).toBe(2);
  });

  test('N moves focusedToolIndex backward', () => {
    const toolBlockIndices = [0, 3, 7, 12];
    let focusedToolIndex = 3;

    // Press N
    focusedToolIndex = Math.max(focusedToolIndex - 1, 0);
    expect(focusedToolIndex).toBe(2);

    // Press N again
    focusedToolIndex = Math.max(focusedToolIndex - 1, 0);
    expect(focusedToolIndex).toBe(1);
  });

  test('focusedToolIndex clamps at end of list', () => {
    const toolBlockIndices = [0, 3, 7];
    let focusedToolIndex = 2; // last index

    // Press n at end
    focusedToolIndex = Math.min(focusedToolIndex + 1, toolBlockIndices.length - 1);
    expect(focusedToolIndex).toBe(2); // clamped
  });

  test('focusedToolIndex clamps at start of list', () => {
    let focusedToolIndex = 0;

    // Press N at start
    focusedToolIndex = Math.max(focusedToolIndex - 1, 0);
    expect(focusedToolIndex).toBe(0); // clamped
  });

  test('focus persists across j/k manual scroll', () => {
    let focusedToolIndex = 2;
    // j/k scroll does not clear focus
    const scrollOffset = 10; // manual scroll happened
    expect(focusedToolIndex).toBe(2); // unchanged
  });

  test('focus clamps when blocks list shrinks', () => {
    let focusedToolIndex = 5;
    const newToolBlockCount = 3;

    // Clamp to new bounds
    focusedToolIndex = Math.min(focusedToolIndex, newToolBlockCount - 1);
    expect(focusedToolIndex).toBe(2);
  });
});

// ── Tool block focus: visual highlight ──────────────────────

describe('tool block focus: visual highlight', () => {
  test('focused tool block uses > prefix indicator', () => {
    const isFocused = true;
    const prefix = isFocused ? '>' : ' ';
    expect(prefix).toBe('>');
  });

  test('unfocused tool block uses space prefix', () => {
    const isFocused = false;
    const prefix = isFocused ? '>' : ' ';
    expect(prefix).toBe(' ');
  });
});

// ── Tool block expand/collapse toggle ───────────────────────

describe('tool block expand: toggle state', () => {
  test('expanded set tracks which blocks are expanded', () => {
    const expandedSet = new Set<number>();
    expect(expandedSet.size).toBe(0);

    // Toggle expand
    expandedSet.add(2);
    expect(expandedSet.has(2)).toBe(true);

    // Toggle collapse
    expandedSet.delete(2);
    expect(expandedSet.has(2)).toBe(false);
  });

  test('Enter toggles between expanded and collapsed', () => {
    const expandedSet = new Set<number>();
    const focusedIndex = 3;

    // First Enter: expand
    if (expandedSet.has(focusedIndex)) {
      expandedSet.delete(focusedIndex);
    } else {
      expandedSet.add(focusedIndex);
    }
    expect(expandedSet.has(focusedIndex)).toBe(true);

    // Second Enter: collapse
    if (expandedSet.has(focusedIndex)) {
      expandedSet.delete(focusedIndex);
    } else {
      expandedSet.add(focusedIndex);
    }
    expect(expandedSet.has(focusedIndex)).toBe(false);
  });

  test('collapse indicator: + collapsed, - expanded', () => {
    const isExpanded = false;
    expect(isExpanded ? '-' : '+').toBe('+');

    const isExpanded2 = true;
    expect(isExpanded2 ? '-' : '+').toBe('-');
  });

  test('multiple blocks can be expanded simultaneously', () => {
    const expandedSet = new Set<number>();
    expandedSet.add(1);
    expandedSet.add(3);
    expandedSet.add(5);

    expect(expandedSet.size).toBe(3);
    expect(expandedSet.has(1)).toBe(true);
    expect(expandedSet.has(3)).toBe(true);
    expect(expandedSet.has(5)).toBe(true);
    expect(expandedSet.has(2)).toBe(false);
  });
});

// ── Expanded content rendering ──────────────────────────────

describe('tool block expanded: content rendering', () => {
  test('tool input rendered as key-value pairs', () => {
    const input: Record<string, unknown> = {
      file_path: 'src/core.ts',
      old_string: 'function foo() {}',
      new_string: 'function bar() {}',
    };

    const lines: string[] = [];
    for (const [key, value] of Object.entries(input)) {
      const display = typeof value === 'string' ? value : JSON.stringify(value);
      lines.push(`  ${key}: ${display}`);
    }

    expect(lines).toHaveLength(3);
    expect(lines[0]).toContain('file_path');
    expect(lines[0]).toContain('src/core.ts');
    expect(lines[1]).toContain('old_string');
    expect(lines[2]).toContain('new_string');
  });

  test('non-string input values are JSON-stringified', () => {
    const input: Record<string, unknown> = {
      timeout: 60000,
      recursive: true,
      items: ['a', 'b'],
    };

    for (const [key, value] of Object.entries(input)) {
      const display = typeof value === 'string' ? value : JSON.stringify(value);
      expect(typeof display).toBe('string');
    }

    expect(JSON.stringify(input.timeout)).toBe('60000');
    expect(JSON.stringify(input.recursive)).toBe('true');
    expect(JSON.stringify(input.items)).toBe('["a","b"]');
  });

  test('full tool output rendered preserving newlines', () => {
    const output = 'Line 1\nLine 2\nLine 3\n  indented\n';
    const lines = output.split('\n');
    expect(lines.length).toBeGreaterThan(1);
    expect(lines[0]).toBe('Line 1');
    expect(lines[3]).toBe('  indented');
  });

  test('expanded view replaces 120-char preview with full output', () => {
    const fullOutput = 'A'.repeat(500);
    const preview = fullOutput.slice(0, 120) + '...';

    // In collapsed mode: preview
    expect(preview.length).toBe(123);
    // In expanded mode: full output
    expect(fullOutput.length).toBe(500);
  });

  test('tool input rendering handles all common tool types', () => {
    const toolInputs: Array<{ toolName: string; input: Record<string, unknown> }> = [
      { toolName: 'Bash', input: { command: 'npm test', description: 'Run tests' } },
      { toolName: 'Read', input: { file_path: 'src/core.ts', offset: 10, limit: 50 } },
      { toolName: 'Write', input: { file_path: 'src/new.ts', content: 'export const x = 1;' } },
      { toolName: 'Edit', input: { file_path: 'src/core.ts', old_string: 'foo', new_string: 'bar' } },
      { toolName: 'Grep', input: { pattern: 'runQuery', path: 'src/', glob: '*.ts' } },
      { toolName: 'Glob', input: { pattern: '**/*.test.ts' } },
      { toolName: 'WebFetch', input: { url: 'https://example.com', prompt: 'summarize' } },
    ];

    for (const { toolName, input } of toolInputs) {
      const entries = Object.entries(input);
      expect(entries.length).toBeGreaterThan(0);
      // Every tool input can be rendered as key-value pairs
      for (const [key, value] of entries) {
        const display = typeof value === 'string' ? value : JSON.stringify(value);
        expect(typeof display).toBe('string');
        expect(display.length).toBeGreaterThan(0);
      }
    }
  });

  test('empty input object renders no key-value pairs', () => {
    const input: Record<string, unknown> = {};
    const entries = Object.entries(input);
    expect(entries).toHaveLength(0);
  });

  test('empty output renders without error', () => {
    const output = '';
    expect(output.length).toBe(0);
    // Should not crash when rendering empty output
    expect(output.split('\n')).toEqual(['']);
  });
});
