// Generated by forge proof from forge-tui-sessions.md, tui-view-switcher.md, tui-specs-list.md, tui-spec-detail.md, tool-block-focus.md, tool-block-expand-toggle.md, tool-block-expanded-content.md
import { describe, test, expect, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import type { ForgeResult, SessionEvent, SpecManifest, SpecEntry, SpecRun } from './types.js';
import { loadManifest } from './specs.js';

// ── Helpers ──────────────────────────────────────────────────

let tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const raw = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-tui-test-'));
  const dir = await fs.realpath(raw);
  tmpDirs.push(dir);
  return dir;
}

afterEach(async () => {
  for (const d of tmpDirs) {
    await fs.rm(d, { recursive: true, force: true }).catch(() => {});
  }
  tmpDirs = [];
});

function makeSummary(overrides: Partial<ForgeResult> = {}): ForgeResult {
  return {
    startedAt: '2026-01-01T00:00:00Z',
    completedAt: '2026-01-01T00:01:00Z',
    durationSeconds: 60,
    status: 'success',
    prompt: 'test prompt',
    model: 'sonnet',
    cwd: '/test',
    ...overrides,
  };
}

function makeEntry(overrides: Partial<SpecEntry> = {}): SpecEntry {
  return {
    spec: 'feature.md',
    status: 'passed',
    runs: [],
    source: 'file',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    ...overrides,
  };
}

function makeRun(overrides: Partial<SpecRun> = {}): SpecRun {
  return {
    runId: 'run-1',
    timestamp: '2026-01-01T00:00:00Z',
    resultPath: '.forge/results/2026-01-01T00-00-00Z',
    status: 'passed',
    costUsd: 0.5,
    durationSeconds: 60,
    ...overrides,
  };
}

async function setupForge(dir: string, manifest?: SpecManifest): Promise<void> {
  const forgeDir = path.join(dir, '.forge');
  await fs.mkdir(forgeDir, { recursive: true });
  if (manifest) {
    await fs.writeFile(path.join(forgeDir, 'specs.json'), JSON.stringify(manifest));
  }
}

async function setupResults(dir: string, results: Array<{ ts: string; summary: ForgeResult }>): Promise<void> {
  const resultsDir = path.join(dir, '.forge', 'results');
  for (const { ts, summary } of results) {
    const runDir = path.join(resultsDir, ts);
    await fs.mkdir(runDir, { recursive: true });
    await fs.writeFile(path.join(runDir, 'summary.json'), JSON.stringify(summary));
  }
}

async function setupSession(dir: string, sessionId: string, events: SessionEvent[]): Promise<string> {
  const sessionDir = path.join(dir, '.forge', 'sessions', sessionId);
  await fs.mkdir(sessionDir, { recursive: true });
  const eventsPath = path.join(sessionDir, 'events.jsonl');
  const streamPath = path.join(sessionDir, 'stream.log');
  await fs.writeFile(eventsPath, events.map(e => JSON.stringify(e)).join('\n'));
  await fs.writeFile(streamPath, '[Session started]\n');
  return eventsPath;
}

/**
 * Replicate the groupEvents logic from tui.tsx for testing.
 * Groups flat events into tool blocks, text blocks, and session dividers.
 */
interface ToolBlock { kind: 'tool'; start: SessionEvent; result?: SessionEvent }
interface TextBlock { kind: 'text'; content: string; timestamp: string }
interface SessionStartBlock { kind: 'session_start'; event: SessionEvent }
interface SessionEndBlock { kind: 'session_end'; event: SessionEvent }
type GroupedBlock = ToolBlock | TextBlock | SessionStartBlock | SessionEndBlock;

function groupEvents(events: SessionEvent[]): GroupedBlock[] {
  const blocks: GroupedBlock[] = [];
  let textParts: string[] = [];
  let textTimestamp = '';
  const pendingById = new Map<string, number>();
  const pendingQueue: number[] = [];

  const flushText = () => {
    if (textParts.length > 0) {
      blocks.push({ kind: 'text', content: textParts.join(''), timestamp: textTimestamp });
      textParts = [];
      textTimestamp = '';
    }
  };

  for (const event of events) {
    switch (event.type) {
      case 'session_start':
        flushText();
        blocks.push({ kind: 'session_start', event });
        break;
      case 'session_end':
        flushText();
        blocks.push({ kind: 'session_end', event });
        break;
      case 'text_delta':
        if (textParts.length === 0) textTimestamp = event.timestamp;
        textParts.push(event.content);
        break;
      case 'thinking_delta':
        // Hidden by default
        break;
      case 'tool_call_start': {
        flushText();
        const idx = blocks.length;
        blocks.push({ kind: 'tool', start: event });
        if (event.toolUseId) {
          pendingById.set(event.toolUseId, idx);
        } else {
          pendingQueue.push(idx);
        }
        break;
      }
      case 'tool_call_result': {
        if (event.toolUseId && pendingById.has(event.toolUseId)) {
          const idx = pendingById.get(event.toolUseId)!;
          (blocks[idx] as ToolBlock).result = event;
          pendingById.delete(event.toolUseId);
        } else if (pendingQueue.length > 0) {
          const idx = pendingQueue.shift()!;
          (blocks[idx] as ToolBlock).result = event;
        }
        break;
      }
    }
  }
  flushText();
  return blocks;
}

// ── TUI module exports ───────────────────────────────────────

describe('TUI module and CLI registration', () => {
  test('runTui is exported from tui.tsx', async () => {
    const mod = await import('./tui.js');
    expect(typeof mod.runTui).toBe('function');
  });

  test('tui command is registered in CLI', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    expect(indexContent).toContain(".command('tui')");
  });

  test('tui command has no required args (optional cwd only)', async () => {
    const indexContent = await fs.readFile(path.join(import.meta.dirname, 'index.ts'), 'utf-8');
    // Should have -C flag but no required argument
    expect(indexContent).toContain("'Interactive sessions viewer'");
  });
});

// ── Session list: data loading from .forge/results/ ──────────

describe('session list data loading', () => {
  test('sessions populated from summary.json files sorted by recency', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);
    await setupResults(dir, [
      { ts: '2026-01-01T00-00-00Z', summary: makeSummary({ sessionId: 's1', startedAt: '2026-01-01T00:00:00Z' }) },
      { ts: '2026-01-02T00-00-00Z', summary: makeSummary({ sessionId: 's2', startedAt: '2026-01-02T00:00:00Z' }) },
      { ts: '2026-01-03T00-00-00Z', summary: makeSummary({ sessionId: 's3', startedAt: '2026-01-03T00:00:00Z' }) },
    ]);

    const resultsDir = path.join(dir, '.forge', 'results');
    const entries = await fs.readdir(resultsDir);
    expect(entries).toHaveLength(3);

    // Summaries can be loaded and sorted by startedAt
    const summaries: ForgeResult[] = [];
    for (const entry of entries) {
      const raw = await fs.readFile(path.join(resultsDir, entry, 'summary.json'), 'utf-8');
      summaries.push(JSON.parse(raw));
    }
    summaries.sort((a, b) => b.startedAt.localeCompare(a.startedAt));
    expect(summaries[0].sessionId).toBe('s3'); // newest first
    expect(summaries[2].sessionId).toBe('s1'); // oldest last
  });

  test('session row data includes all required display fields', () => {
    const summary = makeSummary({
      sessionId: 's1',
      specPath: '/repo/specs/auth.md',
      costUsd: 1.50,
      durationSeconds: 120,
      model: 'opus',
      status: 'success',
    });

    // Status: 'success' -> icon '+', Failed -> 'x', Running -> '>'
    const statusIcon = summary.status === 'success' ? '+' : 'x';
    expect(statusIcon).toBe('+');
    expect(summary.model).toBe('opus');
    expect(summary.costUsd).toBe(1.50);
    expect(summary.durationSeconds).toBe(120);
    // spec name extracted from path
    const specName = summary.specPath ? path.basename(summary.specPath) : '--';
    expect(specName).toBe('auth.md');
  });

  test('latest-session.json identifies running sessions', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);

    const sessionInfo = {
      sessionId: 'running-session',
      startedAt: new Date().toISOString(),
      model: 'sonnet',
      cwd: dir,
      logPath: path.join(dir, '.forge', 'sessions', 'running-session', 'stream.log'),
    };
    await fs.writeFile(
      path.join(dir, '.forge', 'latest-session.json'),
      JSON.stringify(sessionInfo),
    );

    const raw = await fs.readFile(path.join(dir, '.forge', 'latest-session.json'), 'utf-8');
    const parsed = JSON.parse(raw);
    expect(parsed.sessionId).toBe('running-session');
    // events.jsonl derived from logPath
    const eventsPath = parsed.logPath.replace('stream.log', 'events.jsonl');
    expect(eventsPath).toContain('events.jsonl');
  });

  test('empty results directory yields no sessions', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);
    await fs.mkdir(path.join(dir, '.forge', 'results'), { recursive: true });

    const entries = await fs.readdir(path.join(dir, '.forge', 'results'));
    expect(entries).toHaveLength(0);
  });
});

// ── Session detail: events.jsonl parsing and grouping ────────

describe('session detail event grouping', () => {
  test('text_delta events merge into single text block', () => {
    const events: SessionEvent[] = [
      { type: 'session_start', timestamp: 'ts', sessionId: 's', model: 'm', prompt: 'p' },
      { type: 'text_delta', timestamp: 'ts1', content: 'Hello ' },
      { type: 'text_delta', timestamp: 'ts2', content: 'world.' },
    ];
    const blocks = groupEvents(events);
    const textBlocks = blocks.filter(b => b.kind === 'text');
    expect(textBlocks).toHaveLength(1);
    expect((textBlocks[0] as TextBlock).content).toBe('Hello world.');
  });

  test('tool_call_start and tool_call_result pair by toolUseId', () => {
    const events: SessionEvent[] = [
      { type: 'tool_call_start', timestamp: 'ts1', toolName: 'Read', toolUseId: 'id-1', input: { file_path: 'a.ts' } },
      { type: 'tool_call_start', timestamp: 'ts2', toolName: 'Bash', toolUseId: 'id-2', input: { command: 'ls' } },
      { type: 'tool_call_result', timestamp: 'ts3', toolName: 'Bash', toolUseId: 'id-2', output: 'dir listing' },
      { type: 'tool_call_result', timestamp: 'ts4', toolName: 'Read', toolUseId: 'id-1', output: 'file content' },
    ];
    const blocks = groupEvents(events);
    const toolBlocks = blocks.filter(b => b.kind === 'tool') as ToolBlock[];
    expect(toolBlocks).toHaveLength(2);
    // First tool block (Read) paired with its result
    expect((toolBlocks[0].start as any).toolName).toBe('Read');
    expect((toolBlocks[0].result as any).output).toBe('file content');
    // Second tool block (Bash) paired with its result
    expect((toolBlocks[1].start as any).toolName).toBe('Bash');
    expect((toolBlocks[1].result as any).output).toBe('dir listing');
  });

  test('tool_call_start without toolUseId uses FIFO matching', () => {
    const events: SessionEvent[] = [
      { type: 'tool_call_start', timestamp: 'ts1', toolName: 'Read', input: { file_path: 'a.ts' } },
      { type: 'tool_call_result', timestamp: 'ts2', toolName: 'Read', output: 'content' },
    ];
    const blocks = groupEvents(events);
    const toolBlocks = blocks.filter(b => b.kind === 'tool') as ToolBlock[];
    expect(toolBlocks).toHaveLength(1);
    expect(toolBlocks[0].result).toBeDefined();
    expect((toolBlocks[0].result as any).output).toBe('content');
  });

  test('thinking_delta events are skipped (hidden by default)', () => {
    const events: SessionEvent[] = [
      { type: 'session_start', timestamp: 'ts', sessionId: 's', model: 'm', prompt: 'p' },
      { type: 'thinking_delta', timestamp: 'ts1', content: 'internal reasoning' },
      { type: 'text_delta', timestamp: 'ts2', content: 'visible text' },
    ];
    const blocks = groupEvents(events);
    const allKinds = blocks.map(b => b.kind);
    expect(allKinds).not.toContain('thinking');
    expect(allKinds).toContain('session_start');
    expect(allKinds).toContain('text');
  });

  test('text block flushed before tool block', () => {
    const events: SessionEvent[] = [
      { type: 'text_delta', timestamp: 'ts1', content: 'reasoning' },
      { type: 'tool_call_start', timestamp: 'ts2', toolName: 'Bash', input: { command: 'ls' } },
    ];
    const blocks = groupEvents(events);
    expect(blocks[0].kind).toBe('text');
    expect(blocks[1].kind).toBe('tool');
  });

  test('session_start and session_end create divider blocks', () => {
    const events: SessionEvent[] = [
      { type: 'session_start', timestamp: 'ts1', sessionId: 's1', model: 'sonnet', prompt: 'task' },
      { type: 'text_delta', timestamp: 'ts2', content: 'done' },
      { type: 'session_end', timestamp: 'ts3', durationSeconds: 10, status: 'success' },
    ];
    const blocks = groupEvents(events);
    expect(blocks[0].kind).toBe('session_start');
    expect(blocks[1].kind).toBe('text');
    expect(blocks[2].kind).toBe('session_end');
  });

  test('empty events array returns empty blocks', () => {
    const blocks = groupEvents([]);
    expect(blocks).toHaveLength(0);
  });

  test('tool block indices can be collected for focus navigation', () => {
    const events: SessionEvent[] = [
      { type: 'session_start', timestamp: 'ts', sessionId: 's', model: 'm', prompt: 'p' },
      { type: 'text_delta', timestamp: 'ts1', content: 'analysis' },
      { type: 'tool_call_start', timestamp: 'ts2', toolName: 'Read', input: {} },
      { type: 'tool_call_result', timestamp: 'ts3', toolName: 'Read', output: '' },
      { type: 'text_delta', timestamp: 'ts4', content: 'more text' },
      { type: 'tool_call_start', timestamp: 'ts5', toolName: 'Edit', input: {} },
      { type: 'tool_call_result', timestamp: 'ts6', toolName: 'Edit', output: '' },
      { type: 'tool_call_start', timestamp: 'ts7', toolName: 'Bash', input: {} },
      { type: 'tool_call_result', timestamp: 'ts8', toolName: 'Bash', output: '' },
    ];
    const blocks = groupEvents(events);
    const toolBlockIndices = blocks
      .map((b, i) => b.kind === 'tool' ? i : -1)
      .filter(i => i >= 0);
    expect(toolBlockIndices).toHaveLength(3);
    // n/N navigation: focusedToolIndex cycles through these indices
  });
});

// ── events.jsonl parsing from file ───────────────────────────

describe('events.jsonl file parsing', () => {
  test('events parsed from JSONL format with all event types', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);

    const events: SessionEvent[] = [
      { type: 'session_start', timestamp: '2026-01-01T00:00:00Z', sessionId: 's1', model: 'sonnet', prompt: 'test' },
      { type: 'thinking_delta', timestamp: '2026-01-01T00:00:01Z', content: 'Analyzing...' },
      { type: 'text_delta', timestamp: '2026-01-01T00:00:02Z', content: 'Found it.' },
      { type: 'tool_call_start', timestamp: '2026-01-01T00:00:03Z', toolName: 'Read', input: { file_path: 'src/index.ts' } },
      { type: 'tool_call_result', timestamp: '2026-01-01T00:00:04Z', toolName: 'Read', output: 'file contents' },
      { type: 'session_end', timestamp: '2026-01-01T00:00:10Z', durationSeconds: 10, status: 'success' },
    ];

    const eventsPath = await setupSession(dir, 's1', events);
    const content = await fs.readFile(eventsPath, 'utf-8');
    const parsed = content.split('\n').filter(l => l.trim()).map(l => JSON.parse(l) as SessionEvent);

    expect(parsed).toHaveLength(6);
    expect(parsed[0].type).toBe('session_start');
    expect(parsed[1].type).toBe('thinking_delta');
    expect(parsed[2].type).toBe('text_delta');
    expect(parsed[3].type).toBe('tool_call_start');
    expect(parsed[4].type).toBe('tool_call_result');
    expect(parsed[5].type).toBe('session_end');
  });

  test('malformed JSONL lines are skipped gracefully', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir);

    const sessionDir = path.join(dir, '.forge', 'sessions', 's1');
    await fs.mkdir(sessionDir, { recursive: true });
    const eventsPath = path.join(sessionDir, 'events.jsonl');

    const lines = [
      JSON.stringify({ type: 'session_start', timestamp: 'ts', sessionId: 's1', model: 'sonnet', prompt: 'test' }),
      'not valid json {{{',
      JSON.stringify({ type: 'text_delta', timestamp: 'ts', content: 'hello' }),
    ];
    await fs.writeFile(eventsPath, lines.join('\n'));

    const content = await fs.readFile(eventsPath, 'utf-8');
    const parsed: SessionEvent[] = [];
    for (const line of content.split('\n')) {
      if (!line.trim()) continue;
      try { parsed.push(JSON.parse(line)); } catch { /* skip */ }
    }
    expect(parsed).toHaveLength(2);
  });

  test('events.jsonl path derived from stream.log via dirname', () => {
    // deriveEventsPath with logPath
    const logPath = '/repo/.forge/sessions/abc123/stream.log';
    const eventsPath = path.join(path.dirname(logPath), 'events.jsonl');
    expect(eventsPath).toBe('/repo/.forge/sessions/abc123/events.jsonl');
  });

  test('events.jsonl path derived from sessionId and cwd', () => {
    const sessionId = 'def456';
    const cwd = '/repo';
    const eventsPath = path.join(cwd, '.forge', 'sessions', sessionId, 'events.jsonl');
    expect(eventsPath).toBe('/repo/.forge/sessions/def456/events.jsonl');
  });
});

// ── Tab bar: view switcher ───────────────────────────────────

describe('tab bar view switcher', () => {
  test('Tab type supports sessions, specs, pipeline', () => {
    const tabs: Array<'sessions' | 'specs' | 'pipeline'> = ['sessions', 'specs', 'pipeline'];
    expect(tabs).toHaveLength(3);
    expect(tabs).toContain('sessions');
    expect(tabs).toContain('specs');
    expect(tabs).toContain('pipeline');
  });

  test('tab cycling wraps around: sessions -> specs -> pipeline -> sessions', () => {
    const tabs = ['sessions', 'specs', 'pipeline'] as const;
    let current = 0;
    // Press tab 3 times
    current = (current + 1) % tabs.length; expect(tabs[current]).toBe('specs');
    current = (current + 1) % tabs.length; expect(tabs[current]).toBe('pipeline');
    current = (current + 1) % tabs.length; expect(tabs[current]).toBe('sessions');
  });
});

// ── Specs list: manifest loading and display data ────────────

describe('specs list data', () => {
  test('loadManifest returns entries for specs list', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir, {
      version: 1,
      specs: [
        makeEntry({ spec: 'auth/login.md', status: 'passed', runs: [makeRun()] }),
        makeEntry({ spec: 'auth/oauth.md', status: 'failed', runs: [makeRun({ status: 'failed' })] }),
        makeEntry({ spec: 'db/migrate.md', status: 'pending' }),
      ],
    });

    const manifest = await loadManifest(dir);
    expect(manifest.specs).toHaveLength(3);

    // Can group by directory
    const authSpecs = manifest.specs.filter(s => s.spec.startsWith('auth/'));
    expect(authSpecs).toHaveLength(2);
    const dbSpecs = manifest.specs.filter(s => s.spec.startsWith('db/'));
    expect(dbSpecs).toHaveLength(1);
  });

  test('total cost per spec computed from runs', () => {
    const entry = makeEntry({
      runs: [
        makeRun({ costUsd: 1.50, durationSeconds: 60 }),
        makeRun({ costUsd: 2.00, durationSeconds: 90, runId: 'run-2', timestamp: '2026-01-02T00:00:00Z' }),
      ],
    });
    const totalCost = entry.runs.reduce((s, r) => s + (r.costUsd ?? 0), 0);
    const totalDuration = entry.runs.reduce((s, r) => s + r.durationSeconds, 0);
    expect(totalCost).toBeCloseTo(3.50, 2);
    expect(totalDuration).toBe(150);
  });

  test('empty manifest shows no specs', async () => {
    const dir = await makeTmpDir();
    await setupForge(dir, { version: 1, specs: [] });
    const manifest = await loadManifest(dir);
    expect(manifest.specs).toHaveLength(0);
  });

  test('missing manifest file returns empty manifest gracefully', async () => {
    const dir = await makeTmpDir();
    // No .forge directory at all
    const manifest = await loadManifest(dir);
    expect(manifest.specs).toHaveLength(0);
    expect(manifest.version).toBe(1);
  });

  test('status icon mapping: + for passed, x for failed, - for pending', () => {
    const iconMap: Record<string, string> = {
      passed: '+', failed: 'x', pending: '-', running: '>',
    };
    expect(iconMap.passed).toBe('+');
    expect(iconMap.failed).toBe('x');
    expect(iconMap.pending).toBe('-');
    expect(iconMap.running).toBe('>');
  });

  test('directory grouping extracts parent dir from spec path', () => {
    const specs = ['auth/login.md', 'auth/oauth.md', 'db/migrate.md', 'standalone.md'];
    const groups = new Map<string, string[]>();
    for (const spec of specs) {
      const dir = spec.includes('/') ? path.dirname(spec) : '.';
      if (!groups.has(dir)) groups.set(dir, []);
      groups.get(dir)!.push(spec);
    }
    expect(groups.get('auth')).toHaveLength(2);
    expect(groups.get('db')).toHaveLength(1);
    expect(groups.get('.')).toHaveLength(1);
  });
});

// ── Spec detail: run history ─────────────────────────────────

describe('spec detail run history', () => {
  test('run entries have all display fields', () => {
    const entry = makeEntry({
      spec: 'auth/login.md',
      runs: [
        makeRun({
          runId: 'run-1',
          timestamp: '2026-01-01T00:00:00Z',
          status: 'failed',
          costUsd: 1.00,
          durationSeconds: 30,
          numTurns: 10,
          verifyAttempts: 2,
        }),
        makeRun({
          runId: 'run-2',
          timestamp: '2026-01-02T00:00:00Z',
          status: 'passed',
          costUsd: 2.00,
          durationSeconds: 60,
          numTurns: 25,
          verifyAttempts: 0,
        }),
      ],
    });

    expect(entry.runs).toHaveLength(2);
    // Newest first (sorted by caller)
    const sorted = [...entry.runs].sort((a, b) => b.timestamp.localeCompare(a.timestamp));
    expect(sorted[0].runId).toBe('run-2');
    expect(sorted[0].numTurns).toBe(25);
    expect(sorted[1].runId).toBe('run-1');
    expect(sorted[1].verifyAttempts).toBe(2);
  });

  test('empty runs array shows no run history', () => {
    const entry = makeEntry({ runs: [] });
    expect(entry.runs).toHaveLength(0);
  });

  test('session events path can be derived from resultPath', () => {
    // resultPath stores the result directory, sessionId can be derived from summary
    const run = makeRun({ resultPath: '.forge/results/2026-01-01T00-00-00Z' });
    expect(run.resultPath).toContain('.forge/results/');
    // The TUI reads summary.json from resultPath, then uses sessionId for events
  });

  test('spec metadata includes status, source, timestamps', () => {
    const entry = makeEntry({
      spec: 'auth/login.md',
      status: 'passed',
      source: 'file',
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-02T00:00:00Z',
    });
    expect(entry.status).toBe('passed');
    expect(entry.source).toBe('file');
    expect(entry.createdAt).toBe('2026-01-01T00:00:00Z');
    expect(entry.updatedAt).toBe('2026-01-02T00:00:00Z');
  });
});

// ── Tool block input/output data ─────────────────────────────

describe('tool block input and output rendering data', () => {
  test('summarizeToolInput extracts command for Bash', () => {
    const input: Record<string, unknown> = { command: 'npm test --verbose' };
    // Collapsed summary: the command string
    const summary = typeof input.command === 'string' ? input.command : '';
    expect(summary).toBe('npm test --verbose');
  });

  test('summarizeToolInput extracts file_path for Read', () => {
    const input: Record<string, unknown> = { file_path: '/repo/src/auth.ts' };
    const summary = typeof input.file_path === 'string' ? path.basename(input.file_path as string) : '';
    expect(summary).toBe('auth.ts');
  });

  test('summarizeToolInput extracts pattern for Grep', () => {
    const input: Record<string, unknown> = { pattern: 'TODO|FIXME', path: 'src/' };
    const summary = typeof input.pattern === 'string' ? input.pattern : '';
    expect(summary).toBe('TODO|FIXME');
  });

  test('expanded tool block shows all input keys', () => {
    const input: Record<string, unknown> = {
      file_path: '/repo/src/index.ts',
      old_string: 'const a = 1;',
      new_string: 'const a = 2;',
    };
    const keys = Object.keys(input);
    expect(keys).toContain('file_path');
    expect(keys).toContain('old_string');
    expect(keys).toContain('new_string');

    // All values can be formatted as strings
    for (const [, value] of Object.entries(input)) {
      const formatted = typeof value === 'string' ? value : JSON.stringify(value);
      expect(typeof formatted).toBe('string');
    }
  });

  test('expanded tool block renders full output preserving newlines', () => {
    const output = 'line 1\nline 2\nline 3\n  indented line';
    const lines = output.split('\n');
    expect(lines).toHaveLength(4);
    expect(lines[3]).toBe('  indented line');
  });

  test('non-string input values are JSON-stringified for display', () => {
    const input: Record<string, unknown> = {
      command: 'echo hi',
      timeout: 60000,
      run_in_background: true,
      options: { verbose: true, count: 3 },
    };
    for (const [, value] of Object.entries(input)) {
      const display = typeof value === 'string' ? value : JSON.stringify(value);
      expect(typeof display).toBe('string');
    }
    expect(JSON.stringify(input.timeout)).toBe('60000');
    expect(JSON.stringify(input.run_in_background)).toBe('true');
    expect(JSON.stringify(input.options)).toBe('{"verbose":true,"count":3}');
  });

  test('tool block with toolUseId enables stable focus tracking', () => {
    const events: SessionEvent[] = [
      { type: 'tool_call_start', timestamp: 'ts1', toolName: 'Read', toolUseId: 'tu-abc', input: {} },
      { type: 'tool_call_start', timestamp: 'ts2', toolName: 'Edit', toolUseId: 'tu-def', input: {} },
    ];
    const blocks = groupEvents(events);
    const toolBlocks = blocks.filter(b => b.kind === 'tool') as ToolBlock[];
    // Each block has a unique toolUseId for stable expand/collapse tracking
    const ids = toolBlocks.map(b => (b.start as any).toolUseId);
    expect(ids[0]).toBe('tu-abc');
    expect(ids[1]).toBe('tu-def');
    expect(new Set(ids).size).toBe(ids.length); // all unique
  });

  test('expand/collapse state tracked as Set of indices or IDs', () => {
    // Simulating the expandedSet pattern from the spec
    const expandedSet = new Set<string>();
    expect(expandedSet.size).toBe(0);

    expandedSet.add('tu-abc');
    expect(expandedSet.has('tu-abc')).toBe(true);

    // Toggle: pressing Enter removes from set (collapse)
    expandedSet.delete('tu-abc');
    expect(expandedSet.has('tu-abc')).toBe(false);
  });
});
