// Generated by forge proof from workspace-hooks-extraction.md, monorepo-worktree-support.md
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import {
  detectSetupCommands,
  resolveSetupCommands,
  resolveTeardownCommands,
  runWorkspaceHooks,
  detectScopedSetupCommands,
} from './workspace.js';
import type { ForgeLocalConfig } from './config.js';
import { CONFIG_DEFAULTS } from './config.js';

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-ws-test-'));
});

afterEach(async () => {
  await fs.rm(tmpDir, { recursive: true, force: true });
});

// ── detectSetupCommands ──────────────────────────────────────

describe('detectSetupCommands', () => {
  test('detects bun project via bun.lockb', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('bun install');
  });

  test('detects pnpm project via pnpm-lock.yaml', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'pnpm-lock.yaml'), '');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('pnpm install');
  });

  test('detects npm project via package-lock.json', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'package-lock.json'), '{}');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('npm install');
  });

  test('detects Cargo project', async () => {
    await fs.writeFile(path.join(tmpDir, 'Cargo.toml'), '[package]');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('cargo build');
  });

  test('detects Go project', async () => {
    await fs.writeFile(path.join(tmpDir, 'go.mod'), 'module test');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('go mod download');
  });

  test('detects hybrid project (Node + Cargo)', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');
    await fs.writeFile(path.join(tmpDir, 'Cargo.toml'), '[package]');

    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toContain('bun install');
    expect(commands).toContain('cargo build');
  });

  test('returns empty array for empty directory', async () => {
    const commands = await detectSetupCommands(tmpDir);
    expect(commands).toEqual([]);
  });
});

// ── resolveSetupCommands ─────────────────────────────────────

describe('resolveSetupCommands', () => {
  test('config overrides take precedence over auto-detection', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const config: ForgeLocalConfig = {
      ...CONFIG_DEFAULTS,
      setup: ['custom-setup.sh'],
    };

    const commands = await resolveSetupCommands(tmpDir, config);
    expect(commands).toEqual(['custom-setup.sh']);
  });

  test('falls back to auto-detection when config.setup is empty', async () => {
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const config: ForgeLocalConfig = { ...CONFIG_DEFAULTS, setup: [] };

    const commands = await resolveSetupCommands(tmpDir, config);
    expect(commands).toContain('bun install');
  });
});

// ── resolveTeardownCommands ──────────────────────────────────

describe('resolveTeardownCommands', () => {
  test('returns config teardown commands', () => {
    const config: ForgeLocalConfig = {
      ...CONFIG_DEFAULTS,
      teardown: ['docker-compose down', 'rm -rf .cache'],
    };

    expect(resolveTeardownCommands(config)).toEqual(['docker-compose down', 'rm -rf .cache']);
  });

  test('returns empty array when no teardown configured', () => {
    expect(resolveTeardownCommands(CONFIG_DEFAULTS)).toEqual([]);
  });
});

// ── runWorkspaceHooks ────────────────────────────────────────

describe('runWorkspaceHooks', () => {
  test('returns success for empty command list', async () => {
    const result = await runWorkspaceHooks([], tmpDir, 5000, true);
    expect(result.success).toBe(true);
    expect(result.output).toBe('');
  });

  test('runs commands sequentially and returns combined output', async () => {
    const result = await runWorkspaceHooks(
      ['echo hello', 'echo world'],
      tmpDir,
      5000,
      true,
    );
    expect(result.success).toBe(true);
    expect(result.output).toContain('hello');
    expect(result.output).toContain('world');
  });

  test('stops on first failure', async () => {
    const result = await runWorkspaceHooks(
      ['echo first', 'false', 'echo third'],
      tmpDir,
      5000,
      true,
    );
    expect(result.success).toBe(false);
    expect(result.failedCommand).toContain('false');
  });

  test('reports timeout as failure', async () => {
    const result = await runWorkspaceHooks(
      ['sleep 60'],
      tmpDir,
      100, // Very short timeout
      true,
    );
    expect(result.success).toBe(false);
    expect(result.failedCommand).toContain('timed out');
  });
});

// ── detectScopedSetupCommands (monorepo) ─────────────────────

describe('detectScopedSetupCommands', () => {
  test('detects build script in scoped package', async () => {
    // Create a monorepo-like structure
    await fs.writeFile(path.join(tmpDir, 'package.json'), '{}');
    await fs.writeFile(path.join(tmpDir, 'bun.lockb'), '');

    const scopedDir = path.join(tmpDir, 'packages', 'api');
    await fs.mkdir(scopedDir, { recursive: true });
    await fs.writeFile(
      path.join(scopedDir, 'package.json'),
      JSON.stringify({ scripts: { build: 'tsc -b' } }),
    );

    const { commands, cwd } = await detectScopedSetupCommands(tmpDir, 'packages/api');
    expect(commands).toContain('bun run build');
    expect(cwd).toBe(scopedDir);
  });

  test('returns empty commands when no build script', async () => {
    const scopedDir = path.join(tmpDir, 'packages', 'utils');
    await fs.mkdir(scopedDir, { recursive: true });
    await fs.writeFile(
      path.join(scopedDir, 'package.json'),
      JSON.stringify({ scripts: { test: 'jest' } }),
    );

    const { commands } = await detectScopedSetupCommands(tmpDir, 'packages/utils');
    expect(commands).toEqual([]);
  });

  test('detects Cargo project in scoped directory', async () => {
    const scopedDir = path.join(tmpDir, 'crates', 'core');
    await fs.mkdir(scopedDir, { recursive: true });
    await fs.writeFile(path.join(scopedDir, 'Cargo.toml'), '[package]');

    const { commands } = await detectScopedSetupCommands(tmpDir, 'crates/core');
    expect(commands).toContain('cargo build');
  });

  test('returns empty when scoped directory does not exist', async () => {
    const { commands } = await detectScopedSetupCommands(tmpDir, 'nonexistent/path');
    expect(commands).toEqual([]);
  });
});
