// Generated by forge proof from worktree-aware-audit.md
import { describe, test, expect, beforeEach } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  transitionWorktreeStatus,
  getDb,
} from './db.js';
import type { Database } from 'bun:sqlite';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function makeWorktreeId(): string {
  return `wt-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeWorktreeId();
  insertWorktree(db, {
    id,
    spec_path: 'specs/auth.md',
    branch: 'forge/auth',
    worktree_path: '/tmp/project-auth',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── Worktree-aware audit lifecycle transitions ───────────────

describe('worktree audit status transitions', () => {
  test('complete -> auditing is a valid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('auditing');
  });

  test('auditing -> audited is a valid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'audited');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('audited');
  });

  test('auditing -> failed stores error message', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'failed', 'Audit round failed');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('failed');
    expect(wt!.error).toBe('Audit round failed');
  });

  test('created -> auditing is an invalid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    expect(() => transitionWorktreeStatus(db, id, 'auditing')).toThrow('Invalid worktree transition');
  });

  test('running -> auditing is an invalid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    expect(() => transitionWorktreeStatus(db, id, 'auditing')).toThrow('Invalid worktree transition');
  });
});

// ── Worktree resolution for audit ────────────────────────────

describe('worktree resolution for audit context', () => {
  test('getWorktree resolves worktree by ID for audit scope', () => {
    const id = insertTestWorktree({
      worktree_path: '/home/dev/project-auth-wt',
      spec_path: 'specs/auth/',
    });

    const wt = getWorktree(db, id);
    expect(wt).not.toBeNull();
    expect(wt!.worktree_path).toBe('/home/dev/project-auth-wt');
    expect(wt!.spec_path).toBe('specs/auth/');
  });

  test('getWorktree returns null for non-existent worktree ID', () => {
    const wt = getWorktree(db, 'nonexistent-wt-id');
    expect(wt).toBeNull();
  });
});

// ── Audit-fix loop within worktree ────────────────────────────

describe('audit-fix worktree lifecycle', () => {
  test('full audit lifecycle: created -> running -> complete -> auditing -> audited', () => {
    const id = insertTestWorktree({ status: 'created' });

    transitionWorktreeStatus(db, id, 'running');
    expect(getWorktree(db, id)!.status).toBe('running');

    transitionWorktreeStatus(db, id, 'complete');
    expect(getWorktree(db, id)!.status).toBe('complete');

    transitionWorktreeStatus(db, id, 'auditing');
    expect(getWorktree(db, id)!.status).toBe('auditing');

    transitionWorktreeStatus(db, id, 'audited');
    expect(getWorktree(db, id)!.status).toBe('audited');
  });

  test('audited worktree can proceed to proofing', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'audited');
    transitionWorktreeStatus(db, id, 'proofing');

    expect(getWorktree(db, id)!.status).toBe('proofing');
  });

  test('audited worktree can skip proofing and go to ready', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'audited');
    transitionWorktreeStatus(db, id, 'ready');

    expect(getWorktree(db, id)!.status).toBe('ready');
  });
});

// ── Error handling in audit ──────────────────────────────────

describe('audit error handling in worktree context', () => {
  test('transition to failed clears previous error on retry path', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'failed', 'First failure');

    expect(getWorktree(db, id)!.error).toBe('First failure');

    // Retry from failed -> created -> running -> complete -> auditing
    transitionWorktreeStatus(db, id, 'created');
    expect(getWorktree(db, id)!.error).toBeNull();
  });
});
