// Generated by forge proof from work-group-id.md
import { describe, test, expect, beforeEach } from 'bun:test';
import { generateWorkGroupId } from './utils.js';
import {
  getTestDb,
  insertSpecEntry,
  listSpecEntriesByWorkGroup,
  insertWorktree,
  getWorktreesByWorkGroup,
} from './db.js';
import type { Database } from 'bun:sqlite';
import crypto from 'crypto';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

// ── generateWorkGroupId ──────────────────────────────────────

describe('generateWorkGroupId', () => {
  test('follows wg-{timestamp}-{random} format', () => {
    const id = generateWorkGroupId();
    expect(id).toMatch(/^wg-\d+-[0-9a-f]{6}$/);
  });

  test('generates unique IDs', () => {
    const ids = new Set(Array.from({ length: 100 }, () => generateWorkGroupId()));
    expect(ids.size).toBe(100);
  });

  test('timestamp is within 2 seconds of current time', () => {
    const id = generateWorkGroupId();
    const parts = id.split('-');
    const timestamp = parseInt(parts[1], 10);
    const nowSeconds = Math.floor(Date.now() / 1000);
    expect(Math.abs(nowSeconds - timestamp)).toBeLessThanOrEqual(2);
  });

  test('is short enough for directory and branch names', () => {
    const id = generateWorkGroupId();
    // wg- + 10 digits + - + 6 hex = ~20 chars
    expect(id.length).toBeLessThanOrEqual(22);
    expect(id).not.toContain(' ');
    expect(id).not.toContain('/');
  });
});

// ── Work Group propagation to spec entries ───────────────────

describe('work group association with spec entries', () => {
  test('spec entries created with work_group_id are retrievable by group', () => {
    const wgId = generateWorkGroupId();

    insertSpecEntry(db, { id: crypto.randomUUID(), spec: 'auth.md', work_group_id: wgId });
    insertSpecEntry(db, { id: crypto.randomUUID(), spec: 'api.md', work_group_id: wgId });
    insertSpecEntry(db, { id: crypto.randomUUID(), spec: 'other.md', work_group_id: 'wg-different' });

    const entries = listSpecEntriesByWorkGroup(db, wgId);
    expect(entries).toHaveLength(2);
    expect(entries.map(e => e.spec).sort()).toEqual(['api.md', 'auth.md']);
  });

  test('legacy specs without work_group_id are not in any group', () => {
    insertSpecEntry(db, { id: crypto.randomUUID(), spec: 'legacy.md' });

    const entries = listSpecEntriesByWorkGroup(db, 'any-group');
    expect(entries).toHaveLength(0);
  });
});

// ── Work Group propagation to worktrees ──────────────────────

describe('work group association with worktrees', () => {
  test('worktrees created with same work_group_id are grouped', () => {
    const wgId = generateWorkGroupId();

    insertWorktree(db, {
      id: `wt-1-${Date.now()}`,
      work_group_id: wgId,
      spec_path: 'auth.md',
      branch: 'forge/auth',
      worktree_path: '/tmp/p-auth',
    });
    insertWorktree(db, {
      id: `wt-2-${Date.now()}`,
      work_group_id: wgId,
      spec_path: 'api.md',
      branch: 'forge/api',
      worktree_path: '/tmp/p-api',
    });
    insertWorktree(db, {
      id: `wt-3-${Date.now()}`,
      work_group_id: 'wg-other',
      spec_path: 'other.md',
      branch: 'forge/other',
      worktree_path: '/tmp/p-other',
    });

    const group = getWorktreesByWorkGroup(db, wgId);
    expect(group).toHaveLength(2);
    expect(group.map(w => w.spec_path).sort()).toEqual(['api.md', 'auth.md']);
  });

  test('auto-minted work group at run time links all worktrees', () => {
    const runTimeWg = generateWorkGroupId();

    for (let i = 0; i < 5; i++) {
      insertWorktree(db, {
        id: `wt-rt-${i}-${Date.now()}`,
        work_group_id: runTimeWg,
        spec_path: `spec-${i}.md`,
        branch: `forge/spec-${i}`,
        worktree_path: `/tmp/p-spec-${i}`,
      });
    }

    const group = getWorktreesByWorkGroup(db, runTimeWg);
    expect(group).toHaveLength(5);
  });
});
