// Generated by forge proof from worktree-aware-proof.md
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  transitionWorktreeStatus,
} from './db.js';
import { detectTestConvention } from './proof.js';
import type { Database } from 'bun:sqlite';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function makeWorktreeId(): string {
  return `wt-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeWorktreeId();
  insertWorktree(db, {
    id,
    spec_path: 'specs/feature.md',
    branch: 'forge/feature',
    worktree_path: '/tmp/project-feature',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── Worktree proof lifecycle transitions ─────────────────────

describe('worktree proof status transitions', () => {
  test('complete -> proofing is a valid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'proofing');

    expect(getWorktree(db, id)!.status).toBe('proofing');
  });

  test('proofing -> proofed is a valid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'proofing');
    transitionWorktreeStatus(db, id, 'proofed');

    expect(getWorktree(db, id)!.status).toBe('proofed');
  });

  test('proofing -> failed stores error message', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'proofing');
    transitionWorktreeStatus(db, id, 'failed', 'Proof generation failed: no tests generated');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('failed');
    expect(wt!.error).toBe('Proof generation failed: no tests generated');
  });

  test('audited -> proofing is a valid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'audited');
    transitionWorktreeStatus(db, id, 'proofing');

    expect(getWorktree(db, id)!.status).toBe('proofing');
  });

  test('created -> proofing is an invalid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    expect(() => transitionWorktreeStatus(db, id, 'proofing')).toThrow('Invalid worktree transition');
  });

  test('running -> proofing is an invalid transition', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    expect(() => transitionWorktreeStatus(db, id, 'proofing')).toThrow('Invalid worktree transition');
  });
});

// ── Full proof lifecycle through worktree ─────────────────────

describe('worktree proof full lifecycle', () => {
  test('complete -> proofing -> proofed -> ready', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'proofing');
    transitionWorktreeStatus(db, id, 'proofed');
    transitionWorktreeStatus(db, id, 'ready');

    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('full pipeline: created -> running -> complete -> auditing -> audited -> proofing -> proofed -> ready', () => {
    const id = insertTestWorktree({ status: 'created' });
    const transitions = [
      'running', 'complete', 'auditing', 'audited', 'proofing', 'proofed', 'ready',
    ] as const;

    for (const next of transitions) {
      transitionWorktreeStatus(db, id, next);
    }

    expect(getWorktree(db, id)!.status).toBe('ready');
  });
});

// ── detectTestConvention ─────────────────────────────────────

describe('detectTestConvention', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-proof-conv-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test('detects colocated tests in src/ with >= 2 test files', async () => {
    const srcDir = path.join(tmpDir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'foo.test.ts'), '');
    await fs.writeFile(path.join(srcDir, 'bar.test.ts'), '');
    await fs.writeFile(path.join(srcDir, 'baz.ts'), '');

    const result = await detectTestConvention(tmpDir);
    expect(result.style).toBe('colocated');
    expect(result.testDir).toBe('src');
    expect(result.examples.length).toBeGreaterThanOrEqual(2);
  });

  test('detects separate tests/ directory', async () => {
    const testsDir = path.join(tmpDir, 'tests');
    await fs.mkdir(testsDir, { recursive: true });
    await fs.writeFile(path.join(testsDir, 'foo.test.ts'), '');

    const result = await detectTestConvention(tmpDir);
    expect(result.style).toBe('separate');
    expect(result.testDir).toBe('tests');
  });

  test('defaults to colocated in src/ when no tests found', async () => {
    const result = await detectTestConvention(tmpDir);
    expect(result.style).toBe('colocated');
    expect(result.testDir).toBe('src');
    expect(result.examples).toEqual([]);
  });

  test('colocated detection requires at least 2 test files', async () => {
    const srcDir = path.join(tmpDir, 'src');
    await fs.mkdir(srcDir, { recursive: true });
    await fs.writeFile(path.join(srcDir, 'only.test.ts'), '');

    const result = await detectTestConvention(tmpDir);
    // Only 1 test file: not enough for colocated detection, falls through
    expect(result.style).toBe('colocated');
    expect(result.testDir).toBe('src');
  });
});

// ── Worktree resolution for proof ────────────────────────────

describe('worktree resolution for proof context', () => {
  test('getWorktree resolves branch for git diff scoping', () => {
    const id = insertTestWorktree({
      branch: 'forge/ENG-100/feature-x',
      worktree_path: '/home/dev/project-feature-x',
    });

    const wt = getWorktree(db, id);
    expect(wt).not.toBeNull();
    expect(wt!.branch).toBe('forge/ENG-100/feature-x');
    expect(wt!.worktree_path).toBe('/home/dev/project-feature-x');
  });
});
