// Generated by forge proof from cli-worktree-commands.md
import { describe, test, expect, beforeEach } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  getWorktreesByWorkGroup,
  transitionWorktreeStatus,
  listWorktrees,
  insertSpecEntry,
  insertSpecRun,
  getSpecEntryByPath,
} from './db.js';
import type { Database } from 'bun:sqlite';
import type { WorktreeStatus } from './db.js';
import crypto from 'crypto';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = `wt-cli-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
  insertWorktree(db, {
    id,
    spec_path: 'specs/test.md',
    branch: 'forge/test',
    worktree_path: '/tmp/project-test',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── forge worktree list ─────────────────────────────────────

describe('worktree list data', () => {
  test('list shows all worktrees with required fields', () => {
    insertTestWorktree({
      work_group_id: 'wg-list',
      spec_path: 'auth.md',
      branch: 'forge/auth',
      worktree_path: '/tmp/auth',
    });
    insertTestWorktree({
      work_group_id: 'wg-list',
      spec_path: 'api.md',
      branch: 'forge/api',
      worktree_path: '/tmp/api',
    });

    const all = listWorktrees(db);
    expect(all).toHaveLength(2);

    for (const wt of all) {
      // All required fields present
      expect(wt.id).toBeTruthy();
      expect(wt.status).toBeTruthy();
      expect(wt.spec_path).toBeTruthy();
      expect(wt.branch).toBeTruthy();
      expect(wt.worktree_path).toBeTruthy();
      expect(wt.created_at).toBeTruthy();
      expect(wt.updated_at).toBeTruthy();
    }
  });

  test('list filters by status', () => {
    insertTestWorktree({ status: 'created', branch: 'forge/c1', worktree_path: '/tmp/c1' });
    const runId = insertTestWorktree({ status: 'created', branch: 'forge/c2', worktree_path: '/tmp/c2' });
    transitionWorktreeStatus(db, runId, 'running');
    insertTestWorktree({ status: 'created', branch: 'forge/c3', worktree_path: '/tmp/c3' });

    const running = listWorktrees(db, 'running');
    expect(running).toHaveLength(1);
    expect(running[0].status).toBe('running');
  });

  test('list filters by work group', () => {
    insertTestWorktree({ work_group_id: 'wg-X', branch: 'forge/x1', worktree_path: '/tmp/x1' });
    insertTestWorktree({ work_group_id: 'wg-X', branch: 'forge/x2', worktree_path: '/tmp/x2' });
    insertTestWorktree({ work_group_id: 'wg-Y', branch: 'forge/y1', worktree_path: '/tmp/y1' });

    const groupX = getWorktreesByWorkGroup(db, 'wg-X');
    expect(groupX).toHaveLength(2);
    expect(groupX.every(w => w.work_group_id === 'wg-X')).toBe(true);
  });

  test('most recently updated worktrees appear first', () => {
    const id1 = insertTestWorktree({ branch: 'forge/old', worktree_path: '/tmp/old' });
    const id2 = insertTestWorktree({ branch: 'forge/new', worktree_path: '/tmp/new' });

    // Trigger an update on id1 (makes it most recently updated)
    transitionWorktreeStatus(db, id1, 'running');

    const all = listWorktrees(db);
    // listWorktrees orders by created_at DESC. For updated_at sort, that's CLI-side.
    // The DB provides the data; the CLI sorts by updated_at.
    expect(all).toHaveLength(2);
  });
});

// ── forge worktree status <id> ──────────────────────────────

describe('worktree status detail', () => {
  test('shows detailed info including spec content reference', () => {
    const id = insertTestWorktree({
      spec_path: 'specs/auth-login.md',
      work_group_id: 'wg-detail',
      linear_issue_id: 'ENG-42',
      session_id: 'sess-123',
    });

    const wt = getWorktree(db, id);
    expect(wt).not.toBeNull();
    expect(wt!.spec_path).toBe('specs/auth-login.md');
    expect(wt!.work_group_id).toBe('wg-detail');
    expect(wt!.linear_issue_id).toBe('ENG-42');
    expect(wt!.session_id).toBe('sess-123');
  });

  test('shows run history from spec_runs via spec_entries', () => {
    const specPath = 'specs/run-history.md';
    const entryId = crypto.randomUUID();
    insertSpecEntry(db, { id: entryId, spec: specPath });
    insertSpecRun(db, {
      id: crypto.randomUUID(),
      spec_entry_id: entryId,
      run_id: 'batch-1',
      timestamp: '2026-01-01T00:00:00Z',
      status: 'passed',
      cost_usd: 2.5,
      duration_seconds: 120,
    });

    const id = insertTestWorktree({ spec_path: specPath });

    // Verify lookup path works
    const entry = getSpecEntryByPath(db, specPath);
    expect(entry).not.toBeNull();
    expect(entry!.id).toBe(entryId);
  });
});

// ── forge worktree mark-ready <id> ──────────────────────────

describe('worktree mark-ready', () => {
  test('transitions complete -> ready', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');

    const { previousStatus } = transitionWorktreeStatus(db, id, 'ready');
    expect(previousStatus).toBe('complete');
    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('transitions proofed -> ready', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'auditing');
    transitionWorktreeStatus(db, id, 'audited');
    transitionWorktreeStatus(db, id, 'proofing');
    transitionWorktreeStatus(db, id, 'proofed');

    const { previousStatus } = transitionWorktreeStatus(db, id, 'ready');
    expect(previousStatus).toBe('proofed');
    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('transitions merge_failed -> ready (retry)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');
    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merge_failed');

    const { previousStatus } = transitionWorktreeStatus(db, id, 'ready');
    expect(previousStatus).toBe('merge_failed');
    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('rejects invalid transition from created', () => {
    const id = insertTestWorktree({ status: 'created' });
    expect(() => transitionWorktreeStatus(db, id, 'ready')).toThrow('Invalid worktree transition');
  });

  test('rejects invalid transition from running', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    expect(() => transitionWorktreeStatus(db, id, 'ready')).toThrow('Invalid worktree transition');
  });
});
