// Generated by forge proof from work-group-id.md
import { describe, test, expect, beforeEach } from 'bun:test';
import {
  getTestDb,
  insertSpecEntry,
  listSpecEntriesByWorkGroup,
  listSpecEntries,
  getWorktreesByWorkGroup,
  insertWorktree,
  getWorktree,
} from './db.js';
import { generateWorkGroupId, deriveSpecName } from './utils.js';
import { findOrCreateEntry } from './specs.js';
import type { SpecManifest } from './types.js';
import type { Database } from 'bun:sqlite';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

// ── generateWorkGroupId ──────────────────────────────────────

describe('generateWorkGroupId', () => {
  test('generates ID with format wg-{timestamp}-{random}', () => {
    const id = generateWorkGroupId();
    expect(id).toMatch(/^wg-\d+-[0-9a-f]{4}$/);
  });

  test('timestamp portion is current epoch seconds', () => {
    const before = Math.floor(Date.now() / 1000);
    const id = generateWorkGroupId();
    const after = Math.floor(Date.now() / 1000);

    const parts = id.split('-');
    const timestamp = parseInt(parts[1], 10);
    expect(timestamp).toBeGreaterThanOrEqual(before);
    expect(timestamp).toBeLessThanOrEqual(after);
  });

  test('random suffix is 4 hex characters', () => {
    const id = generateWorkGroupId();
    const suffix = id.split('-')[2];
    expect(suffix).toMatch(/^[0-9a-f]{4}$/);
  });

  test('generates unique IDs across calls', () => {
    const ids = new Set<string>();
    for (let i = 0; i < 100; i++) {
      ids.add(generateWorkGroupId());
    }
    // With 4 hex chars of randomness, collisions should be extremely rare
    expect(ids.size).toBe(100);
  });

  test('ID is short enough for directory names', () => {
    const id = generateWorkGroupId();
    // wg-{10 digits}-{4 chars} = ~18 chars max
    expect(id.length).toBeLessThan(25);
  });

  test('ID contains only directory-safe characters', () => {
    const id = generateWorkGroupId();
    // Only lowercase alphanumeric and hyphens
    expect(id).toMatch(/^[a-z0-9-]+$/);
  });
});

// ── Work group ID in spec entries ────────────────────────────

describe('work group ID in spec entries', () => {
  test('spec entries store work_group_id', () => {
    const wgId = generateWorkGroupId();

    insertSpecEntry(db, {
      id: 'entry-1',
      spec: 'auth.md',
      status: 'pending',
      work_group_id: wgId,
    });

    const entries = listSpecEntriesByWorkGroup(db, wgId);
    expect(entries).toHaveLength(1);
    expect(entries[0].work_group_id).toBe(wgId);
  });

  test('multiple entries share the same work group ID', () => {
    const wgId = generateWorkGroupId();
    const specs = ['auth.md', 'api.md', 'ui.md'];

    for (const spec of specs) {
      insertSpecEntry(db, {
        id: `entry-${spec}`,
        spec,
        status: 'pending',
        work_group_id: wgId,
      });
    }

    const entries = listSpecEntriesByWorkGroup(db, wgId);
    expect(entries).toHaveLength(3);
    expect(entries.every(e => e.work_group_id === wgId)).toBe(true);
  });

  test('work_group_id is optional (null for legacy specs)', () => {
    insertSpecEntry(db, {
      id: 'legacy-entry',
      spec: 'legacy.md',
      status: 'pending',
      // No work_group_id
    });

    const entries = listSpecEntries(db);
    expect(entries).toHaveLength(1);
    expect(entries[0].work_group_id).toBeNull();
  });

  test('listSpecEntriesByWorkGroup returns only matching group', () => {
    const wgA = generateWorkGroupId();
    const wgB = generateWorkGroupId();

    insertSpecEntry(db, { id: 'a1', spec: 'a1.md', work_group_id: wgA });
    insertSpecEntry(db, { id: 'a2', spec: 'a2.md', work_group_id: wgA });
    insertSpecEntry(db, { id: 'b1', spec: 'b1.md', work_group_id: wgB });

    const groupA = listSpecEntriesByWorkGroup(db, wgA);
    expect(groupA).toHaveLength(2);

    const groupB = listSpecEntriesByWorkGroup(db, wgB);
    expect(groupB).toHaveLength(1);
  });
});

// ── Work group ID in worktrees ───────────────────────────────

describe('work group ID in worktrees', () => {
  test('getWorktreesByWorkGroup returns all worktrees for a work group', () => {
    const wgId = generateWorkGroupId();

    insertWorktree(db, {
      id: 'wt-1',
      work_group_id: wgId,
      spec_path: 'auth.md',
      branch: 'forge/auth',
      worktree_path: '/tmp/auth',
    });
    insertWorktree(db, {
      id: 'wt-2',
      work_group_id: wgId,
      spec_path: 'api.md',
      branch: 'forge/api',
      worktree_path: '/tmp/api',
    });
    insertWorktree(db, {
      id: 'wt-other',
      work_group_id: 'wg-other',
      spec_path: 'other.md',
      branch: 'forge/other',
      worktree_path: '/tmp/other',
    });

    const group = getWorktreesByWorkGroup(db, wgId);
    expect(group).toHaveLength(2);
    expect(group.every(w => w.work_group_id === wgId)).toBe(true);
  });

  test('work group spans both spec entries and worktrees', () => {
    const wgId = generateWorkGroupId();

    // Create spec entries with work group
    insertSpecEntry(db, { id: 'se-auth', spec: 'auth.md', work_group_id: wgId });
    insertSpecEntry(db, { id: 'se-api', spec: 'api.md', work_group_id: wgId });

    // Create worktrees with same work group
    insertWorktree(db, {
      id: 'wt-auth',
      work_group_id: wgId,
      spec_path: 'auth.md',
      branch: 'forge/auth',
      worktree_path: '/tmp/auth',
    });

    const specEntries = listSpecEntriesByWorkGroup(db, wgId);
    const worktrees = getWorktreesByWorkGroup(db, wgId);

    expect(specEntries).toHaveLength(2);
    expect(worktrees).toHaveLength(1);
  });
});

// ── Work group in manifest operations ────────────────────────

describe('findOrCreateEntry with workGroupId', () => {
  test('new entry receives work group ID', () => {
    const manifest: SpecManifest = { version: 1, specs: [] };
    const wgId = generateWorkGroupId();

    const entry = findOrCreateEntry(manifest, 'new.md', 'define:session-1', wgId);
    expect(entry.workGroupId).toBe(wgId);
  });

  test('existing entry without work group gets assigned', () => {
    const now = new Date().toISOString();
    const manifest: SpecManifest = {
      version: 1,
      specs: [{
        spec: 'existing.md',
        status: 'pending',
        runs: [],
        source: 'file',
        createdAt: now,
        updatedAt: now,
      }],
    };
    const wgId = generateWorkGroupId();

    const entry = findOrCreateEntry(manifest, 'existing.md', 'file', wgId);
    expect(entry.workGroupId).toBe(wgId);
  });

  test('existing entry with work group keeps original', () => {
    const now = new Date().toISOString();
    const originalWg = generateWorkGroupId();
    const newWg = generateWorkGroupId();

    const manifest: SpecManifest = {
      version: 1,
      specs: [{
        spec: 'grouped.md',
        status: 'pending',
        runs: [],
        source: 'file',
        workGroupId: originalWg,
        createdAt: now,
        updatedAt: now,
      }],
    };

    const entry = findOrCreateEntry(manifest, 'grouped.md', 'file', newWg);
    expect(entry.workGroupId).toBe(originalWg);
  });

  test('entry without explicit work group has undefined workGroupId', () => {
    const manifest: SpecManifest = { version: 1, specs: [] };
    const entry = findOrCreateEntry(manifest, 'no-wg.md', 'file');
    expect(entry.workGroupId).toBeUndefined();
  });
});

// ── Auto-minting behavior ────────────────────────────────────

describe('auto-minting work group ID', () => {
  test('legacy specs without work group receive auto-minted ID via findOrCreateEntry', () => {
    const manifest: SpecManifest = { version: 1, specs: [] };

    // Simulate what runForge does: auto-mint at run time
    const autoMintedWg = generateWorkGroupId();
    const entry = findOrCreateEntry(manifest, 'legacy.md', 'file', autoMintedWg);

    expect(entry.workGroupId).toBe(autoMintedWg);
    expect(entry.workGroupId).toMatch(/^wg-/);
  });

  test('ForgeResult.workGroupId is defined in type shape', () => {
    // Verify the type exists by importing and constructing
    const result = {
      startedAt: new Date().toISOString(),
      completedAt: new Date().toISOString(),
      durationSeconds: 10,
      status: 'success' as const,
      prompt: 'test',
      model: 'sonnet',
      cwd: '/tmp',
      type: 'define' as const,
      workGroupId: generateWorkGroupId(),
    };

    expect(result.workGroupId).toMatch(/^wg-/);
  });
});
