// Generated by forge proof from worktree-registry-schema.md, worktree-persistent-lifecycle.md
import { describe, test, expect, beforeEach } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  getWorktreeByPath,
  getWorktreeByBranch,
  listWorktrees,
  getWorktreesByWorkGroup,
  updateWorktreeStatus,
  updateWorktreeSpecPaths,
  updateWorktreePid,
  linkWorktreeTask,
  linkWorktreeSession,
  transitionWorktreeStatus,
  getValidTransitions,
  querySessionsByWorktree,
  insertSession,
  insertTask,
} from './db.js';
import type { Database } from 'bun:sqlite';
import type { WorktreeStatus } from './db.js';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function makeWorktreeId(): string {
  return `wt-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeWorktreeId();
  insertWorktree(db, {
    id,
    spec_path: 'specs/auth-login.md',
    branch: 'forge/auth-login',
    worktree_path: '/tmp/project-auth-login',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── Schema ──────────────────────────────────────────────────

describe('worktrees table schema', () => {
  test('worktrees table exists with correct columns', () => {
    const cols = db.query("PRAGMA table_info(worktrees)").all() as Array<{ name: string }>;
    const colNames = cols.map(c => c.name);
    expect(colNames).toContain('id');
    expect(colNames).toContain('work_group_id');
    expect(colNames).toContain('spec_path');
    expect(colNames).toContain('spec_paths');
    expect(colNames).toContain('branch');
    expect(colNames).toContain('worktree_path');
    expect(colNames).toContain('status');
    expect(colNames).toContain('linear_issue_id');
    expect(colNames).toContain('pid');
    expect(colNames).toContain('task_id');
    expect(colNames).toContain('session_id');
    expect(colNames).toContain('error');
    expect(colNames).toContain('created_at');
    expect(colNames).toContain('updated_at');
  });

  test('indexes exist on worktrees table', () => {
    const indexes = db.query("PRAGMA index_list(worktrees)").all() as Array<{ name: string }>;
    const names = indexes.map(i => i.name);
    expect(names).toContain('idx_worktrees_status');
    expect(names).toContain('idx_worktrees_work_group_id');
    expect(names).toContain('idx_worktrees_branch');
    expect(names).toContain('idx_worktrees_task_id');
  });

  test('status CHECK constraint limits to valid values', () => {
    expect(() => {
      db.run(
        `INSERT INTO worktrees (id, spec_path, spec_paths, branch, worktree_path, status, created_at, updated_at)
         VALUES ('bad-id', 'spec.md', '[]', 'branch', '/tmp/bad', 'invalid_status', datetime('now'), datetime('now'))`,
      );
    }).toThrow();
  });
});

// ── Worktree CRUD ────────────────────────────────────────────

describe('insertWorktree / getWorktree', () => {
  test('inserts and retrieves a worktree by ID', () => {
    const id = insertTestWorktree({ work_group_id: 'wg-123', linear_issue_id: 'ENG-42' });

    const wt = getWorktree(db, id);
    expect(wt).not.toBeNull();
    expect(wt!.id).toBe(id);
    expect(wt!.spec_path).toBe('specs/auth-login.md');
    expect(wt!.branch).toBe('forge/auth-login');
    expect(wt!.worktree_path).toBe('/tmp/project-auth-login');
    expect(wt!.status).toBe('created');
    expect(wt!.work_group_id).toBe('wg-123');
    expect(wt!.linear_issue_id).toBe('ENG-42');
    expect(wt!.spec_paths).toBe('[]');
    expect(wt!.pid).toBeNull();
    expect(wt!.task_id).toBeNull();
    expect(wt!.session_id).toBeNull();
    expect(wt!.error).toBeNull();
  });

  test('INSERT OR IGNORE skips duplicate IDs', () => {
    const id = insertTestWorktree({ spec_path: 'first.md' });
    insertWorktree(db, {
      id,
      spec_path: 'second.md',
      branch: 'forge/second',
      worktree_path: '/tmp/second',
    });

    const wt = getWorktree(db, id);
    expect(wt!.spec_path).toBe('first.md');
  });

  test('returns null for non-existent ID', () => {
    expect(getWorktree(db, 'nonexistent')).toBeNull();
  });

  test('stores spec_paths as JSON array', () => {
    const id = makeWorktreeId();
    insertWorktree(db, {
      id,
      spec_path: 'specs/',
      spec_paths: ['specs/a.md', 'specs/b.md'],
      branch: 'forge/multi',
      worktree_path: '/tmp/multi',
    });

    const wt = getWorktree(db, id);
    expect(JSON.parse(wt!.spec_paths)).toEqual(['specs/a.md', 'specs/b.md']);
  });
});

describe('getWorktreeByPath', () => {
  test('retrieves worktree by filesystem path', () => {
    const id = insertTestWorktree({ worktree_path: '/home/dev/project-auth' });
    const wt = getWorktreeByPath(db, '/home/dev/project-auth');
    expect(wt).not.toBeNull();
    expect(wt!.id).toBe(id);
  });

  test('returns the newest row when multiple worktrees share a path', () => {
    const olderId = insertTestWorktree({
      status: 'complete',
      branch: 'forge/older',
      worktree_path: '/tmp/reused-path',
    });
    const newerId = insertTestWorktree({
      status: 'created',
      branch: 'forge/newer',
      worktree_path: '/tmp/reused-path',
    });

    const wt = getWorktreeByPath(db, '/tmp/reused-path');
    expect(wt).not.toBeNull();
    expect(wt!.id).toBe(newerId);
    expect(wt!.id).not.toBe(olderId);
    expect(wt!.status).toBe('created');
  });

  test('returns null for non-existent path', () => {
    expect(getWorktreeByPath(db, '/no/such/path')).toBeNull();
  });
});

describe('getWorktreeByBranch', () => {
  test('retrieves worktree by branch name', () => {
    const id = insertTestWorktree({ branch: 'forge/ENG-123/api-setup' });
    const wt = getWorktreeByBranch(db, 'forge/ENG-123/api-setup');
    expect(wt).not.toBeNull();
    expect(wt!.id).toBe(id);
  });

  test('returns the newest row when multiple worktrees share a branch', () => {
    const olderId = insertTestWorktree({
      status: 'complete',
      branch: 'forge/reused-branch',
      worktree_path: '/tmp/branch-old',
    });
    const newerId = insertTestWorktree({
      status: 'created',
      branch: 'forge/reused-branch',
      worktree_path: '/tmp/branch-new',
    });

    const wt = getWorktreeByBranch(db, 'forge/reused-branch');
    expect(wt).not.toBeNull();
    expect(wt!.id).toBe(newerId);
    expect(wt!.id).not.toBe(olderId);
    expect(wt!.status).toBe('created');
  });

  test('returns null for non-existent branch', () => {
    expect(getWorktreeByBranch(db, 'no-such-branch')).toBeNull();
  });
});

describe('listWorktrees', () => {
  test('returns all worktrees ordered by created_at DESC', () => {
    insertTestWorktree({ spec_path: 'a.md', branch: 'forge/a', worktree_path: '/tmp/a' });
    insertTestWorktree({ spec_path: 'b.md', branch: 'forge/b', worktree_path: '/tmp/b' });

    const all = listWorktrees(db);
    expect(all).toHaveLength(2);
    // DESC order: second inserted is more recent
    expect(all[0].spec_path).toBe('b.md');
    expect(all[1].spec_path).toBe('a.md');
  });

  test('filters by status', () => {
    insertTestWorktree({ status: 'running', branch: 'forge/r1', worktree_path: '/tmp/r1' });
    insertTestWorktree({ status: 'complete', branch: 'forge/c1', worktree_path: '/tmp/c1' });
    insertTestWorktree({ status: 'running', branch: 'forge/r2', worktree_path: '/tmp/r2' });

    const running = listWorktrees(db, 'running');
    expect(running).toHaveLength(2);
    expect(running.every(w => w.status === 'running')).toBe(true);
  });

  test('returns empty array when no worktrees', () => {
    expect(listWorktrees(db)).toEqual([]);
  });
});

describe('getWorktreesByWorkGroup', () => {
  test('returns worktrees for a work group ordered by created_at ASC', () => {
    insertTestWorktree({ work_group_id: 'wg-A', spec_path: 'first.md', branch: 'forge/f', worktree_path: '/tmp/f' });
    insertTestWorktree({ work_group_id: 'wg-A', spec_path: 'second.md', branch: 'forge/s', worktree_path: '/tmp/s' });
    insertTestWorktree({ work_group_id: 'wg-B', spec_path: 'other.md', branch: 'forge/o', worktree_path: '/tmp/o' });

    const groupA = getWorktreesByWorkGroup(db, 'wg-A');
    expect(groupA).toHaveLength(2);
    // ASC order
    expect(groupA[0].spec_path).toBe('first.md');
    expect(groupA[1].spec_path).toBe('second.md');
  });

  test('returns empty for non-existent work group', () => {
    expect(getWorktreesByWorkGroup(db, 'wg-nope')).toEqual([]);
  });
});

// ── Update Helpers ──────────────────────────────────────────

describe('updateWorktreeStatus', () => {
  test('updates status and clears error by default', () => {
    const id = insertTestWorktree();
    updateWorktreeStatus(db, id, 'running');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('running');
    expect(wt!.error).toBeNull();
  });

  test('stores error message when provided', () => {
    const id = insertTestWorktree();
    updateWorktreeStatus(db, id, 'failed', 'Build failed');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('failed');
    expect(wt!.error).toBe('Build failed');
  });
});

describe('updateWorktreeSpecPaths', () => {
  test('updates spec_paths JSON array', () => {
    const id = insertTestWorktree();
    updateWorktreeSpecPaths(db, id, ['specs/a.md', 'specs/b.md', 'specs/c.md']);

    const wt = getWorktree(db, id);
    expect(JSON.parse(wt!.spec_paths)).toEqual(['specs/a.md', 'specs/b.md', 'specs/c.md']);
  });
});

describe('updateWorktreePid', () => {
  test('sets the executor PID', () => {
    const id = insertTestWorktree();
    updateWorktreePid(db, id, 12345);

    const wt = getWorktree(db, id);
    expect(wt!.pid).toBe(12345);
  });
});

describe('linkWorktreeTask', () => {
  test('sets the task_id', () => {
    const id = insertTestWorktree();
    linkWorktreeTask(db, id, 'task-abc');

    const wt = getWorktree(db, id);
    expect(wt!.task_id).toBe('task-abc');
  });
});

describe('linkWorktreeSession', () => {
  test('sets the session_id', () => {
    const id = insertTestWorktree();
    linkWorktreeSession(db, id, 'sess-xyz');

    const wt = getWorktree(db, id);
    expect(wt!.session_id).toBe('sess-xyz');
  });
});

// ── State Machine ────────────────────────────────────────────

describe('transitionWorktreeStatus', () => {
  test('valid transition: created -> running', () => {
    const id = insertTestWorktree({ status: 'created' });
    const { previousStatus } = transitionWorktreeStatus(db, id, 'running');

    expect(previousStatus).toBe('created');
    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('running');
  });

  test('valid transition: running -> complete', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');

    expect(getWorktree(db, id)!.status).toBe('complete');
  });

  test('valid transition: complete -> ready (skip audit+proof)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');

    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('valid transition: merge_failed -> ready (retry)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');
    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merge_failed');
    transitionWorktreeStatus(db, id, 'ready');

    expect(getWorktree(db, id)!.status).toBe('ready');
  });

  test('valid full lifecycle: created -> running -> complete -> auditing -> audited -> proofing -> proofed -> ready -> merging -> merged -> cleaned', () => {
    const id = insertTestWorktree({ status: 'created' });
    const transitions: WorktreeStatus[] = [
      'running', 'complete', 'auditing', 'audited',
      'proofing', 'proofed', 'ready', 'merging', 'merged', 'cleaned',
    ];

    for (const next of transitions) {
      transitionWorktreeStatus(db, id, next);
    }

    expect(getWorktree(db, id)!.status).toBe('cleaned');
  });

  test('invalid transition throws: created -> complete', () => {
    const id = insertTestWorktree({ status: 'created' });
    expect(() => transitionWorktreeStatus(db, id, 'complete')).toThrow('Invalid worktree transition');
  });

  test('invalid transition throws: cleaned -> running (terminal)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');
    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merged');
    transitionWorktreeStatus(db, id, 'cleaned');

    expect(() => transitionWorktreeStatus(db, id, 'running')).toThrow('Invalid worktree transition');
  });

  test('invalid transition throws: running -> ready (must go through complete)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    expect(() => transitionWorktreeStatus(db, id, 'ready')).toThrow('Invalid worktree transition');
  });

  test('stores error on failure transitions', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'failed', 'Setup failed: bun install');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('failed');
    expect(wt!.error).toBe('Setup failed: bun install');
  });

  test('clears error on non-error transitions', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'failed', 'Some error');
    transitionWorktreeStatus(db, id, 'created'); // failed -> created retry

    const wt = getWorktree(db, id);
    expect(wt!.error).toBeNull();
  });

  test('throws for non-existent worktree', () => {
    expect(() => transitionWorktreeStatus(db, 'nonexistent', 'running')).toThrow('Worktree not found');
  });

  test('merging -> paused (git conflict)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');
    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'paused', 'Conflict in: src/auth.ts, src/db.ts');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('paused');
    expect(wt!.error).toBe('Conflict in: src/auth.ts, src/db.ts');
  });

  test('merging -> merge_failed (type-check failure)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');
    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'merge_failed', 'Type errors could not be fixed');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('merge_failed');
  });

  test('paused -> merging (resume after manual fix)', () => {
    const id = insertTestWorktree({ status: 'created' });
    transitionWorktreeStatus(db, id, 'running');
    transitionWorktreeStatus(db, id, 'complete');
    transitionWorktreeStatus(db, id, 'ready');
    transitionWorktreeStatus(db, id, 'merging');
    transitionWorktreeStatus(db, id, 'paused');
    transitionWorktreeStatus(db, id, 'merging');

    expect(getWorktree(db, id)!.status).toBe('merging');
  });
});

describe('getValidTransitions', () => {
  test('created allows running and failed', () => {
    expect(getValidTransitions('created')).toEqual(['running', 'failed']);
  });

  test('running allows complete and failed', () => {
    expect(getValidTransitions('running')).toEqual(['complete', 'failed']);
  });

  test('complete allows auditing, proofing, and ready', () => {
    expect(getValidTransitions('complete')).toEqual(['auditing', 'proofing', 'ready']);
  });

  test('cleaned has no valid transitions (terminal)', () => {
    expect(getValidTransitions('cleaned')).toEqual([]);
  });

  test('merging allows merged, merge_failed, and paused', () => {
    expect(getValidTransitions('merging')).toEqual(['merged', 'merge_failed', 'paused']);
  });

  test('merge_failed allows ready', () => {
    expect(getValidTransitions('merge_failed')).toEqual(['ready']);
  });
});

// ── Session-Worktree Association ─────────────────────────────

describe('querySessionsByWorktree', () => {
  test('finds sessions via direct session_id link', () => {
    const wtId = insertTestWorktree({ session_id: 'sess-direct' });

    insertSession(db, { id: 'sess-direct', startedAt: '2026-01-01T00:00:00Z' });

    const sessions = querySessionsByWorktree(db, wtId);
    expect(sessions).toHaveLength(1);
    expect(sessions[0].id).toBe('sess-direct');
  });

  test('finds sessions via task cwd join', () => {
    const wtId = insertTestWorktree({ worktree_path: '/tmp/my-worktree' });

    insertSession(db, { id: 'sess-task', startedAt: '2026-01-01T00:00:00Z' });
    insertTask(db, {
      id: 'task-1',
      command: 'run',
      status: 'completed',
      cwd: '/tmp/my-worktree',
      sessionId: 'sess-task',
    });

    const sessions = querySessionsByWorktree(db, wtId);
    expect(sessions).toHaveLength(1);
    expect(sessions[0].id).toBe('sess-task');
  });

  test('deduplicates sessions found via both paths', () => {
    const wtId = insertTestWorktree({
      worktree_path: '/tmp/dedup-wt',
      session_id: 'sess-both',
    });

    insertSession(db, { id: 'sess-both', startedAt: '2026-01-01T00:00:00Z' });
    insertTask(db, {
      id: 'task-dedup',
      command: 'run',
      status: 'completed',
      cwd: '/tmp/dedup-wt',
      sessionId: 'sess-both',
    });

    const sessions = querySessionsByWorktree(db, wtId);
    expect(sessions).toHaveLength(1);
  });

  test('returns empty for worktree with no sessions', () => {
    const wtId = insertTestWorktree();
    expect(querySessionsByWorktree(db, wtId)).toEqual([]);
  });

  test('sessions ordered by startedAt ASC', () => {
    const wtId = insertTestWorktree({ session_id: 'sess-2' });

    insertSession(db, { id: 'sess-2', startedAt: '2026-01-02T00:00:00Z' });
    // Add another session via task path
    insertSession(db, { id: 'sess-1', startedAt: '2026-01-01T00:00:00Z' });
    insertTask(db, {
      id: 'task-order',
      command: 'run',
      status: 'completed',
      cwd: getWorktree(db, wtId)!.worktree_path,
      sessionId: 'sess-1',
    });

    const sessions = querySessionsByWorktree(db, wtId);
    expect(sessions).toHaveLength(2);
    expect(sessions[0].id).toBe('sess-1');
    expect(sessions[1].id).toBe('sess-2');
  });
});
