// Generated by forge proof from worktree-limits.md
// Canonical worktree-limits test suite (consolidated from worktree-limits.test.ts + proof)
import { describe, test, expect, beforeAll, afterAll, beforeEach, afterEach } from 'bun:test';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  listWorktrees,
  updateWorktreeStatus,
} from './db.js';
import type { Database } from 'bun:sqlite';
import type { WorktreeRow, WorktreeStatus } from './db.js';
import {
  calculateWorktreeDiskUsage,
  countActiveWorktrees,
  checkWorktreeLimits,
} from './worktree-limits.js';
import { CONFIG_DEFAULTS, clearConfigCache, getConfig } from './config.js';
import { execAsync, createWorktree, cleanupWorktree } from './utils.js';
import { setupHermeticGit, teardownHermeticGit } from './test-utils.js';

let db: Database;
let tmpDirs: string[];

beforeEach(() => {
  db = getTestDb();
  tmpDirs = [];
  clearConfigCache();
});

afterEach(async () => {
  clearConfigCache();
  for (const dir of tmpDirs) {
    await fs.rm(dir, { recursive: true, force: true }).catch(() => {});
  }
});

function makeId(): string {
  return `wt-lim-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function fakeWorktreeRow(overrides: Partial<WorktreeRow> = {}): WorktreeRow {
  const id = makeId();
  return {
    id,
    work_group_id: null,
    spec_path: 'specs/test.md',
    spec_paths: '[]',
    branch: `forge/test-${id}`,
    worktree_path: '/tmp/nonexistent-lim',
    status: 'complete',
    linear_issue_id: null,
    pid: null,
    task_id: null,
    session_id: null,
    error: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...overrides,
  };
}

// ── Config defaults ─────────────────────────────────────────────

describe('worktree limit config defaults', () => {
  test('maxWorktrees defaults to 10', () => {
    expect(CONFIG_DEFAULTS.maxWorktrees).toBe(10);
  });

  test('maxWorktreeDiskMb defaults to 5000 (5GB)', () => {
    expect(CONFIG_DEFAULTS.maxWorktreeDiskMb).toBe(5000);
  });

  test('config loaded from .forge/config.json', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-cfg-'));
    tmpDirs.push(tmpDir);

    const forgeDir = path.join(tmpDir, '.forge');
    await fs.mkdir(forgeDir, { recursive: true });
    await fs.writeFile(
      path.join(forgeDir, 'config.json'),
      JSON.stringify({ maxWorktrees: 20, maxWorktreeDiskMb: 8000 }),
    );

    const config = getConfig(tmpDir);
    expect(config.maxWorktrees).toBe(20);
    expect(config.maxWorktreeDiskMb).toBe(8000);
  });

  test('invalid config values fall back to defaults', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-invalid-'));
    tmpDirs.push(tmpDir);

    const forgeDir = path.join(tmpDir, '.forge');
    await fs.mkdir(forgeDir, { recursive: true });
    await fs.writeFile(
      path.join(forgeDir, 'config.json'),
      JSON.stringify({ maxWorktrees: -5, maxWorktreeDiskMb: 'not-a-number' }),
    );

    const config = getConfig(tmpDir);
    expect(config.maxWorktrees).toBe(10); // fallback to default
    expect(config.maxWorktreeDiskMb).toBe(5000); // fallback to default
  });

  test('env override FORGE_MAX_WORKTREES takes precedence', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-env-'));
    tmpDirs.push(tmpDir);

    const prev = process.env.FORGE_MAX_WORKTREES;
    process.env.FORGE_MAX_WORKTREES = '25';

    try {
      const config = getConfig(tmpDir);
      expect(config.maxWorktrees).toBe(25);
    } finally {
      if (prev === undefined) delete process.env.FORGE_MAX_WORKTREES;
      else process.env.FORGE_MAX_WORKTREES = prev;
    }
  });

  test('env override FORGE_MAX_WORKTREE_DISK_MB takes precedence', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-env-disk-'));
    tmpDirs.push(tmpDir);

    const prev = process.env.FORGE_MAX_WORKTREE_DISK_MB;
    process.env.FORGE_MAX_WORKTREE_DISK_MB = '3000';

    try {
      const config = getConfig(tmpDir);
      expect(config.maxWorktreeDiskMb).toBe(3000);
    } finally {
      if (prev === undefined) delete process.env.FORGE_MAX_WORKTREE_DISK_MB;
      else process.env.FORGE_MAX_WORKTREE_DISK_MB = prev;
    }
  });
});

// ── Active worktree count ───────────────────────────────────────

describe('active worktree counting (status not in cleaned)', () => {
  test('counts all non-cleaned statuses as active', () => {
    const activeStatuses: WorktreeStatus[] = [
      'created', 'running', 'complete', 'failed',
      'auditing', 'audited', 'proofing', 'proofed',
      'ready', 'paused', 'merging', 'merge_failed', 'merged',
    ];

    const rows = activeStatuses.map(s => fakeWorktreeRow({ status: s }));
    expect(countActiveWorktrees(rows)).toBe(activeStatuses.length);
  });

  test('cleaned status is excluded from active count', () => {
    const rows = [
      fakeWorktreeRow({ status: 'complete' }),
      fakeWorktreeRow({ status: 'cleaned' }),
      fakeWorktreeRow({ status: 'merged' }),
    ];
    expect(countActiveWorktrees(rows)).toBe(2); // complete + merged
  });

  test('merged worktrees count as active (still have directories)', () => {
    const rows = [
      fakeWorktreeRow({ status: 'merged' }),
    ];
    expect(countActiveWorktrees(rows)).toBe(1);
  });
});

// ── Disk usage calculation ──────────────────────────────────────

describe('disk usage calculation', () => {
  test('returns 0 for empty worktree list', async () => {
    expect(await calculateWorktreeDiskUsage([])).toBe(0);
  });

  test('skips cleaned worktrees (no directory on disk)', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-disk-'));
    tmpDirs.push(tmpDir);
    await fs.writeFile(path.join(tmpDir, 'data.txt'), 'x'.repeat(10000));

    const rows = [fakeWorktreeRow({ status: 'cleaned', worktree_path: tmpDir })];
    expect(await calculateWorktreeDiskUsage(rows)).toBe(0);
  });

  test('measures real directory sizes for non-cleaned worktrees', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-measure-'));
    tmpDirs.push(tmpDir);
    await fs.writeFile(path.join(tmpDir, 'data.txt'), 'x'.repeat(1024 * 100)); // ~100KB

    const rows = [fakeWorktreeRow({ status: 'complete', worktree_path: tmpDir })];
    const usage = await calculateWorktreeDiskUsage(rows);
    expect(usage).toBeGreaterThan(0);
  });

  test('returns -1 when all directories are unmeasurable', async () => {
    const rows = [
      fakeWorktreeRow({ status: 'complete', worktree_path: '/tmp/nonexistent-forge-xyz-abc' }),
    ];
    expect(await calculateWorktreeDiskUsage(rows)).toBe(-1);
  });

  test('best-effort: unmeasurable directories are skipped without error', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-partial-'));
    tmpDirs.push(tmpDir);
    await fs.writeFile(path.join(tmpDir, 'data.txt'), 'x'.repeat(1024 * 50));

    const rows = [
      fakeWorktreeRow({ status: 'complete', worktree_path: tmpDir }),
      fakeWorktreeRow({ status: 'running', worktree_path: '/tmp/nonexistent-forge-partial-xyz' }),
    ];

    const usage = await calculateWorktreeDiskUsage(rows);
    // Should still return a valid number (measured the existing dir)
    expect(usage).toBeGreaterThan(0);
  });
});

// ── Error message content ───────────────────────────────────────

describe('limit exceeded error messages', () => {
  test('count limit error includes active count and max', () => {
    const activeCount = 10;
    const maxWorktrees = 10;
    const error = `Worktree limit reached: ${activeCount}/${maxWorktrees} active worktrees.`;
    expect(error).toContain('10/10');
    expect(error).toContain('limit reached');
  });

  test('count limit error suggests forge worktree prune', () => {
    const error = [
      'Worktree limit reached: 10/10 active worktrees.',
      '',
      'To free up worktrees, run:  forge worktree prune',
    ].join('\n');
    expect(error).toContain('forge worktree prune');
  });

  test('disk limit error includes current usage and max', () => {
    const diskUsageMb = 5200;
    const maxDiskMb = 5000;
    const error = `Worktree disk limit reached: ${diskUsageMb}MB / ${maxDiskMb}MB used.`;
    expect(error).toContain('5200MB');
    expect(error).toContain('5000MB');
  });

  test('disk limit error suggests forge worktree prune', () => {
    const error = [
      'Worktree disk limit reached: 5200MB / 5000MB used.',
      '',
      'To free up disk space, run:  forge worktree prune',
    ].join('\n');
    expect(error).toContain('forge worktree prune');
  });

  test('error messages mention --force flag as override', () => {
    const error = 'To override this limit:     use --force flag';
    expect(error).toContain('--force');
  });
});

// ── Limits are per-project (scoped to git repo root) ────────────

describe('per-project limit scoping', () => {
  test('config is loaded from the working directory .forge/config.json', async () => {
    const dir1 = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-proj1-'));
    const dir2 = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-lim-proj2-'));
    tmpDirs.push(dir1, dir2);

    await fs.mkdir(path.join(dir1, '.forge'), { recursive: true });
    await fs.mkdir(path.join(dir2, '.forge'), { recursive: true });
    await fs.writeFile(path.join(dir1, '.forge', 'config.json'), JSON.stringify({ maxWorktrees: 5 }));
    await fs.writeFile(path.join(dir2, '.forge', 'config.json'), JSON.stringify({ maxWorktrees: 15 }));

    const config1 = getConfig(dir1);
    const config2 = getConfig(dir2);

    expect(config1.maxWorktrees).toBe(5);
    expect(config2.maxWorktrees).toBe(15);
  });
});

// ── Integration: createWorktree respects limits ───────────────

describe('createWorktree limit enforcement', () => {
  let tmpDir: string;

  beforeAll(() => { setupHermeticGit(); });
  afterAll(() => { teardownHermeticGit(); });

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-wt-limits-int-'));
    await execAsync('git init', { cwd: tmpDir });
    await execAsync('git config user.email "test@forge.dev"', { cwd: tmpDir });
    await execAsync('git config user.name "Forge Test"', { cwd: tmpDir });
    await fs.writeFile(path.join(tmpDir, 'README.md'), '# Test\n');
    await execAsync('git add -A && git commit -m "init"', { cwd: tmpDir });
    clearConfigCache();
  });

  afterEach(async () => {
    clearConfigCache();
    try { await execAsync('git worktree prune', { cwd: tmpDir }); } catch {}
    await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  });

  async function writeConfig(config: Record<string, unknown>) {
    const dir = path.join(tmpDir, '.forge');
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(path.join(dir, 'config.json'), JSON.stringify(config, null, 2));
    clearConfigCache();
  }

  test('createWorktree respects limits', async () => {
    await writeConfig({ maxWorktrees: 1, maxWorktreeDiskMb: 5000 });
    const wt1 = await createWorktree(tmpDir, 'ignored', { spec_path: 'specs/first.md' });
    try {
      await expect(
        createWorktree(tmpDir, 'ignored', { spec_path: 'specs/second.md' })
      ).rejects.toThrow('Worktree limit reached');
    } finally {
      await cleanupWorktree(wt1, tmpDir);
    }
  });

  test('createWorktree allows bypass with force', async () => {
    await writeConfig({ maxWorktrees: 1, maxWorktreeDiskMb: 5000 });
    const wt1 = await createWorktree(tmpDir, 'ignored', { spec_path: 'specs/first.md', force: true });
    let wt2: string | undefined;
    try {
      wt2 = await createWorktree(tmpDir, 'ignored', { spec_path: 'specs/second.md', force: true });
      expect(wt2).toBeTruthy();
    } finally {
      await cleanupWorktree(wt1, tmpDir);
      if (wt2) await cleanupWorktree(wt2, tmpDir);
    }
  });

  test('checkWorktreeLimits returns ok when DB unavailable', async () => {
    const noDbDir = await fs.mkdtemp(path.join(os.tmpdir(), 'forge-wt-nodb-'));
    try {
      const result = await checkWorktreeLimits(noDbDir);
      expect(result.ok).toBe(true);
    } finally {
      await fs.rm(noDbDir, { recursive: true, force: true });
    }
  });
});
