// Generated by forge proof from worktree-prune.md
import { describe, test, expect, beforeEach, spyOn } from 'bun:test';
import {
  getTestDb,
  insertWorktree,
  getWorktree,
  listWorktrees,
  transitionWorktreeStatus,
  updateWorktreeStatus,
  updateWorktreePid,
} from './db.js';
import type { Database } from 'bun:sqlite';
import type { WorktreeStatus } from './db.js';

let db: Database;

beforeEach(() => {
  db = getTestDb();
});

function makeId(): string {
  return `wt-prune-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`;
}

function insertTestWorktree(overrides: Partial<Parameters<typeof insertWorktree>[1]> = {}): string {
  const id = overrides.id ?? makeId();
  insertWorktree(db, {
    id,
    spec_path: 'specs/test.md',
    branch: 'forge/test',
    worktree_path: '/tmp/project-test',
    status: 'created',
    ...overrides,
  });
  return id;
}

// ── Prune targets: merged and cleaned ───────────────────────────

describe('prune target identification', () => {
  test('worktrees with status merged are prunable', () => {
    const id = insertTestWorktree({ status: 'merged', branch: 'forge/m1', worktree_path: '/tmp/m1' });
    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('merged');

    // Default prune targets: merged and cleaned
    const prunableStatuses = new Set<WorktreeStatus>(['merged', 'cleaned']);
    expect(prunableStatuses.has(wt!.status)).toBe(true);
  });

  test('worktrees with status cleaned are prunable', () => {
    const id = insertTestWorktree({ status: 'cleaned', branch: 'forge/c1', worktree_path: '/tmp/c1' });
    const wt = getWorktree(db, id);
    expect(prunableDefault(wt!.status)).toBe(true);
  });

  test('running worktrees are never prunable', () => {
    const id = insertTestWorktree({ status: 'running', branch: 'forge/r1', worktree_path: '/tmp/r1' });
    const wt = getWorktree(db, id);
    const activeStatuses = new Set<WorktreeStatus>(['running', 'auditing', 'proofing', 'merging']);
    expect(activeStatuses.has(wt!.status)).toBe(true);
  });

  test('complete worktrees are not prunable by default', () => {
    const id = insertTestWorktree({ status: 'complete', branch: 'forge/co1', worktree_path: '/tmp/co1' });
    const wt = getWorktree(db, id);
    expect(prunableDefault(wt!.status)).toBe(false);
  });

  test('failed worktrees are not prunable by default', () => {
    const id = insertTestWorktree({ status: 'failed', branch: 'forge/f1', worktree_path: '/tmp/f1' });
    const wt = getWorktree(db, id);
    expect(prunableDefault(wt!.status)).toBe(false);
  });
});

// Helper: match the pruneWorktrees default prunable set
function prunableDefault(status: WorktreeStatus): boolean {
  const set = new Set<WorktreeStatus>(['merged', 'cleaned']);
  return set.has(status);
}

// ── Force prune expands target set ──────────────────────────────

describe('force prune targets', () => {
  test('--force allows pruning complete worktrees', () => {
    const forceSet = new Set<WorktreeStatus>([
      'created', 'complete', 'failed', 'audited', 'proofed',
      'ready', 'paused', 'merge_failed', 'merged', 'cleaned',
    ]);
    expect(forceSet.has('complete')).toBe(true);
  });

  test('--force allows pruning failed worktrees', () => {
    const forceSet = new Set<WorktreeStatus>([
      'created', 'complete', 'failed', 'audited', 'proofed',
      'ready', 'paused', 'merge_failed', 'merged', 'cleaned',
    ]);
    expect(forceSet.has('failed')).toBe(true);
  });

  test('--force still does not prune running worktrees', () => {
    const activeStatuses = new Set<WorktreeStatus>(['running', 'auditing', 'proofing', 'merging']);
    for (const status of activeStatuses) {
      expect(activeStatuses.has(status)).toBe(true);
    }
  });
});

// ── Stale detection: PID liveness ───────────────────────────────

describe('stale detection via PID liveness', () => {
  test('running worktree with dead PID should be marked failed', () => {
    const id = insertTestWorktree({
      status: 'running',
      branch: 'forge/stale-pid',
      worktree_path: '/tmp/stale-pid',
    });
    // Set a PID that is definitely not alive (very high number)
    updateWorktreePid(db, id, 999999999);

    // Simulate stale detection: check if PID is alive
    const wt = getWorktree(db, id);
    let pidAlive = false;
    try {
      process.kill(wt!.pid!, 0);
      pidAlive = true;
    } catch {
      pidAlive = false;
    }

    expect(pidAlive).toBe(false);

    // Mark as failed (what detectAndMarkStale does)
    updateWorktreeStatus(db, id, 'failed', `Stale: process ${wt!.pid} no longer alive`);

    const updated = getWorktree(db, id);
    expect(updated!.status).toBe('failed');
    expect(updated!.error).toContain('Stale');
    expect(updated!.error).toContain('999999999');
  });

  test('running worktree with alive PID should not be marked stale', () => {
    const id = insertTestWorktree({
      status: 'running',
      branch: 'forge/alive-pid',
      worktree_path: '/tmp/alive-pid',
    });
    // Use current process PID (which is always alive)
    updateWorktreePid(db, id, process.pid);

    let pidAlive = false;
    try {
      process.kill(process.pid, 0);
      pidAlive = true;
    } catch {
      pidAlive = false;
    }

    expect(pidAlive).toBe(true);
    // Should NOT be marked stale
    expect(getWorktree(db, id)!.status).toBe('running');
  });

  test('running worktree without PID is not checked for liveness', () => {
    const id = insertTestWorktree({
      status: 'running',
      branch: 'forge/no-pid',
      worktree_path: '/tmp/no-pid',
    });

    const wt = getWorktree(db, id);
    expect(wt!.pid).toBeNull();
    // No PID means no liveness check -- should remain running
    expect(wt!.status).toBe('running');
  });
});

// ── Stale detection: TTL-based ──────────────────────────────────

describe('TTL-based stale detection', () => {
  test('non-terminal worktree older than TTL is flagged stale', () => {
    const oldDate = new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(); // 10 days ago
    const id = insertTestWorktree({
      status: 'complete',
      branch: 'forge/ttl-old',
      worktree_path: '/tmp/ttl-old',
    });
    // Manually set updated_at to be old
    db.run('UPDATE worktrees SET updated_at = ? WHERE id = ?', [oldDate, id]);

    const wt = getWorktree(db, id);
    const age = Date.now() - new Date(wt!.updated_at).getTime();
    const ttlMs = 7 * 24 * 60 * 60 * 1000; // 7 days default

    expect(age).toBeGreaterThan(ttlMs);

    // Simulate TTL stale detection
    const terminalStatuses: WorktreeStatus[] = ['merged', 'cleaned'];
    const activeStatuses: WorktreeStatus[] = ['running', 'auditing', 'proofing', 'merging'];
    const shouldFlag = !terminalStatuses.includes(wt!.status) && !activeStatuses.includes(wt!.status);
    expect(shouldFlag).toBe(true);
  });

  test('terminal statuses (merged, cleaned) are not flagged by TTL', () => {
    const oldDate = new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString();
    const terminalStatuses: WorktreeStatus[] = ['merged', 'cleaned'];

    for (const status of terminalStatuses) {
      const id = insertTestWorktree({
        status,
        branch: `forge/ttl-terminal-${status}`,
        worktree_path: `/tmp/ttl-terminal-${status}`,
      });
      db.run('UPDATE worktrees SET updated_at = ? WHERE id = ?', [oldDate, id]);

      const wt = getWorktree(db, id);
      const shouldFlag = !terminalStatuses.includes(wt!.status);
      expect(shouldFlag).toBe(false);
    }
  });

  test('active statuses are not flagged by TTL', () => {
    const oldDate = new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString();
    const activeStatuses: WorktreeStatus[] = ['running', 'auditing', 'proofing', 'merging'];

    for (const status of activeStatuses) {
      const id = insertTestWorktree({
        status,
        branch: `forge/ttl-active-${status}`,
        worktree_path: `/tmp/ttl-active-${status}`,
      });
      db.run('UPDATE worktrees SET updated_at = ? WHERE id = ?', [oldDate, id]);

      const wt = getWorktree(db, id);
      const shouldFlag = !activeStatuses.includes(wt!.status);
      expect(shouldFlag).toBe(false);
    }
  });

  test('recent non-terminal worktree is not flagged by TTL', () => {
    const id = insertTestWorktree({
      status: 'complete',
      branch: 'forge/ttl-recent',
      worktree_path: '/tmp/ttl-recent',
    });

    const wt = getWorktree(db, id);
    const age = Date.now() - new Date(wt!.updated_at).getTime();
    const ttlMs = 7 * 24 * 60 * 60 * 1000;

    expect(age).toBeLessThan(ttlMs);
  });

  test('configurable TTL via worktreePruneTtlDays', () => {
    // Default is 7 days, configurable via .forge/config.json
    const ttlDays = 7;
    const ttlMs = ttlDays * 24 * 60 * 60 * 1000;
    expect(ttlMs).toBe(604800000); // 7 days in ms

    // Custom TTL: 3 days
    const customTtlDays = 3;
    const customTtlMs = customTtlDays * 24 * 60 * 60 * 1000;
    expect(customTtlMs).toBe(259200000);
  });
});

// ── Registry status update on prune ─────────────────────────────

describe('registry status update after prune', () => {
  test('pruned worktree status updated to cleaned', () => {
    const id = insertTestWorktree({
      status: 'merged',
      branch: 'forge/prune-clean',
      worktree_path: '/tmp/prune-clean',
    });

    // Simulate prune: update to cleaned
    updateWorktreeStatus(db, id, 'cleaned');

    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('cleaned');
    expect(wt!.error).toBeNull();
  });

  test('already-cleaned worktrees remain cleaned after prune', () => {
    const id = insertTestWorktree({
      status: 'cleaned',
      branch: 'forge/already-clean',
      worktree_path: '/tmp/already-clean',
    });

    // Should not throw when already cleaned
    const wt = getWorktree(db, id);
    expect(wt!.status).toBe('cleaned');
  });
});

// ── Branch cleanup uses -d (safe delete) ────────────────────────

describe('branch cleanup safety', () => {
  test('branch deletion uses -d flag not -D for safety', () => {
    // The prune implementation uses: git branch -d "<branch>"
    // NOT: git branch -D "<branch>"
    // -d requires the branch to be fully merged (safe)
    // -D force-deletes regardless (unsafe)
    const deleteCmd = `git branch -d "forge/test-branch"`;
    expect(deleteCmd).toContain('-d');
    expect(deleteCmd).not.toContain('-D');
  });
});

// ── Dry-run mode ────────────────────────────────────────────────

describe('dry-run mode', () => {
  test('dry-run identifies worktrees that would be pruned without modifying state', () => {
    const id1 = insertTestWorktree({
      status: 'merged',
      branch: 'forge/dry1',
      worktree_path: '/tmp/dry1',
    });
    const id2 = insertTestWorktree({
      status: 'complete',
      branch: 'forge/dry2',
      worktree_path: '/tmp/dry2',
    });

    // Default prune targets: merged and cleaned
    const allWorktrees = listWorktrees(db);
    const prunableStatuses = new Set<WorktreeStatus>(['merged', 'cleaned']);
    const wouldPrune = allWorktrees.filter(w => prunableStatuses.has(w.status));

    expect(wouldPrune).toHaveLength(1);
    expect(wouldPrune[0].id).toBe(id1);

    // Verify nothing was modified (dry-run)
    expect(getWorktree(db, id1)!.status).toBe('merged');
    expect(getWorktree(db, id2)!.status).toBe('complete');
  });
});

// ── Mixed scenario: multiple statuses ───────────────────────────

describe('prune with mixed statuses', () => {
  test('only merged and cleaned are pruned in default mode', () => {
    insertTestWorktree({ status: 'running', branch: 'forge/mix-r', worktree_path: '/tmp/mix-r' });
    insertTestWorktree({ status: 'complete', branch: 'forge/mix-c', worktree_path: '/tmp/mix-c' });
    insertTestWorktree({ status: 'failed', branch: 'forge/mix-f', worktree_path: '/tmp/mix-f' });
    const mergedId = insertTestWorktree({ status: 'merged', branch: 'forge/mix-m', worktree_path: '/tmp/mix-m' });
    const cleanedId = insertTestWorktree({ status: 'cleaned', branch: 'forge/mix-cl', worktree_path: '/tmp/mix-cl' });

    const allWorktrees = listWorktrees(db);
    const defaultPrunable = new Set<WorktreeStatus>(['merged', 'cleaned']);
    const activeStatuses = new Set<WorktreeStatus>(['running', 'auditing', 'proofing', 'merging']);

    const actions = allWorktrees.filter(
      w => !activeStatuses.has(w.status) && defaultPrunable.has(w.status)
    );

    expect(actions).toHaveLength(2);
    const actionIds = actions.map(a => a.id);
    expect(actionIds).toContain(mergedId);
    expect(actionIds).toContain(cleanedId);
  });

  test('force mode prunes all non-active statuses', () => {
    insertTestWorktree({ status: 'running', branch: 'forge/fmix-r', worktree_path: '/tmp/fmix-r' });
    insertTestWorktree({ status: 'complete', branch: 'forge/fmix-c', worktree_path: '/tmp/fmix-c' });
    insertTestWorktree({ status: 'failed', branch: 'forge/fmix-f', worktree_path: '/tmp/fmix-f' });
    insertTestWorktree({ status: 'merged', branch: 'forge/fmix-m', worktree_path: '/tmp/fmix-m' });

    const forceSet = new Set<WorktreeStatus>([
      'created', 'complete', 'failed', 'audited', 'proofed',
      'ready', 'paused', 'merge_failed', 'merged', 'cleaned',
    ]);
    const activeStatuses = new Set<WorktreeStatus>(['running', 'auditing', 'proofing', 'merging']);

    const allWorktrees = listWorktrees(db);
    const forceActions = allWorktrees.filter(
      w => !activeStatuses.has(w.status) && forceSet.has(w.status)
    );

    // complete, failed, merged should be prunable (not running)
    expect(forceActions).toHaveLength(3);
  });
});
